begin;
select plan(23);
select has_table('public','miller_quiet_maintenance_runs','quiet maintenance run ledger exists');
select has_table('public','miller_quiet_maintenance_actions','quiet maintenance action audit exists');
select ok(not has_table_privilege('anon','public.miller_quiet_maintenance_runs','select,insert,update,delete'),'anonymous callers cannot access quiet runs');
select ok(not has_table_privilege('authenticated','public.miller_quiet_maintenance_runs','select,insert,update,delete'),'ordinary callers cannot access quiet runs');
select ok(not has_table_privilege('anon','public.miller_quiet_maintenance_actions','select,insert,update,delete'),'anonymous callers cannot access quiet action audit');
select ok(not has_table_privilege('authenticated','public.miller_quiet_maintenance_actions','select,insert,update,delete'),'ordinary callers cannot access quiet action audit');
select has_function('public','start_quiet_maintenance_cycle',array['text','text','text','uuid','timestamp with time zone'],'start RPC exists');
select has_function('public','apply_quiet_maintenance_cycle',array['uuid','jsonb'],'atomic apply RPC exists');
select has_function('public','fail_quiet_maintenance_cycle',array['uuid','text'],'safe failure RPC exists');
select ok(not has_function_privilege('anon','public.start_quiet_maintenance_cycle(text,text,text,uuid,timestamp with time zone)','execute'),'anonymous callers cannot start a cycle');
select ok(not has_function_privilege('authenticated','public.apply_quiet_maintenance_cycle(uuid,jsonb)','execute'),'ordinary callers cannot apply a plan');
select function_privs_are('public','start_quiet_maintenance_cycle',array['text','text','text','uuid','timestamp with time zone'],'service_role',array['EXECUTE'],'only service role starts cycles');
select function_privs_are('public','apply_quiet_maintenance_cycle',array['uuid','jsonb'],'service_role',array['EXECUTE'],'only service role applies plans');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name in ('miller_quiet_maintenance_runs','miller_quiet_maintenance_actions') and column_name in ('query','raw_query','session_id','user_id','ip_address','device_id','email','phone')),'maintenance schema has no raw or identifying fields');
select col_is_unique('public','miller_quiet_maintenance_runs',array['request_key'],'request keys make retries inspectable');
insert into auth.users(id,instance_id,aud,role,email,encrypted_password,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values ('00000000-0000-0000-0000-000000005001','00000000-0000-0000-0000-000000000000','authenticated','authenticated','quiet-maintenance@example.invalid','','{}','{}',now(),now());
insert into public.miller_attention_topics(id,topic_key,topic_type,title,state,status,current_score,version) values ('00000000-0000-0000-0000-000000005002','service_system:quiet_fixture','service_system','Quiet fixture','focus','active',50,1);
insert into public.miller_coverage_hypotheses(id,hypothesis_key,kind,theme,geography,strength_band,coverage_state,uncertainty_reason,matching_resource_count,status,research_question,expires_at) values ('00000000-0000-0000-0000-000000005003',repeat('a',64),'need','transportation','fraser','recurring','represented','coverage_present_discoverability_unknown',3,'evidence_available','Does this fixture have current directory evidence?','2026-12-31T00:00:00Z');
insert into public.miller_need_observation_buckets(bucket_key,source,schema_version,kind,theme,geography,observed_hour,expires_at) values (repeat('b',64),'public_directory_search','human-needs-v1','need','transportation','fraser','2026-01-01T00:00:00Z','2026-01-02T00:00:00Z');
set local role service_role;
select set_config('request.jwt.claim.role','service_role',true);
select is((select status from public.start_quiet_maintenance_cycle(repeat('c',64),'local_test','local_manual','00000000-0000-0000-0000-000000005001','2026-02-01T00:00:00Z')),'running','service role can start a local maintenance cycle');
select is((select status from public.apply_quiet_maintenance_cycle((select id from public.miller_quiet_maintenance_runs where request_key=repeat('c',64)),jsonb_build_object('attention_updates',jsonb_build_array(jsonb_build_object('action_key',repeat('d',64),'topic_id','00000000-0000-0000-0000-000000005002','expected_version',1,'prior_score',50,'prior_state','focus','next_score',20,'next_state','watch','reason_codes','["fixture"]'::jsonb)),'hypothesis_updates',jsonb_build_array(jsonb_build_object('action_key',repeat('e',64),'hypothesis_id','00000000-0000-0000-0000-000000005003','expected_status','evidence_available','next_status','resolved','reason_codes','["fixture"]'::jsonb)),'expired_buckets',jsonb_build_array(jsonb_build_object('action_key',repeat('f',64),'bucket_key',repeat('b',64))),'reflections','[]'::jsonb,'inspected_counts','{}'::jsonb,'action_counts','{}'::jsonb,'carry_forward','[]'::jsonb,'result_summary','{}'::jsonb))),'completed','atomic apply completes the run');
select is((select current_score from public.miller_attention_topics where id='00000000-0000-0000-0000-000000005002'),20::numeric,'attention regulation is applied');
select is((select status from public.miller_coverage_hypotheses where id='00000000-0000-0000-0000-000000005003'),'resolved','only explicit derived hypothesis transition is applied');
select is((select count(*) from public.miller_need_observation_buckets where bucket_key=repeat('b',64)),0::bigint,'expired aggregate bucket is forgotten');
select is((select count(*) from public.miller_quiet_maintenance_actions where run_id=(select id from public.miller_quiet_maintenance_runs where request_key=repeat('c',64))),3::bigint,'each automatic derived-state action is audited');
select is((select id from public.start_quiet_maintenance_cycle(repeat('c',64),'local_test','local_manual','00000000-0000-0000-0000-000000005001','2026-02-01T00:00:00Z')),(select id from public.miller_quiet_maintenance_runs where request_key=repeat('c',64)),'repeated start returns the existing auditable run');
select throws_like($$delete from public.miller_quiet_maintenance_actions$$,'resource fact audit is append-only','quiet maintenance action audit cannot be deleted');
reset role;
select * from finish();
rollback;
