begin;
select plan(19);
select has_column('public','miller_security_pulse_runs','target_id','pulse binds a target');
select has_column('public','miller_security_pulse_runs','profile_version','pulse records profile version');
select has_table('public','miller_security_capabilities','capability registry exists');
select has_table('public','miller_security_sensor_outcomes','sensor outcome history exists');
select has_table('public','miller_security_observers','external observer allowlist exists');
select has_table('public','miller_external_security_observations','external observations exist');
select col_is_pk('public','miller_security_capabilities',array['target_id','capability_id'],'capability identity is target-scoped');
select col_is_unique('public','miller_security_sensor_outcomes',array['run_id','instrument_id'],'one outcome per sensor per run');
select ok(not has_table_privilege('anon','public.miller_security_capabilities','select,insert,update,delete'),'anon cannot access capabilities');
select ok(not has_table_privilege('authenticated','public.miller_security_sensor_outcomes','select,insert,update,delete'),'ordinary users cannot access sensor outcomes');
select ok(not has_table_privilege('authenticated','public.miller_security_observers','select,insert,update,delete'),'ordinary users cannot administer observer allowlist');
select ok(not exists(select 1 from pg_policies where schemaname='public' and tablename in ('miller_security_capabilities','miller_security_sensor_outcomes','miller_security_observers','miller_external_security_observations') and roles && array['anon'::name]),'no anonymous security-data policies exist');
select ok(has_table_privilege('service_role','public.miller_security_capabilities','select,insert,update'),'service role can maintain code-defined capability state');
select ok(has_table_privilege('service_role','public.miller_security_sensor_outcomes','select,insert'),'service role can append outcomes');
select ok(not has_table_privilege('service_role','public.miller_security_sensor_outcomes','delete'),'service role cannot erase outcome history');
select ok(has_function_privilege('authenticated','public.record_external_security_observation(text,text,text,timestamptz,text,jsonb)','execute'),'only authenticated allowlisted observer identity can submit observations');
select ok(not has_function_privilege('anon','public.record_external_security_observation(text,text,text,timestamptz,text,jsonb)','execute'),'anon cannot submit external observations');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name in ('miller_security_sensor_outcomes','miller_external_security_observations') and column_name in ('request_body','authorization','token','cookie','secret','raw_payload')),'security records exclude raw credentials and payloads');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='miller_security_sensor_outcomes_target_recent_idx'),'outcome history is indexed by target and sensor');
select * from finish();
rollback;
