import test from "node:test"
import assert from "node:assert/strict"
import { ATTENTION_LIMITS, FREE_SENSOR_ADAPTERS, SENSOR_CADENCE, attentionCuriosityQuestions, attentionSignalFingerprint, attentionTopicKey, recalculateTopic, signalContribution } from "../server/attentionEngine.js"
const now = "2026-08-22T00:00:00.000Z"
const signal = (overrides = {}) => ({ topic_key: "treatment:stimulants", signal_type: "scientific_evidence", signal_family: "scientific", source_id: "pubmed", source_authority: 95, magnitude: 1, novelty: 1, relevance: 1, confidence: 1, observed_at: now, decay_class: "slow", underlying_event_key: "event-a", reason_codes: ["fixture"], provenance: { evidence_class: "systematic_review" }, ...overrides })

test("attention topics and signals have stable deterministic identities", () => { assert.equal(attentionTopicKey({ topic_type: "treatment", subject: "Contingency Management" }), "treatment:contingency_management"); assert.equal(attentionSignalFingerprint(signal()), attentionSignalFingerprint(signal())) })
test("duplicate copies of one announcement are capped while independent families converge", () => { const topic = { topic_key: "treatment:stimulants", status: "active", current_score: 0 }, copies = Array.from({ length: 5 }, (_, i) => signal({ source_id: `copy-${i}`, underlying_event_key: "same-release", signal_family: "services", signal_type: "service_change", provenance: {} })), converged = [...copies, signal({ source_id: "bccdc", underlying_event_key: "toxic", signal_family: "toxic_drug", signal_type: "toxic_drug_alert", decay_class: "fast", reflex_eligible: true })]; assert.equal(recalculateTopic(topic, copies, now).unique_event_count, 1); assert.ok(recalculateTopic(topic, converged, now).current_score > recalculateTopic(topic, copies, now).current_score) })
test("low-authority cultural signal cannot create focus and score stays clamped", () => { const result = recalculateTopic({ topic_key: "cultural:language", status: "active", current_score: 0 }, Array.from({ length: 9 }, (_, i) => signal({ source_id: `c${i}`, underlying_event_key: `e${i}`, signal_family: "cultural", signal_type: "cultural_signal", source_authority: 20, decay_class: "fast", provenance: {} })), now); assert.notEqual(result.state, "focus"); assert.ok(result.current_score <= ATTENTION_LIMITS.maxScore) })
test("authoritative reflex event becomes urgent review but is only a state", () => { const result = recalculateTopic({ topic_key: "resource:one", status: "active", current_score: 0 }, [signal({ signal_type: "service_change", signal_family: "services", source_authority: 95, reflex_eligible: true, underlying_event_key: "closure", provenance: {} })], now); assert.equal(result.state, "urgent_review"); assert.equal(result.canonical_mutation, undefined) })
test("decay, resolution, and later reinforcement are deterministic", () => { const topic = { topic_key: "policy:oat", status: "active", current_score: 60 }, old = signal({ observed_at: "2024-01-01T00:00:00.000Z", decay_class: "fast", underlying_event_key: "old", provenance: {} }), falling = recalculateTopic(topic, [old], now), resolved = recalculateTopic({ ...topic, status: "resolved" }, [old], now), reactivated = recalculateTopic({ ...resolved, status: "active" }, [old, signal({ underlying_event_key: "new", provenance: {} })], now); assert.equal(falling.trend, "falling"); assert.equal(resolved.state, "background"); assert.ok(reactivated.current_score > resolved.current_score) })
test("scientific evidence, pharmacology, and toxic-drug signal classes retain distinct bounds", () => { assert.ok(signalContribution(signal({ provenance: { evidence_class: "single_study" } }), now) < signalContribution(signal({ provenance: { evidence_class: "guideline" } }), now)); assert.equal(SENSOR_CADENCE.toxic_drug_alerts, "fast"); assert.ok(FREE_SENSOR_ADAPTERS.some((item) => item.family === "pharmacology")); assert.ok(FREE_SENSOR_ADAPTERS.some((item) => item.family === "scientific")) })
test("only attended active non-protected topics create bounded curiosity questions", () => { const questions = attentionCuriosityQuestions([{ topic_key: "x", state: "focus", status: "active", current_score: 60 }, { topic_key: "secret", state: "urgent_review", status: "active", current_score: 99, protected: true }, { topic_key: "old", state: "background", status: "active", current_score: 5 }]); assert.equal(questions.length, 1); assert.equal(questions[0].requires_human_authorization, true) })
