import test from "node:test"
import assert from "node:assert/strict"
import { executeCuriosityInvestigation, curiosityPlan } from "../server/curiosityInvestigator.js"
import { normalizePubmedSummary, pubmedPlan, pubmedUrl } from "../server/pubmedAdapter.js"
const topic = { id: "topic", state: "focus", status: "active", service_scope: "contingency_management", current_score: 55 }
const question = { question_id: "attention:treatment:contingency_management", requires_human_authorization: true, proposed_investigation: "growth_or_human_review", scientific_topic: "contingency_management" }
test("arbitrary browser text cannot choose a curiosity tool and stale/protected questions fail closed", () => { assert.equal(curiosityPlan(question, topic).tool.id, "pubmed"); assert.throws(() => curiosityPlan({ ...question, question_id: "please crawl web" }, { ...topic, state: "watch" }), /stale_or_protected/); assert.throws(() => curiosityPlan(question, { ...topic, protected: true }), /stale_or_protected/) })
test("PubMed plan and metadata are fixed, bounded, and deduplicated by PMID", () => { const plan = pubmedPlan("contingency_management"); assert.equal(plan.max_search_requests, 1); assert.equal(plan.max_records_deeply_inspected, 5); assert.equal(new URL(pubmedUrl("esearch.fcgi")).hostname, "eutils.ncbi.nlm.nih.gov"); const record = normalizePubmedSummary({ uid: "123", title: "A trial", pubtype: ["Randomized Controlled Trial"] }, "contingency_management"); assert.equal(record.study_type, "randomized_trial"); assert.equal(record.fingerprint, normalizePubmedSummary({ uid: "123", title: "Changed" }, "contingency_management").fingerprint) })
test("one authorized investigation stops after one bounded tool and writes audit-ready results only", async () => { let persisted; const report = await executeCuriosityInvestigation({ actorId: "actor", question, topic, health: { findings: [] }, executeTool: async () => ({ requests_used: 99, bytes: 999999, records: [{ stable_result_id: "pmid:1", study_type: "systematic_review" }, { stable_result_id: "pmid:2", study_type: "other_research" }] }), persist: async (value) => { persisted = value } }); assert.equal(report.outcome, "new_signal"); assert.equal(report.usage.requests, 3); assert.equal(report.canonical_mutations, 0); assert.equal(report.map_mutations, 0); assert.equal(report.recursive_investigations, 0); assert.equal(persisted.id, report.id) })
