import test from "node:test"
import assert from "node:assert/strict"
import { normalizeProviderResult, providerCacheKey, providerConfiguration } from "../server/geocodingProviders.js"
import { evaluateGeocodingConsensus } from "../server/geocodingConsensus.js"
import { assessLocationSensitivity } from "../server/locationSensitivity.js"

const result = (provider, latitude = 49.2827, longitude = -123.1207, extra = {}) => normalizeProviderResult({ provider, query: "10 Main St, Vancouver, BC", returned_address: "10 Main St, Vancouver, BC", latitude, longitude, result_type: "address", precision: "civic_number", street_number_match: true, municipality_match: true, province_match: true, country_match: true, provider_result_id: `${provider}-10`, ...extra })
const safety = { specific_program_public: true, specific_location_public: true, hard_exclusion: false }

test("normalized contract retains licensing and provider-specific cache identity", () => { const item = result("bc_address_geocoder"); assert.equal(item.license.permits_persistent_storage, true); assert.notEqual(providerCacheKey("bc_address_geocoder", "10 Main"), providerCacheKey("geoapify", "10 Main")) })
test("providers are disabled by default and configuration never returns secret values", () => { const config = providerConfiguration({ GEOAPIFY_API_KEY: "secret" }); assert.ok(config.every((x) => x.enabled === false)); assert.equal(JSON.stringify(config).includes("secret"), false) })
test("independent storage-compatible exact results within 35 metres reach Tier A", () => { const decision = evaluateGeocodingConsensus({ results: [result("bc_address_geocoder"), result("geoapify", 49.28275, -123.1207)], authoritativeAddress: true, safety }); assert.equal(decision.tier, "A"); assert.equal(decision.failed_hard_gates.length, 0) })
test("shared underlying datasets are not independent", () => { const decision = evaluateGeocodingConsensus({ results: [result("nominatim"), result("geoapify")], authoritativeAddress: true, safety }); assert.notEqual(decision.tier, "A"); assert.ok(decision.failed_hard_gates.includes("independent_underlying_datasets_required")) })
test("licensing, centroid, mismatch, distance, and safety gates fail closed", () => { const cases = [[result("google"), result("bc_address_geocoder")], [result("bc_address_geocoder", 49.28, -123.12, { precision: "parcel centroid" }), result("geoapify")], [result("bc_address_geocoder", 49.28, -123.12, { street_number_match: false }), result("geoapify")], [result("bc_address_geocoder"), result("geoapify", 49.29, -123.12)]]; for (const results of cases) assert.notEqual(evaluateGeocodingConsensus({ results, authoritativeAddress: true, safety }).tier, "A"); assert.notEqual(evaluateGeocodingConsensus({ results: [result("bc_address_geocoder"), result("geoapify")], authoritativeAddress: true, safety: { ...safety, hard_exclusion: true } }).tier, "A") })
test("public storefront does not inherit parent housing risk, while residential program does", () => { const storefront = assessLocationSensitivity({ program: { name: "Public thrift shop" }, location: { type: "fixed", publiclyAdvertised: true }, facility: { type: "storefront" }, parentOrganization: { activities: "housing and shelters" } }); assert.equal(storefront.hard_exclusion, false); assert.equal(storefront.specific_location_public, true); assert.equal(storefront.parent_organization_warning, true); const home = assessLocationSensitivity({ program: { name: "Residential treatment" }, location: { type: "fixed", publiclyAdvertised: true }, facility: { type: "residence" }, parentOrganization: { activities: "housing" } }); assert.equal(home.hard_exclusion, true) })
test("public clinic remains eligible while confidential sibling program is excluded", () => { const clinic = assessLocationSensitivity({ program: { name: "Public health clinic" }, location: { type: "fixed", publiclyAdvertised: true }, facility: { type: "clinic" }, parentOrganization: { activities: "women and youth services" } }); const confidential = assessLocationSensitivity({ program: { name: "Confidential counselling program" }, location: { type: "confidential", publiclyAdvertised: false }, facility: { type: "clinic" }, parentOrganization: { activities: "women and youth services" } }); assert.equal(clinic.specific_program_public, true); assert.equal(confidential.hard_exclusion, true) })
