import test from "node:test"
import assert from "node:assert/strict"
import { HEALTH_CANADA, classifyHealthCanadaRecord, extractHealthCanadaRecords, fetchHealthCanadaFeed, healthCanadaUrl, inspectHealthCanadaPayload } from "../server/healthCanadaAdapter.js"
import { HEALTH_CANADA_PLAN, inspectHealthCanada, runHealthCanadaInspection } from "../server/healthCanadaSensor.js"
const oat={NID:"123",Title:"Methadone product safety alert",Category:"Health product recall","Last updated":"2026-08-22",URL:"https://recalls-rappels.canada.ca/en/alert-recall"}
test("Health Canada adapter has a fixed official feed endpoint",()=>{assert.equal(healthCanadaUrl(HEALTH_CANADA.endpoint).hostname,"recalls-rappels.canada.ca");assert.throws(()=>healthCanadaUrl("https://evil.invalid/data/api/3/action/package_show"),/allowlist/)})
test("controlled OAT relevance accepts a safety record and rejects unrelated recall",()=>{assert.equal(classifyHealthCanadaRecord(oat).medication,"methadone");assert.equal(classifyHealthCanadaRecord({id:"x",title:"toddler toy recall",category:"recall"}),null)})
test("successful zero differs from duplicate and parser failure",()=>{const first=inspectHealthCanadaPayload({result:{records:[oat]}});assert.equal(first.status,"inspection_success_new_relevant_change");const duplicate=inspectHealthCanadaPayload({result:{records:[oat]}},{last_fingerprint:first.accepted[0].fingerprint});assert.equal(duplicate.status,"inspection_success_no_relevant_change");assert.equal(duplicate.duplicates_ignored,1);assert.throws(()=>inspectHealthCanadaPayload({unexpected:true}),/schema_drift/)})
test("sensor plan is fixed and produces a private pharmacology signal contract",()=>{const inspection=inspectHealthCanada({result:{records:[oat]}});assert.equal(HEALTH_CANADA_PLAN.max_requests,1);assert.equal(inspection.signals[0].signal_family,"pharmacology");assert.equal(inspection.plan.no_canonical_mutation,true);assert.equal(inspection.checkpoint.health_state,"healthy")})
test("bounded range parser accepts only complete leading JSON records",()=>{const text=`[${JSON.stringify(oat)},${JSON.stringify({...oat,NID:"124"})},`;assert.equal(extractHealthCanadaRecords(text).length,2);assert.throws(()=>extractHealthCanadaRecords("{}"),/schema_drift/)})
test("fixed fetch sends one range request and rejects invalid source responses",async()=>{let options;const mock=async(_url,input)=>{options=input;return new Response(`[${JSON.stringify(oat)},`,{status:206,headers:{"content-type":"application/json","content-length":"200"}})};const result=await fetchHealthCanadaFeed({fetchImpl:mock});assert.equal(result.records.length,1);assert.equal(options.headers.Range,`bytes=0-${HEALTH_CANADA.maxBytes-1}`);await assert.rejects(()=>fetchHealthCanadaFeed({fetchImpl:async()=>new Response("x",{status:200,headers:{"content-type":"text/html"}})}),/content_type/)})
test("inspection produces a bounded auditable result",async()=>{const result=await runHealthCanadaInspection({fetchImpl:async()=>new Response(`[${JSON.stringify(oat)},`,{status:206,headers:{"content-type":"application/json","content-length":"200"}})});assert.equal(result.request_count,1);assert.equal(result.records_accepted,1);assert.equal(result.signals[0].signal_family,"pharmacology")})
