import test from "node:test"
import assert from "node:assert/strict"
import { HUMAN_NEEDS, activeNeedWorkspace, aggregateNeedSignal, classifyHumanNeed, humanNeedBucketKey } from "../server/humanNeedsSense.js"

const sensitive = "My daughter Sarah is 16 and needs detox near 123 Example Street. Call 604-555-0123."
test("Human Needs returns only controlled aggregate labels and never raw input", () => { const result = classifyHumanNeed(sensitive, "Surrey"); assert.equal(result.raw_retained, false); assert.equal(result.sensitive_entity_detected, true); assert.deepEqual(result.observations[0], { kind: "need", theme: "withdrawal_management", geography: "fraser" }); assert.doesNotMatch(JSON.stringify(result), /Sarah|123 Example|604-555/) })
test("no user, session, device, or free-form dimension can reach a bucket identity", () => { const bucket = humanNeedBucketKey({ kind: "need", theme: "youth_services", geography: "fraser", observedAt: "2026-08-23T02:00:00Z" }); assert.match(bucket, /^[a-f0-9]{64}$/); assert.equal(HUMAN_NEEDS.enabled({}), false) })
test("low support is suppressed while thresholded demand produces only coarse signal provenance", () => { const low = { observation_count: 4 }, full = { bucket_key: "a".repeat(64), kind: "need", theme: "withdrawal_management", geography: "fraser", observation_count: 5, last_observed_at: "2026-08-23T02:00:00Z" }; assert.equal(aggregateNeedSignal(low), null); const signal = aggregateNeedSignal(full); assert.equal(signal.provenance.raw_query_retained, false); assert.equal(signal.provenance.user_linkage, false); assert.doesNotMatch(JSON.stringify(signal), /Sarah|street|phone/i) })
test("working memory is bounded and expired buckets cannot remain active", () => { const items = Array.from({ length: 25 }, (_, index) => ({ bucket_key: String(index), kind: "need", theme: "counselling", geography: "province", observation_count: 5 + index, expires_at: "2026-09-01T00:00:00Z" })); items.push({ bucket_key: "expired", kind: "need", theme: "counselling", geography: "province", observation_count: 99, expires_at: "2026-08-01T00:00:00Z" }); assert.equal(activeNeedWorkspace(items, "2026-08-23T00:00:00Z").length, 20) })
