import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs"
import { buildExceptionQueue, evaluateClaim } from "../server/intelligence/evidenceEngine.js"
import { classifyLocationCandidate, locationDryRun } from "../server/intelligence/locationAutomation.js"
import { collectProviderResults, planRetrieval } from "../server/intelligence/orchestration.js"
import { normalizeResourceCandidate, resolveCandidateEntity } from "../server/intelligence/resourceCandidates.js"
import { barrierCompatibility, extractExplicitBarrierIntent, normalizeBarrierProfile } from "../server/intelligence/barriers.js"
import { nextSupportCategories } from "../server/intelligence/continuity.js"
import { automationMetrics, detectFactChange, recheckPriority } from "../server/intelligence/maintenance.js"

const now = new Date("2026-08-20T12:00:00Z")
const official = (value, extras = {}) => ({ sourceType: "official_provider", value, url: "https://provider.example/program", retrievedAt: "2026-08-19T12:00:00Z", independentKey: "provider.example", ...extras })
const directory = (value) => ({ sourceType: "established_directory", value, url: "https://directory.example/item", retrievedAt: "2026-08-18T12:00:00Z", independentKey: "directory.example" })

test("low-risk official facts auto-accept with explainable reasons", () => { const result = evaluateClaim({ subjectId: "r1", field: "phone", proposedValue: "604-555-1234", evidence: [official("604-555-1234")] }, { now }); assert.equal(result.decision, "auto_accept"); assert.ok(result.reasonCodes.includes("official_source_agreement")); assert.equal(result.risk, "low") })
test("two independent sources agree without becoming a resource-level confidence", () => { const result = evaluateClaim({ subjectId: "r1", field: "phone", proposedValue: "6045551234", evidence: [{ ...directory("6045551234"), sourceType: "established_directory" }, { ...directory("604-555-1234"), independentKey: "health-directory.example" }] }, { now }); assert.equal(result.decision, "auto_accept"); assert.equal(result.agreement.independentSources, 2); assert.equal("resourceConfidence" in result, false) })
test("official conflict with trusted Miller fact is exception review", () => { const result = evaluateClaim({ subjectId: "r1", field: "phone", proposedValue: "604-555-9999", existingTrustedValue: "604-555-1234", evidence: [official("604-555-9999")] }, { now }); assert.equal(result.decision, "human_review"); assert.ok(result.reasonCodes.includes("conflicts_with_existing_verified_fact")) })
test("stale and unknown evidence do not silently publish", () => { const stale = evaluateClaim({ subjectId: "r1", field: "hours", proposedValue: "9-5", evidence: [{ ...official("9-5"), retrievedAt: "2020-01-01T00:00:00Z" }] }, { now }); assert.equal(stale.decision, "accept_with_monitoring"); assert.equal(evaluateClaim({ subjectId: "r1", field: "phone", proposedValue: "6045551234", evidence: [] }, { now }).decision, "unknown") })
test("high-risk and LLM-only claims always require human review", () => { assert.equal(evaluateClaim({ subjectId: "r1", field: "eligibility", proposedValue: "accepted", evidence: [official("accepted")] }, { now }).decision, "human_review"); assert.equal(evaluateClaim({ subjectId: "r1", field: "phone", proposedValue: "6045551234", evidence: [{ sourceType: "llm_extraction", value: "6045551234", retrievedAt: now.toISOString() }] }, { now }).reasonCodes[0], "llm_not_independent_evidence") })
test("private location risk rejects and creates an evidence-ready exception", () => { const result = evaluateClaim({ subjectId: "s1", field: "address", proposedValue: "100 Hidden Rd", evidence: [official("100 Hidden Rd")], safetyFlags: ["private_location"] }, { now }); assert.equal(result.decision, "reject"); const queue = buildExceptionQueue([result]); assert.equal(queue.length, 1); assert.deepEqual(queue[0].suggestedActions, ["approve_suggestion", "keep_existing", "reject", "mark_unknown"]) })

const baseLocation = { canonical_uuid: "r1", resource_name: "Clinic", tier: "A", source_evidence_tier: "E1", evidence_review_status: "approved", program_occupancy_confidence: "supported", score: 100, coordinates: { latitude: 49.2, longitude: -123.1 }, sensitivity_flags: [], conflicts: [], submitted_has_unit: false, returned_has_unit: false, shared_address_count: 1 }
test("exact supported public program address is auto-validatable", () => { const result = classifyLocationCandidate(baseLocation); assert.equal(result.decision, "auto_validatable"); assert.ok(result.reasonCodes.includes("bc_geocoder_exact_match")) })
test("parent/occupancy ambiguity and shared unresolved building require review", () => { assert.equal(classifyLocationCandidate({ ...baseLocation, tier: "B", program_occupancy_confidence: "unverified", source_evidence_tier: "E3" }).decision, "needs_review"); assert.ok(classifyLocationCandidate({ ...baseLocation, tier: "B", shared_address_count: 2, shared_address_group: null }).reasonCodes.includes("address_shared_by_multiple_programs")) })
test("virtual, confidential, and failed geocoder locations do not map", () => { for (const record of [{ ...baseLocation, location_type: "virtual" }, { ...baseLocation, sensitivity_flags: ["confidential"] }, { ...baseLocation, tier: "C" }]) assert.equal(classifyLocationCandidate(record).decision, "do_not_map") })
test("location dry-run is read-only and reports selective automation", () => { const report = locationDryRun([baseLocation, { ...baseLocation, canonical_uuid: "r2", tier: "B" }, { ...baseLocation, canonical_uuid: "r3", tier: "C" }]); assert.deepEqual(report.counts, { auto_validatable: 1, needs_review: 1, do_not_map: 1 }); assert.equal(report.mode, "read_only_dry_run") })

test("orchestrator calls only providers needed by explicit intent", () => { const plan = planRetrieval({ intent: { explicit: { supportNeeds: ["counselling"], locationText: "Gateway Station", city: null, transport: { transitRelevant: true } } }, selectedCandidate: { mapped: true } }); assert.deepEqual(plan.steps.map((x) => x.provider), ["miller", "geocoder", "transit"]); assert.equal(plan.allProviderFanout, false); assert.ok(plan.omitted.some((x) => x.provider === "tavily")); assert.ok(plan.omitted.some((x) => x.provider === "bc211")) })
test("provider failure preserves available results and provenance", () => { const plan = planRetrieval({ task: "maintenance" }), results = collectProviderResults(plan, { miller: [{ id: "r1" }] }); assert.equal(results.length, 1); assert.equal(results[0].provenance.provider, "miller"); assert.equal(plan.failurePolicy, "continue_with_trusted_miller_data") })

const candidate = (changes = {}) => normalizeResourceCandidate({ provider: "miller", sourceRecordId: "1", canonicalCandidateId: "c1", name: "Program A", operator: "Operator", location: { address: "100 Main St", city: "Surrey" }, contact: { phone: "604-555-1234", website: "https://operator.example/program-a" }, trustState: "trusted", ...changes })
test("provider-neutral candidate normalizes unavailable and unsafe fields", () => { const item = normalizeResourceCandidate({ provider: "future", name: " Test ", contact: { website: "javascript:alert(1)" } }); assert.equal(item.contact.website, ""); assert.equal(item.eligibility, null); assert.equal(item.trustState, "unknown") })
test("entity resolution requires program identity plus multiple signals for definite match", () => { const left = candidate(), right = candidate({ provider: "future211", sourceRecordId: "211-1" }); assert.equal(resolveCandidateEntity(left, right).classification, "definite_match"); assert.equal(resolveCandidateEntity(left, candidate({ name: "Program B" })).classification, "distinct") })
test("same website or operator alone never merges different programs", () => { const left = candidate(), right = candidate({ name: "Program B", contact: { phone: "", website: left.contact.website } }); assert.equal(resolveCandidateEntity(left, right).classification, "distinct") })
test("confirmed aliases and single-signal matches remain explicit", () => { const left = candidate(), right = candidate({ provider: "future211", sourceRecordId: "z", contact: { phone: "", website: "" }, location: null }); assert.equal(resolveCandidateEntity(left, right, [{ provider: "future211", sourceRecordId: "z", canonicalId: "c1" }]).classification, "definite_match"); assert.equal(resolveCandidateEntity(left, right).classification, "uncertain") })

test("barrier intent is explicit and profile preserves unknown", () => { const intent = extractExplicitBarrierIntent("I don't have ID, I need to walk in, and I use a wheelchair."); assert.equal(intent.noId, true); assert.equal(intent.walkInNeeded, true); const profile = normalizeBarrierProfile({ identification_required: { value: false, evidence: [official("false")] } }); assert.equal(profile.phone_required.value, "unknown"); assert.equal(barrierCompatibility(profile, intent).overall, "unknown") })
test("barrier matching distinguishes compatible, incompatible, and unknown", () => { const intent = extractExplicitBarrierIntent("I don't have a phone"); assert.equal(barrierCompatibility(normalizeBarrierProfile({ phone_required: false }), intent).overall, "known_compatible"); assert.equal(barrierCompatibility(normalizeBarrierProfile({ phone_required: true }), intent).overall, "known_incompatible"); assert.equal(barrierCompatibility(normalizeBarrierProfile({}), intent).overall, "unknown") })

test("continuity graph returns categories in neutral non-prescriptive language", () => { const next = nextSupportCategories("shelter"); assert.ok(next.suggestions.includes("food")); assert.match(next.message, /may also/); assert.equal(next.prescriptive, false) })
test("change detection preserves old and new values in append-only rollback proposal", () => { const change = detectFactChange({ subjectId: "r1", field: "phone", existingValue: "6045551234", proposedValue: "6045559999", evidence: [official("6045559999")] }, { now }); assert.equal(change.status, "changed"); assert.equal(change.recommendation, "human_review"); assert.equal(change.auditProposal.previousValue, "6045551234"); assert.equal(change.auditProposal.rollbackValue, "6045551234"); assert.equal(detectFactChange({ subjectId: "r1", field: "hours", existingValue: "9-5", proposedValue: "9-5", evidence: [] }, { now }).status, "unchanged") })
test("staleness priority is field-specific and missing sources are urgent", () => { assert.equal(recheckPriority({ field: "hours", lastVerifiedAt: "2026-01-01T00:00:00Z" }, now).priority, "high"); assert.equal(recheckPriority({ field: "coordinates", lastVerifiedAt: "2026-01-01T00:00:00Z" }, now).priority, "low"); assert.equal(recheckPriority({ field: "phone", lastVerifiedAt: now.toISOString(), sourceStillExists: false }, now).priority, "urgent") })
test("automation metrics contain no user data and measure routine handling", () => { const claims = [evaluateClaim({ subjectId: "r1", field: "phone", proposedValue: "6045551234", evidence: [official("6045551234")] }, { now })], locations = [classifyLocationCandidate(baseLocation)]; const metrics = automationMetrics({ claims, locations }); assert.equal(metrics.routineMaintenanceAutomationRate, 1); assert.equal(metrics.locationCandidatesAutoValidatable, 1); assert.equal(metrics.containsUserData, false) })
test("architecture treats provider content as bounded untrusted data", () => { const source = fs.readFileSync(new URL("../server/intelligence/evidenceEngine.js", import.meta.url), "utf8") + fs.readFileSync(new URL("../server/intelligence/resourceCandidates.js", import.meta.url), "utf8"); assert.match(source, /untrustedContent: true/); assert.doesNotMatch(source, /eval\(|innerHTML|fetch\(/) })
test("proposed evidence migration is private, append-only, rollback-ready, and disabled by default", () => { const sql = fs.readFileSync(new URL("../supabase/migrations/202608200001_create_resource_fact_evidence.sql", import.meta.url), "utf8"); assert.match(sql, /enable row level security/g); assert.match(sql, /revoke all[^;]+from anon, authenticated/); assert.match(sql, /before update or delete/); assert.match(sql, /previous_value jsonb/); assert.match(sql, /action in \('observe','accept','keep_existing','reject','mark_unknown','rollback'\)/); assert.match(sql, /observe_only boolean not null default true/); assert.match(sql, /low_risk_fact_updates_enabled boolean not null default false/); assert.doesNotMatch(sql, /grant\s+(?:insert|update|delete)[^;]+(?:anon|authenticated)/i) })
