import test from "node:test"
import assert from "node:assert/strict"
import { evaluateAutomaticLocation, LOCATION_POLICY_VERSION, selectQualityControlSample } from "../server/locationAutomationPolicy.js"

const base = { resource: { display_name: "Public clinic", lifecycle_state: "active", editorial_status: "approved" }, location: { location_type: "fixed", street_address: "10 Main St", city: "Vancouver", latitude: 49.2, longitude: -123.1 }, evidence: { source_identity_stable: true, public_fixed_facility: true, authoritative_source: true, source_url: "https://example.org/location", street_number_match: true, municipality_match: true, province_country_match: true, building_level: true, warnings: [] } }

test("Tier A requires every deterministic hard gate and records policy evidence", () => { const result = evaluateAutomaticLocation(base); assert.equal(result.tier, "A"); assert.equal(result.policy_version, LOCATION_POLICY_VERSION); assert.equal(result.failed_hard_gates.length, 0) })
test("a high score cannot override address, centroid, or authoritative-source failures", () => { for (const evidence of [{ ...base.evidence, street_number_match: false }, { ...base.evidence, centroid: true }, { ...base.evidence, authoritative_source: false }]) assert.notEqual(evaluateAutomaticLocation({ ...base, evidence }).tier, "A") })
test("sensitive, virtual, mobile, service-area, hidden, and human-decided records never reach Tier A", () => { const cases = [{ ...base, resource: { ...base.resource, display_name: "Confidential shelter" } }, { ...base, location: { ...base.location, location_type: "virtual" } }, { ...base, location: { ...base.location, location_type: "mobile" } }, { ...base, location: { ...base.location, location_type: "service_area" } }, { ...base, resource: { ...base.resource, editorial_status: "hidden" } }, { ...base, humanDecision: "rejected" }]; for (const item of cases) assert.notEqual(evaluateAutomaticLocation(item).tier, "A") })
test("shared addresses remain independently evaluated and are only a warning", () => { const result = evaluateAutomaticLocation({ ...base, evidence: { ...base.evidence, address_peer_count: 3 } }); assert.equal(result.tier, "A"); assert.ok(result.warnings.includes("shared_address")) })
test("quality-control sampling is deterministic and at least five for qualifying batches", () => { const items = Array.from({ length: 20 }, (_, i) => ({ resource_id: String(20 - i) })); assert.deepEqual(selectQualityControlSample(items), selectQualityControlSample(items)); assert.equal(selectQualityControlSample(items).length, 5) })
test("automation runner is bounded, cached, audited, and explicit", async () => { const fs = await import("node:fs"); const source = fs.readFileSync(new URL("../scripts/location-automation-1j.mjs", import.meta.url), "utf8"); assert.match(source, /MAX = 50/); assert.match(source, /addressCacheKey/); assert.match(source, /actor_type: "automated_deterministic_policy"/); assert.match(source, /policy_version/); assert.match(source, /--apply/); assert.match(source, /human_decisions_reconsidered/) })
test("protected human overrides and global pause remain server-side", async () => { const fs = await import("node:fs"); const source = fs.readFileSync(new URL("../server.js", import.meta.url), "utf8"); assert.match(source, /app\.post\("\/api\/admin\/location-automation\/pause", requireAdmin/); assert.match(source, /automatedLocationPublicationEnabled = false/); assert.match(source, /automated reapproval is prohibited/); assert.match(source, /permanent_manual_review/) })
