import test from "node:test"
import assert from "node:assert/strict"
import { evaluateAutomaticLocation, LOCATION_POLICY_VERSION, selectQualityControlSample } from "../server/locationAutomationPolicy.js"
import { normalizeBcAddressResult } from "../server/bcAddressGeocoder.js"

const feature = { geometry: { coordinates: [-123.1, 49.2] }, properties: { fullAddress: "10 Main St, Vancouver, BC", streetName: "Main St", localityName: "Vancouver", provinceCode: "BC", score: 100, precisionPoints: 100, matchPrecision: "CIVIC_NUMBER", locationDescriptor: "parcelPoint", siteID: "fixture", faults: [] } }
const bc = normalizeBcAddressResult(feature, { street_address: "10 Main St", city: "Vancouver", result_count: 1 })
const base = { resource: { display_name: "Public clinic", lifecycle_state: "active", editorial_status: "approved" }, location: { location_type: "fixed", street_address: "10 Main St", city: "Vancouver", latitude: 49.2, longitude: -123.1 }, evidence: { source_identity_stable: true, public_fixed_facility: true, program_specific_address: true, public_client_facing: true, bc_result: bc } }

test("Tier A accepts an authoritative parcel point under v1.2.1", () => { const result = evaluateAutomaticLocation(base); assert.equal(result.tier, "A"); assert.equal(result.policy_version, "miller-location-auto-v1.2.1"); assert.equal(result.failed_hard_gates.length, 0); assert.ok(result.warnings.includes("parcel_point_may_not_be_entrance")) })
test("curated evidence awaits BC validation without becoming public", () => { const result = evaluateAutomaticLocation({ ...base, location: { ...base.location, latitude: null, longitude: null }, evidence: { ...base.evidence, bc_result: null } }); assert.equal(result.tier, "B"); assert.ok(result.failed_hard_gates.includes("bc_single_exact_result")) })
test("parent offices, conflicts, hospitals, uncertain suites, shared occupancy and multiple results route to review", () => { for (const evidence of [{ parent_office: true }, { conflicting_address: true }, { large_campus: true }, { submitted_has_unit: true, returned_has_unit: false }, { address_peer_count: 2 }, { multiple_competing_results: true }]) assert.equal(evaluateAutomaticLocation({ ...base, evidence: { ...base.evidence, ...evidence } }).tier, "B") })
test("program-specific independently verified shared services may remain Tier A", () => { assert.equal(evaluateAutomaticLocation({ ...base, evidence: { ...base.evidence, address_peer_count: 3, shared_occupancy_verified: true } }).tier, "A") })
test("sensitive and non-fixed resources never reach Tier A", () => { for (const item of [{ ...base, resource: { ...base.resource, display_name: "Confidential shelter" } }, { ...base, location: { ...base.location, location_type: "virtual" } }, { ...base, humanDecision: "rejected" }]) assert.notEqual(evaluateAutomaticLocation(item).tier, "A") })
test("human decisions always take precedence", () => { for (const humanDecision of ["approved", "rejected", "excluded", "permanent_manual_review"]) assert.notEqual(evaluateAutomaticLocation({ ...base, humanDecision }).tier, "A") })
test("quality-control sampling is deterministic, ten percent with minimum five", () => { const items = Array.from({ length: 100 }, (_, i) => ({ resource_id: String(100 - i) })); assert.deepEqual(selectQualityControlSample(items), selectQualityControlSample(items)); assert.equal(selectQualityControlSample(items).length, 10); assert.equal(selectQualityControlSample(items.slice(0, 20)).length, 5) })
test("front door and rooftop points qualify while routing points remain Tier B", () => { for (const descriptor of ["frontDoorPoint", "rooftopPoint"]) { const result = normalizeBcAddressResult({ ...feature, properties: { ...feature.properties, locationDescriptor: descriptor } }, { street_address: "10 Main St", city: "Vancouver", result_count: 1 }); assert.equal(evaluateAutomaticLocation({ ...base, evidence: { ...base.evidence, bc_result: result } }).tier, "A") } const routing = normalizeBcAddressResult({ ...feature, properties: { ...feature.properties, locationDescriptor: "routingPoint" } }, { street_address: "10 Main St", city: "Vancouver", result_count: 1 }); assert.equal(evaluateAutomaticLocation({ ...base, evidence: { ...base.evidence, bc_result: routing } }).tier, "B") })
test("access points require an explicit non-misleading interpolation decision", () => { const access = normalizeBcAddressResult({ ...feature, properties: { ...feature.properties, locationDescriptor: "accessPoint" } }, { street_address: "10 Main St", city: "Vancouver", result_count: 1 }); assert.equal(evaluateAutomaticLocation({ ...base, evidence: { ...base.evidence, bc_result: access } }).tier, "B"); assert.equal(evaluateAutomaticLocation({ ...base, evidence: { ...base.evidence, bc_result: access, interpolated_access_acceptable: true } }).tier, "A") })
test("broad fallbacks and lower scores fail closed", () => { for (const properties of [{ matchPrecision: "LOCALITY", score: 100 }, { matchPrecision: "CIVIC_NUMBER", score: 99 }]) { const result = normalizeBcAddressResult({ ...feature, properties: { ...feature.properties, ...properties } }, { street_address: "10 Main St", city: "Vancouver", result_count: 1 }); assert.notEqual(evaluateAutomaticLocation({ ...base, evidence: { ...base.evidence, bc_result: result } }).tier, "A") } })
test("unit submissions require recognized unit precision", () => { const location = { ...base.location, street_address: "Unit 2, 10 Main St" }; const civic = normalizeBcAddressResult(feature, { street_address: location.street_address, city: "Vancouver", result_count: 1 }); assert.equal(evaluateAutomaticLocation({ ...base, location, evidence: { ...base.evidence, bc_result: civic, submitted_has_unit: true, returned_has_unit: false } }).tier, "B"); const unit = normalizeBcAddressResult({ ...feature, properties: { ...feature.properties, fullAddress: "UNIT 2 -- 10 Main St, Vancouver, BC", matchPrecision: "UNIT" } }, { street_address: location.street_address, city: "Vancouver", result_count: 1 }); assert.equal(evaluateAutomaticLocation({ ...base, location, evidence: { ...base.evidence, bc_result: unit, submitted_has_unit: true, returned_has_unit: true } }).tier, "A") })
