import test from "node:test"
import assert from "node:assert/strict"
import { evaluateAutomaticLocation, LOCATION_POLICY_VERSION, selectQualityControlSample } from "../server/locationAutomationPolicy.js"
import { normalizeBcAddressResult } from "../server/bcAddressGeocoder.js"

const feature = { geometry: { coordinates: [-123.1, 49.2] }, properties: { fullAddress: "10 Main St, Vancouver, BC", streetName: "Main St", localityName: "Vancouver", provinceCode: "BC", score: 100, precisionPoints: 100, matchPrecision: "CIVIC_NUMBER", locationDescriptor: "accessPoint", siteID: "fixture", faults: [] } }
const bc = normalizeBcAddressResult(feature, { street_address: "10 Main St", city: "Vancouver", result_count: 1 })
const base = { resource: { display_name: "Public clinic", lifecycle_state: "active", editorial_status: "approved" }, location: { location_type: "fixed", street_address: "10 Main St", city: "Vancouver", latitude: 49.2, longitude: -123.1 }, evidence: { source_identity_stable: true, public_fixed_facility: true, program_specific_address: true, public_client_facing: true, bc_result: bc } }

test("Tier A requires every deterministic v1.2 hard gate", () => { const result = evaluateAutomaticLocation(base); assert.equal(result.tier, "A"); assert.equal(result.policy_version, "miller-location-auto-v1.2.0"); assert.equal(result.failed_hard_gates.length, 0) })
test("curated evidence awaits BC validation without becoming public", () => { const result = evaluateAutomaticLocation({ ...base, location: { ...base.location, latitude: null, longitude: null }, evidence: { ...base.evidence, bc_result: null } }); assert.equal(result.tier, "B"); assert.ok(result.failed_hard_gates.includes("bc_single_exact_result")) })
test("parent offices, conflicts, hospitals, uncertain suites, shared occupancy and multiple results route to review", () => { for (const evidence of [{ parent_office: true }, { conflicting_address: true }, { large_campus: true }, { submitted_has_unit: true, returned_has_unit: false }, { address_peer_count: 2 }, { multiple_competing_results: true }]) assert.equal(evaluateAutomaticLocation({ ...base, evidence: { ...base.evidence, ...evidence } }).tier, "B") })
test("program-specific independently verified shared services may remain Tier A", () => { assert.equal(evaluateAutomaticLocation({ ...base, evidence: { ...base.evidence, address_peer_count: 3, shared_occupancy_verified: true } }).tier, "A") })
test("sensitive and non-fixed resources never reach Tier A", () => { for (const item of [{ ...base, resource: { ...base.resource, display_name: "Confidential shelter" } }, { ...base, location: { ...base.location, location_type: "virtual" } }, { ...base, humanDecision: "rejected" }]) assert.notEqual(evaluateAutomaticLocation(item).tier, "A") })
test("human decisions always take precedence", () => { for (const humanDecision of ["approved", "rejected", "excluded", "permanent_manual_review"]) assert.notEqual(evaluateAutomaticLocation({ ...base, humanDecision }).tier, "A") })
test("quality-control sampling is deterministic, ten percent with minimum five", () => { const items = Array.from({ length: 100 }, (_, i) => ({ resource_id: String(100 - i) })); assert.deepEqual(selectQualityControlSample(items), selectQualityControlSample(items)); assert.equal(selectQualityControlSample(items).length, 10); assert.equal(selectQualityControlSample(items.slice(0, 20)).length, 5) })
