import test from "node:test"
import assert from "node:assert/strict"
import { MAP_AUTO_PUBLISH_MODES, assertMapAutoPublishProductionTarget, buildMapAutoPublishContexts, createMachineQcForCandidate, evaluateMapAutoPublishCandidate, selectGeocoderEvidence, selectOccupancyClaim, runMapAutoPublishDryRun } from "../server/mapAutoPublishWorker.js"

const ids = { shelter: "00000000-0000-0000-0000-000000004101", service: "00000000-0000-0000-0000-000000004102", claim: "00000000-0000-0000-0000-000000004201" }
const data = { resources: [{ id: ids.service, display_name: "Community Clinic", lifecycle_state: "active", editorial_status: "approved" }, { id: ids.shelter, display_name: "Example Shelter", lifecycle_state: "active", editorial_status: "approved" }, { id: "hidden", display_name: "Hidden", lifecycle_state: "active", editorial_status: "hidden" }], claims: [{ id: ids.claim, resource_id: ids.shelter, field_name: "location_occupancy", proposed_value: "100 Main Street", status: "observed", last_observed_at: "2026-08-22" }], evidence: [{ claim_id: ids.claim, source_url: "https://example.invalid", source_authority: 95, stale: false }], qc: [{ canonical_resource_id: ids.shelter, version: 2, origin: "machine_initial", review_snapshot: { submitted_address: "100 Main Street", locality: "Surrey", score: 100, location_descriptor: "parcelpoint", sensitivity_flags: [] } }], locations: [{ resource_id: ids.service, public_map: true, review_status: "approved" }] }
test("enumeration prioritizes shelter resources and skips existing public or hidden records", () => { const contexts = buildMapAutoPublishContexts(data); assert.equal(contexts.length, 1); assert.equal(contexts[0].resource.id, ids.shelter); assert.equal(contexts[0].priority, "shelter_housing") })
test("worker binds persisted current QC and occupancy IDs to the dry-run RPC", async () => { const calls = []; const result = await evaluateMapAutoPublishCandidate({ db: { rpc: async (name, args) => { calls.push({ name, args }); return { data: { decision: "auto_publish_eligible", reason_code: "auto_publish_exact_trusted_address" } } } }, item: buildMapAutoPublishContexts(data)[0] }); assert.equal(result.rpc_called, true); assert.deepEqual(calls[0], { name: "dry_run_map_auto_publish_v1", args: { p_resource_id: ids.shelter, p_expected_qc_version: 2, p_occupancy_claim_id: ids.claim } }) })
test("missing QC or occupancy evidence is reported without inventing a policy result", async () => { const item = { ...buildMapAutoPublishContexts(data)[0], qc: null }; const result = await evaluateMapAutoPublishCandidate({ db: { rpc: async () => assert.fail("must not call RPC") }, item }); assert.equal(result.reason_code, "current_machine_qc_required") })
test("classification-only never invokes refresh and repeats deterministically", async () => { let refreshes = 0; const db = { rpc: async () => ({ data: { decision: "auto_publish_eligible", reason_code: "auto_publish_exact_trusted_address" } }) }; const a = await runMapAutoPublishDryRun({ db, data, deterministicRefresh: async () => { refreshes += 1 } }); const b = await runMapAutoPublishDryRun({ db, data }); assert.equal(refreshes, 0); assert.deepEqual(a.reason_counts, b.reason_counts) })
test("deterministic-refresh mode has no publication API and only uses an injected approved refresher", async () => { let refreshed = 0; await evaluateMapAutoPublishCandidate({ db: { rpc: async () => ({ data: { decision: "manual_review", reason_code: "weak_or_invalid_geocode" } }) }, item: buildMapAutoPublishContexts(data)[0], mode: MAP_AUTO_PUBLISH_MODES.DETERMINISTIC_REFRESH_DRY_RUN, deterministicRefresh: async () => { refreshed += 1 } }); assert.equal(refreshed, 1) })
test("production target requires the expected project and explicit dry-run flag", () => { assert.throws(() => assertMapAutoPublishProductionTarget({ supabaseUrl: "http://127.0.0.1:54321", serviceRoleKey: "x", explicitProductionDryRun: true })); assert.throws(() => assertMapAutoPublishProductionTarget({ supabaseUrl: "https://wccagykzugrahwugefqt.supabase.co", serviceRoleKey: "x", explicitProductionDryRun: false })); assert.equal(assertMapAutoPublishProductionTarget({ supabaseUrl: "https://wccagykzugrahwugefqt.supabase.co", serviceRoleKey: "x", explicitProductionDryRun: true }), true) })
test("binding refuses ambiguous occupancy, ignores stale geocoder evidence, and sends identifiers only", async () => { const claims = [{ id: "a", proposed_value: "1 Main", status: "observed" }, { id: "b", proposed_value: "2 Main", status: "observed" }], evidence = new Map([["a", [{ source_url: "https://a.invalid", source_authority: 95, stale: false }]], ["b", [{ source_url: "https://b.invalid", source_authority: 95, stale: false }]]]); assert.equal(selectOccupancyClaim(claims, evidence).claim, null); const geo = selectGeocoderEvidence([{ id: "a" }], new Map([["a", [{ id: "g", source_type: "bc_geocoder", stale: true, extracted_value: { score: 100, standardized_address: "1 Main" } }]]]), "1 Main"); assert.equal(geo, null); const calls = []; const item = { resource: { id: "r" }, occupancyClaim: { id: "claim" }, geocoderEvidence: { id: "geo" }, qc: null }; await createMachineQcForCandidate({ db: { rpc: async (name, args) => { calls.push({ name, args }); return { data: { version: 1 } } } }, item, actorId: "actor" }); assert.deepEqual(calls[0].args, { p_resource_id: "r", p_occupancy_claim_id: "claim", p_geocoder_evidence_id: "geo", p_actor_id: "actor" }) })
