import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs"
import { askMiller, buildMillerRequest, MILLER_CONTRACT_VERSION, MillerApiError, toMillerResourceMatch } from "../src/millerApi.js"
import { validateMillerRequest } from "../server/millerValidation.js"

const noisy = { id: "curated:abc", name: "Clinic", city: "Burnaby", approved: true, fundingType: "public", latitude: 49, longitude: -123, virtual_service: false, public_map: true, verification_status: "verified" }

test("normal Resource Finder request strips UI and geography fields and passes validation", () => { const payload = buildMillerRequest({ mode: "main", query: "detox", city: "All Cities", matches: [noisy] }); assert.deepEqual(Object.keys(payload.matches[0]).sort(), ["approved", "city", "id", "name"]); assert.equal(validateMillerRequest(payload).interface, "main") })
test("map request passes validation without leaking normal discovery controls", () => { const payload = buildMillerRequest({ mode: "map", query: "OAT", matches: [noisy] }); assert.equal(validateMillerRequest(payload).interface, "map"); assert.equal("tavily" in payload, false) })
test("map-only fields are not required in normal mode", () => { assert.doesNotThrow(() => validateMillerRequest({ query: "virtual counselling", interface: "main" })) })
test("numeric, curated, and canonical IDs survive trusted request serialization", () => { for (const id of [30, "curated:abc", "c590181c-3721-58c6-9027-c2af7dc60108"]) assert.equal(toMillerResourceMatch({ id, name: "Resource" }).id, id) })
test("valid shared response contract supports normal results and no-results state", async () => { for (const noResults of [false, true]) { const data = await askMiller(buildMillerRequest({ query: "help" }), { fetchImpl: async () => ({ ok: true, status: 200, json: async () => ({ contractVersion: MILLER_CONTRACT_VERSION, mode: "main", message: noResults ? "No matches" : "Here are options", results: { resourceIds: noResults ? [] : ["curated:abc"], external: [], noResults } }) }) }); assert.equal(data.results.noResults, noResults) } })
test("API failure, malformed response, and timeout are retryable public errors", async () => { await assert.rejects(askMiller(buildMillerRequest({ query: "help" }), { fetchImpl: async () => ({ ok: false, status: 503, json: async () => ({ code: "provider_failure" }) }) }), (error) => error instanceof MillerApiError && error.code === "provider_failure"); await assert.rejects(askMiller(buildMillerRequest({ query: "help" }), { fetchImpl: async () => ({ ok: true, status: 200, json: async () => ({ answer: "old shape" }) }) }), /unexpected response/); await assert.rejects(askMiller(buildMillerRequest({ query: "help" }), { timeoutMs: 1, fetchImpl: (_url, options) => new Promise((_resolve, reject) => options.signal.addEventListener("abort", () => reject(Object.assign(new Error(), { name: "AbortError" })))) }), (error) => error.code === "timeout") })
test("homepage and map share server-side API helper and loading always clears", () => { const app = fs.readFileSync(new URL("../src/App.jsx", import.meta.url), "utf8"), map = fs.readFileSync(new URL("../src/map/ServiceMap.jsx", import.meta.url), "utf8"); assert.match(app, /askMiller\(buildMillerRequest/); assert.match(map, /askMiller\(buildMillerRequest/); assert.match(app, /finally\s*{\s*setIsLoading\(false\)/); assert.doesNotMatch(app, /OPENAI_API_KEY|TAVILY_API_KEY|SUPABASE_SERVICE_ROLE_KEY/) })
