import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs"
import { eligiblePublicLocation, googleDirectionsUrl, googleTransitDirectionsUrl, validateTypedOrigin } from "../src/navigation/navigation.js"
import { geocodeNavigationOrigin, validateOriginText } from "../server/navigationOrigin.js"

const eligible = { id: "42", location_id: "11111111-1111-4111-8111-111111111111", location_type: "fixed", public_map: true, review_status: "approved", verification_status: "verified", latitude: 49.2, longitude: -123.1 }
test("Get there eligibility requires an exact resource identity and authoritative public location", () => { assert.equal(eligiblePublicLocation({ id: 42 }, [eligible]), eligible); for (const change of [{ location_type: "service_area" }, { public_map: false }, { review_status: "pending" }, { verification_status: "geocoded" }, { latitude: null }]) assert.equal(eligiblePublicLocation({ id: 42 }, [{ ...eligible, ...change }]), null); assert.equal(eligiblePublicLocation({ name: "Legacy only" }, [eligible]), null); assert.equal(eligiblePublicLocation({ id: 42, virtual_service: true }, [{ ...eligible, virtual_service: true }]), null) })
test("typed origins are bounded and reject unsafe input", () => { assert.equal(validateTypedOrigin(" Main St & First Ave "), "Main St & First Ave"); assert.equal(validateTypedOrigin("x"), ""); assert.equal(validateTypedOrigin("<script>address</script>"), ""); assert.throws(() => validateOriginText("x")); assert.throws(() => validateOriginText("a\nmalformed address")) })
test("BC origin geocoding normalizes a single safe coordinate without storage", async () => { const fetchImpl = async () => ({ ok: true, status: 200, json: async () => ({ features: [{ geometry: { coordinates: [-123.1, 49.2] }, properties: { fullAddress: "100 Main St, Vancouver, BC", score: 99, precisionPoints: 100, matchPrecision: "civic_number", locationDescriptor: "accessPoint", faults: [] } }] }) }); const result = await geocodeNavigationOrigin("100 Main St, Vancouver", { env: { BC_GEOCODER_ENABLED: "true", BC_GEOCODER_API_KEY: "fixture" }, fetchImpl }); assert.equal(result.ok, true); assert.equal(result.origin.latitude, 49.2); assert.equal(result.origin.provenance.provider, "bc_address_geocoder"); assert.doesNotMatch(JSON.stringify(result), /fixture/) })
test("maps handoff validates parameters and uses documented transit directions URL", () => { const url = new URL(googleTransitDirectionsUrl({ latitude: 49.2, longitude: -123.1 }, { latitude: 49.1, longitude: -123 })); assert.equal(url.origin, "https://www.google.com"); assert.equal(url.searchParams.get("api"), "1"); assert.equal(url.searchParams.get("travelmode"), "transit"); assert.equal(url.searchParams.get("origin"), "49.1,-123"); assert.equal(googleTransitDirectionsUrl({ latitude: 999, longitude: -123 }), ""); assert.equal(googleTransitDirectionsUrl(eligible, { latitude: "bad", longitude: -123 }), "") })
test("external handoffs offer only supported travel modes", () => { for (const mode of ["transit", "walking", "driving", "bicycling"]) assert.equal(new URL(googleDirectionsUrl(eligible, mode)).searchParams.get("travelmode"), mode); assert.equal(googleDirectionsUrl(eligible, "helicopter"), "") })
test("navigation UI requests geolocation only from its explicit action and never persists origins", () => { const source = fs.readFileSync(new URL("../src/navigation/GetTherePanel.jsx", import.meta.url), "utf8"); const handler = source.slice(source.indexOf("function useMyLocation"), source.indexOf("async function geocodeTypedOrigin")); assert.match(handler, /navigator\.geolocation\.getCurrentPosition/); assert.doesNotMatch(source.slice(source.indexOf("useEffect"), source.indexOf("function useMyLocation")), /getCurrentPosition/); assert.doesNotMatch(source, /localStorage|sessionStorage|trackEvent/); assert.match(source, /Location wasn't shared/); assert.match(source, /transit information for this location yet/); assert.match(source, /Live alerts are temporarily unavailable/) })
test("Get there reuses a transient search origin, exposes validated direct-trip facts and clear external choices", () => { const source = fs.readFileSync(new URL("../src/navigation/GetTherePanel.jsx", import.meta.url), "utf8"); assert.match(source, /initialOrigin = null/); assert.match(source, /useState\(initialOrigin\)/); assert.match(source, /loadContext\(initialOrigin\)/); assert.match(source, /directOptions/); assert.match(source, /Board near:/); assert.match(source, /Get off near:/); assert.match(source, /No direct route was found/); assert.match(source, /\["Transit", "transit"\].*\["Walk", "walking"\].*\["Drive", "driving"\].*\["Cycle", "bicycling"\]/) })
test("mobile navigation and result actions stack without tiny controls", () => { const css = fs.readFileSync(new URL("../src/App.css", import.meta.url), "utf8"); assert.match(css, /@media \(max-width: 430px\)[\s\S]*\.resource-links \{ grid-template-columns: 1fr; \}/); assert.match(css, /\.get-there-origin>button[^}]*min-height: 44px/); assert.match(css, /\.get-there-panel[^}]*max-height:/) })
