import test from "node:test"
import assert from "node:assert/strict"
import { coordinateFingerprint, createLocationApplyProposal, validateLocationApplyConfirmation } from "../server/ownerConfirmedLocationApply.js"

const resource = { id: "2739fba4-51d8-5c57-b433-9e31cd99a01d", lifecycle_state: "active", editorial_status: "approved" }
const snapshot = { submitted_address: "323 8th Street, New Westminster, BC", returned_address: "323 Eighth St, New Westminster, BC", locality: "New Westminster", coordinates: { latitude: 49.2078235, longitude: -122.9191564 }, score: 100, location_descriptor: "parcelpoint", program_occupancy_confidence: "supported", sensitivity_flags: [], conflicts: [] }
const qc = { policy_version: "machine_initial_evidence_v1", version: 1, classification_fingerprint: "a".repeat(64), origin: "machine_initial", decision: "manual_review", review_snapshot: snapshot }
const proposal = createLocationApplyProposal({ proposal_id: "farm_last_door_v1", miller_resource_id: resource.id, address_identity: { fingerprint: "b".repeat(64) }, geocoder_evidence_id: "a39cd1b9-7942-4c7e-b5c0-101e4c2e702b", qc, snapshot, source_provenance: { source_url: "https://lastdoor.org", observed_at: "2026-08-29T01:16:41.371Z" } })
const current = { resource, qc, evidence: [{ source_url: "https://lastdoor.org", source_authority: 85, stale: false }], locations: [], address_identity_fingerprint: "b".repeat(64), geocoder_evidence_id: "a39cd1b9-7942-4c7e-b5c0-101e4c2e702b" }
const confirmation=()=>({confirmation_id:"owner_confirmation_1",proposal_fingerprint:proposal.proposal_fingerprint,miller_resource_id:proposal.miller_resource_id,address_identity_fingerprint:proposal.address_identity_fingerprint,geocoder_evidence_id:proposal.geocoder_evidence_id,qc_version:1,qc_fingerprint:qc.classification_fingerprint,coordinate_fingerprint:proposal.coordinate_fingerprint,state:"confirmed",confirmed_at:"2026-08-29T03:00:00.000Z"})
test("machine QC cannot substitute for an owner confirmation",()=>assert.equal(validateLocationApplyConfirmation({proposal,current}).code,"owner_confirmation_required"))
test("confirmation is bound to evidence, QC, identity, and coordinates",()=>{assert.equal(validateLocationApplyConfirmation({proposal,confirmation:confirmation(),current}).allowed,true);assert.equal(validateLocationApplyConfirmation({proposal,confirmation:{...confirmation(),coordinate_fingerprint:coordinateFingerprint({latitude:49.2,longitude:-122.9})},current}).code,"owner_confirmation_stale");assert.equal(validateLocationApplyConfirmation({proposal,confirmation:confirmation(),current:{...current,address_identity_fingerprint:"c".repeat(64)}}).code,"mapping_proposal_stale")})
test("privacy, duplicate, and map boundaries remain separate",()=>{assert.equal(validateLocationApplyConfirmation({proposal,confirmation:confirmation(),current:{...current,locations:[{location_type:"fixed",public_map:true}]}}).code,"mapping_apply_ineligible");assert.equal(validateLocationApplyConfirmation({proposal,confirmation:confirmation(),current}).map_eligibility,"separate_miller_evaluation_required")})
