import test from "node:test"
import assert from "node:assert/strict"
import { buildSearchIntent, extractConservativeSearchIntent, resolveSearchLocation, validateModelSearchIntent } from "../server/searchIntent.js"
import { buildNavigationPacket, deterministicRelevance } from "../src/navigation/searchContext.js"
test("conservative intent separates explicit facts from normalized concepts", () => { const intent = extractConservativeSearchIntent("I need somewhere to talk to someone about fentanyl."); assert.deepEqual(intent.explicit.substances, ["fentanyl"]); assert.deepEqual(intent.normalized.substanceTopics, ["opioids"]); assert.ok(intent.explicit.supportNeeds.includes("counselling")); assert.equal(intent.explicit.locationText, null); assert.equal(intent.explicit.transport.noCar, false) })
test("location and access phrases are extracted without clinical inference", () => { const intent = extractConservativeSearchIntent("I'm near Gateway Station and need somewhere to talk to someone about fentanyl. I don't drive."); assert.equal(intent.explicit.locationText, "Gateway Station"); assert.equal(intent.explicit.transport.noCar, true); assert.equal(intent.explicit.transport.transitRelevant, true); assert.equal(JSON.stringify(intent).includes("disorder"), false) })
test("typographic apostrophes retain explicit no-car intent", () => assert.equal(extractConservativeSearchIntent("I don’t drive.").explicit.transport.noCar, true))
test("explicit practical barriers enter search intent without inference", () => { const barriers = extractConservativeSearchIntent("I don't have ID and I need somewhere wheelchair accessible. I can't pay.").explicit.barriers; assert.deepEqual(barriers, { noId: true, noPhone: false, walkInNeeded: false, wheelchair: true, cannotPay: true }); assert.deepEqual(extractConservativeSearchIntent("I need help").explicit.barriers, { noId: false, noPhone: false, walkInNeeded: false, wheelchair: false, cannotPay: false }) })
test("timing and community are context rather than open-now claims", () => { assert.deepEqual(extractConservativeSearchIntent("I need somewhere tonight.").explicit.timing, ["tonight"]); const intent = extractConservativeSearchIntent("I need counselling in Surrey."); assert.equal(intent.explicit.city, "Surrey"); assert.equal(intent.explicit.locationText, "Surrey"); assert.equal(JSON.stringify(intent).includes("open"), false) })
test("vague help does not invent sensitive facts", () => { const intent = extractConservativeSearchIntent("My friend needs help."); assert.deepEqual(intent.explicit.substances, []); assert.deepEqual(intent.explicit.supportNeeds, []); assert.equal(intent.explicit.locationText, null) })
test("strict model schema rejects malformed and ungrounded sensitive output with safe fallback", () => { assert.equal(validateModelSearchIntent({ substances: ["fentanyl"], diagnosis: "OUD" }, "help with fentanyl"), null); assert.equal(validateModelSearchIntent({ substances: ["alcohol"] }, "help with fentanyl"), null); assert.equal(validateModelSearchIntent({ supportNeeds: ["detox"] }, "help with fentanyl"), null); assert.deepEqual(buildSearchIntent("help with fentanyl", { substances: "fentanyl" }).explicit.substances, ["fentanyl"]) })
test("location resolver preserves community scope and refuses ambiguous arbitrary choices", async () => { const city = await resolveSearchLocation(extractConservativeSearchIntent("counselling in Surrey")); assert.equal(city.status, "community"); assert.equal(city.origin, null); const ambiguous = await resolveSearchLocation(extractConservativeSearchIntent("help near Gateway Station"), { geocode: async () => ({ ok: false }) }); assert.equal(ambiguous.status, "ambiguous"); assert.match(ambiguous.clarification, /Which address or intersection/) })
test("resolved origin and access stay separate from relevance", async () => { const intent = extractConservativeSearchIntent("help near Gateway Station, I use transit"); const locationContext = await resolveSearchLocation(intent, { geocode: async () => ({ ok: true, origin: { latitude: 49.2, longitude: -123.1, label: "Gateway Station", provenance: { provider: "fixture" } } }) }); const map = { id: 42, location_id: "l1", location_type: "fixed", public_map: true, review_status: "approved", verification_status: "verified", latitude: 49.21, longitude: -123.11 }; const packet = buildNavigationPacket({ resource: { id: 42, name: "Clinic" }, publicMapResources: [map], intent, locationContext, relevance: { categories: ["Counselling"], reason: "Matches counselling" } }); assert.equal(packet.origin, locationContext.origin); assert.ok(packet.access.distance.kilometres > 0); assert.equal(packet.access.transitContextAvailable, true); assert.equal("score" in packet, false); assert.match(packet.explanation, /Matches counselling/) })
test("result explanations claim relevance only when trusted resource text supports it", () => { const intent = extractConservativeSearchIntent("I need counselling"); assert.equal(deterministicRelevance({ category: "Counselling" }, intent).reason, "Matches counselling"); assert.equal(deterministicRelevance({ category: "Housing" }, intent).reason, null) })
