import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs"
import { collectCandidateMatches, directoryApprovalState, findConservativeMatches, prepareShelterCandidate } from "../server/shelterDiscovery.js"

const base = { name: "Harbour Shelter", operator: "Example Society", shelter_type: "emergency_shelter", community: "Prince George", source_url: "https://example.org/harbour", website: "https://example.org/harbour", public_address: "10 Main Street", location_disclosure_status: "public", address_intentionally_public: true, confidence: "high" }
test("a valid discovered shelter is normalized with provenance and no geography", () => { const item = prepareShelterCandidate(base); assert.match(item.source_fingerprint, /^[a-f0-9]{64}$/); assert.equal(item.review_status, "pending"); assert.equal(item.geocoding_status, "awaiting_authorized_geocoder"); assert.equal("latitude" in item, false) })
test("confidential and safe-house candidates discard submitted address and cannot be queued for geocoding", () => { const item = prepareShelterCandidate({ ...base, name: "Confidential Youth Safe House", location_disclosure_status: "confidential" }); assert.equal(item.public_address, ""); assert.equal(item.geocoding_status, "not_requested"); assert.equal(item.location_disclosure_status, "confidential") })
test("an intentionally undisclosed location stays distinct from a confidential service", () => { const item = prepareShelterCandidate({ ...base, public_address: "", location_disclosure_status: "undisclosed" }); assert.equal(item.location_disclosure_status, "undisclosed"); assert.equal(item.geocoding_status, "not_requested") })
test("duplicate matching is conservative and surfaces rather than merges", () => { const exact = findConservativeMatches(prepareShelterCandidate(base), [{ id: 7, name: "Harbour Shelter", organization: "Example Society", website: "https://example.org/harbour", city: "Prince George" }]); assert.equal(exact[0].classification, "high_confidence"); const sharedOperator = findConservativeMatches(prepareShelterCandidate(base), [{ id: 8, name: "Different Program", organization: "Example Society", website: "https://example.org/different", city: "Prince George" }]); assert.equal(sharedOperator.some((x) => x.classification === "high_confidence"), false) })
test("a candidate matched through an existing source alias identifies its canonical record", () => { const candidate = prepareShelterCandidate(base); const matches = collectCandidateMatches(candidate, { aliases: [{ resource_id: "11111111-1111-5111-8111-111111111111", source_type: "tavily_resource", source_native_id: "42", source_url: candidate.source_url, source_fingerprint: candidate.source_fingerprint }], registry: [{ id: "11111111-1111-5111-8111-111111111111", display_name: "Harbour Shelter canonical" }] }); assert.equal(matches[0].classification, "confirmed_alias"); assert.equal(matches[0].name, "Harbour Shelter canonical") })
test("likely duplicates already in the candidate queue remain visible", () => { const candidate = prepareShelterCandidate(base); const matches = collectCandidateMatches(candidate, { resources: [{ id: "candidate:9", discovery_candidate_id: 9, name: base.name, organization: base.operator, website: base.website, city: base.community }] }); assert.equal(matches[0].discovery_candidate_id, 9); assert.equal(matches[0].tavily_resource_id, null) })
test("directory approval remains explicitly separate from geocoding and map publication", () => { assert.deepEqual(directoryApprovalState(base), { directory_approved: true, geography_created: false, public_map: false, geocoding_status: "awaiting_authorized_geocoder" }) })
test("invalid candidates produce actionable validation errors", () => { assert.throws(() => prepareShelterCandidate({ name: "X", source_url: "not a URL" }), /name is required/); assert.throws(() => prepareShelterCandidate({ name: "Valid name", source_url: "http://example.org" }), /HTTPS evidence URL/) })
test("schema and protected workflow support save, match, edit, decisions, and ungeocoded approval", () => { const server = fs.readFileSync(new URL("../server.js", import.meta.url), "utf8"), sql = fs.readFileSync(new URL("../supabase/migrations/202608140001_create_shelter_discovery_candidates.sql", import.meta.url), "utf8"), ui = fs.readFileSync(new URL("../src/admin/ShelterCandidateReview.jsx", import.meta.url), "utf8"); assert.match(server, /app\.post\("\/api\/admin\/discovery-candidates", requireAdmin/); assert.match(server, /app\.patch\("\/api\/admin\/discovery-candidates\/:id", requireAdmin/); assert.match(server, /duplicate_review_required/); assert.match(server, /approved_for_directory/); assert.match(server, /Canonical registration failed;[\s\S]*rolled back/); assert.match(server, /Public searches are read-only/); assert.doesNotMatch(server, /Could not store discovered resources/); assert.match(sql, /revoke all[\s\S]*from anon, authenticated/); assert.match(sql, /awaiting_authorized_geocoder/); assert.match(ui, /Approve directory/); assert.match(ui, /No map approval/); assert.match(ui, /No coordinate or map pin was created/) })
test("repeatable imports calculate duplicate and alias matches instead of bypassing review", () => { const script = fs.readFileSync(new URL("../scripts/shelter-candidate-import.mjs", import.meta.url), "utf8"); assert.match(script, /collectCandidateMatches/); assert.doesNotMatch(script, /possible_matches:\s*\[\]/) })
test("211 BC authoritative URLs receive the intended source score instead of the fallback", () => { const server = fs.readFileSync(new URL("../server.js", import.meta.url), "utf8"); assert.match(server, /site\.includes\("bc\.211\.ca"\)/) })
