import { useCallback, useEffect, useMemo, useState } from "react"
import { adminFetch } from "../adminApi.js"

const tabs = [{ id: "E1", label: "Ready for geocoding" }, { id: "E2", label: "Needs address decision" }, { id: "E3", label: "Excluded / insufficient" }]
export default function AddressEvidenceReview() {
  const [inventory, setInventory] = useState({ records: [], counts: {} }), [tab, setTab] = useState("E1"), [selected, setSelected] = useState([]), [status, setStatus] = useState("Loading address evidence…")
  const visible = useMemo(() => inventory.records.filter((item) => item.tier === tab), [inventory, tab])
  const load = useCallback(async () => { const response = await adminFetch("/api/admin/address-evidence"); const body = await response.json().catch(() => ({})); if (!response.ok) return setStatus(body.error || "Address evidence could not be loaded."); setInventory(body); setSelected([]); setStatus(`${body.examined || 0} resources examined. Evidence is not a coordinate or public pin.`) }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  function toggle(id) { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 50 ? [...current, id] : current) }
  async function approveSelected() { const chosen = visible.filter((item) => selected.includes(item.canonical_uuid)); if (!chosen.length || chosen.length > 50) return; if (!window.confirm(`Approve ${chosen.length} public addresses only for a future geocoding batch? No coordinate or pin will be created.\n\n${chosen.map((item) => `${item.resource_name} — ${item.proposed_address}`).join("\n")}`)) return; const response = await adminFetch("/api/admin/address-evidence/bounded-approve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ canonical_uuids: chosen.map((item) => item.canonical_uuid), evidence_version: inventory.version, confirmed_geocoding_only: true }) }); const body = await response.json().catch(() => ({})); if (!response.ok) return setStatus(body.error || "Evidence approval was not saved."); setStatus(`${body.approved_count} approved only for future geocoding; no pins were created.`); await load() }
  return <section className="address-evidence" aria-labelledby="address-evidence-title"><header><p className="eyebrow">Administrator only · evidence, not geography</p><h2 id="address-evidence-title">Address evidence</h2><p role="status">{status}</p></header><div className="review-tabs" role="tablist">{tabs.map((item) => <button key={item.id} role="tab" aria-selected={tab === item.id} onClick={() => { setTab(item.id); setSelected([]) }}>{item.label} ({inventory.counts?.[item.id] || 0})</button>)}</div>{tab === "E1" ? <div className="quick-review-toolbar"><button type="button" onClick={() => setSelected(visible.filter((item) => item.evidence_review_status === "unreviewed").slice(0, 50).map((item) => item.canonical_uuid))}>Select visible E1</button><button type="button" onClick={() => setSelected([])}>Clear selection</button><button type="button" disabled={!selected.length || selected.length > 50} onClick={approveSelected}>Approve {selected.length} for future geocoding</button><span>Maximum 50. This cannot publish a location.</span></div> : null}<div className="evidence-cards">{visible.map((item) => <article key={item.canonical_uuid} className="evidence-card">{tab === "E1" ? <input type="checkbox" aria-label={`Select ${item.resource_name}`} checked={selected.includes(item.canonical_uuid)} disabled={item.evidence_review_status !== "unreviewed"} onChange={() => toggle(item.canonical_uuid)}/> : null}<div><h3>{item.resource_name}</h3><p><strong>Submitted:</strong> {item.submitted_address || "None"}<br/><strong>Proposed:</strong> {item.proposed_address || "None"}</p><p>{item.public_client_facing_rationale}</p>{item.reasons?.length ? <p><strong>Review reason:</strong> {item.reasons.join(", ")}</p> : null}{item.conflicts?.length ? <p><strong>Conflicts:</strong> {item.conflicts.join(", ")}</p> : null}{item.source_url ? <a href={item.source_url} target="_blank" rel="noreferrer">Open source</a> : null}<small>{item.source_title} · retrieved {item.retrieval_date} · {item.evidence_review_status}</small></div></article>)}</div></section>
}
