import { useCallback, useEffect, useRef, useState } from "react"
import L from "leaflet"
import { adminFetch } from "../adminApi.js"

const revisions = [["pilot_eligible", "Looks correct for proposed publication"], ["manual_review", "Require manual review"], ["correct_address", "Correct address"], ["exclude_exact_location", "Exclude exact location"], ["policy_problem", "Report policy problem"], ["defer", "Defer"]]
function MiniMap({ coordinates, name }) { const node = useRef(null), map = useRef(null); useEffect(() => { if (!node.current || map.current || !coordinates) return; map.current = L.map(node.current, { dragging: false, scrollWheelZoom: false }).setView([coordinates.latitude, coordinates.longitude], 16); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>' }).addTo(map.current); L.marker([coordinates.latitude, coordinates.longitude], { title: name }).addTo(map.current); return () => { map.current?.remove(); map.current = null } }, [coordinates, name]); return <div className="automation-mini-map" ref={node} aria-label={`Map preview for ${name}`}/> }
function RecordDetails({ item }) { return <><h3>{item.resource_name}</h3><p><strong>Specific program:</strong> {item.specific_program_name}<br/><strong>Submitted:</strong> {item.submitted_address}<br/><strong>Returned:</strong> {item.returned_address}<br/><strong>BC result:</strong> score {item.score} · {item.precision} · {item.location_descriptor}<br/><strong>Policy:</strong> {item.policy_version} · retrieved {item.retrieved_at ? new Date(item.retrieved_at).toLocaleDateString() : "unknown"}</p><p><strong>Occupancy evidence:</strong> {item.occupancy_evidence_excerpt || item.occupancy_evidence_rationale || "No excerpt recorded."}</p>{item.source_url ? <p><a href={item.source_url} target="_blank" rel="noreferrer">Open occupancy evidence source</a></p> : null}<p><strong>Sensitivity:</strong> {item.sensitivity_flags.length ? item.sensitivity_flags.join(", ") : "None flagged"}<br/><strong>Conflicts:</strong> {item.conflicts.length ? item.conflicts.join(", ") : "None"}<br/><strong>Warnings:</strong> {item.warnings.length ? item.warnings.join(", ") : "None"}</p>{item.shared_address_group ? <p><strong>Shared address:</strong> {item.shared_address_group.resources.map((resource) => resource.resource_name).join("; ")}. Each identity requires independent approval.</p> : null}<p><strong>Parcel-point note:</strong> This point may lie within the parcel and is not necessarily an entrance. Geocoding does not prove program occupancy.</p><p><a href={item.attribution_url} target="_blank" rel="noreferrer">{item.attribution}</a></p><MiniMap coordinates={item.coordinates} name={item.resource_name}/></> }
export default function LocationAutomationReview() {
  const [review, setReview] = useState({ active: [], completed: [], eligible_for_later_pilot: [], shared_address_groups: [], audit: [], sample_count: 0 }), [view, setView] = useState("active"), [status, setStatus] = useState("Loading durable QC review…"), [saving, setSaving] = useState(false)
  const load = useCallback(async () => { const response = await adminFetch("/api/admin/location-qc-review"); const body = await response.json().catch(() => ({})); if (!response.ok) return setStatus(body.error || "QC review is unavailable."); setReview(body); setStatus(`${body.completed.length} of ${body.sample_count} reviewed. Decisions are durable, audited, and non-public.`) }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  const save = async (item, decision) => { setSaving(true); const response = await adminFetch(`/api/admin/location-qc-review/${encodeURIComponent(item.canonical_uuid)}/decision`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision, expected_version: item.review?.version || 0 }) }); const body = await response.json().catch(() => ({})); setSaving(false); if (!response.ok) return setStatus(body.error || "Decision was not saved."); await load() }
  const active = review.active[0]
  return <section className="address-evidence" aria-labelledby="automation-review-title"><header><p className="eyebrow">Administrator only · durable non-public review</p><h2 id="automation-review-title">Phase 1Q quality control</h2><p role="status">{status}</p><p><strong>“Looks correct” means only:</strong> This record may be included in a later, separately confirmed publication pilot.</p></header><div className="review-tabs" role="tablist"><button onClick={() => setView("active")}>Active QC ({review.active.length})</button><button onClick={() => setView("completed")}>Completed history ({review.completed.length})</button><button onClick={() => setView("eligible")}>Later-pilot summary ({review.eligible_for_later_pilot.length})</button><button onClick={() => setView("shared")}>Shared-address groups ({review.shared_address_groups.length})</button></div>{view === "active" ? active ? <article className="evidence-card"><p>Record {review.completed.length + 1} of {review.sample_count}</p><RecordDetails item={active}/><div className="automation-review-actions"><button disabled={saving} onClick={() => save(active, "pilot_eligible")}>Approve-for-pilot and next</button><button disabled={saving} onClick={() => save(active, "manual_review")}>Manual-review and next</button><button disabled={saving} onClick={() => save(active, "defer")}>Defer and next</button></div><small>No location or publication record will be created.</small></article> : <p>The active QC queue is complete. Review the later-pilot summary before Phase 1R.</p> : null}{view === "completed" ? <div className="evidence-cards">{review.completed.map((item) => <article className="evidence-card" key={item.canonical_uuid}><RecordDetails item={item}/><p><strong>Current decision:</strong> {item.review.decision} · version {item.review.version}</p><div className="automation-review-actions">{revisions.map(([decision, label]) => <button disabled={saving} key={decision} onClick={() => save(item, decision)}>{label}</button>)}</div></article>)}<h3>Append-only audit history</h3>{review.audit.map((entry) => <p key={entry.id}>{entry.created_at}: {entry.canonical_uuid} — {entry.previous_decision || "unreviewed"} → {entry.new_decision}</p>)}</div> : null}{view === "eligible" ? <div className="evidence-cards">{review.eligible_for_later_pilot.map((item) => <article className="evidence-card" key={item.canonical_uuid}><RecordDetails item={item}/></article>)}</div> : null}{view === "shared" ? <div className="evidence-cards">{review.shared_address_groups.map((group) => <article className="evidence-card" key={group.normalized_address}><h3>{group.normalized_address}</h3>{group.batch_records.map((item) => <p key={item.canonical_uuid}>{item.resource_name} — independent Tier {item.tier} identity</p>)}<p>One confirmed tenant does not validate another. A future shared marker may list only independently approved services.</p></article>)}</div> : null}</section>
}
