import { useCallback, useEffect, useRef, useState } from "react"
import L from "leaflet"
import { adminFetch } from "../adminApi.js"

const pendingIcon = L.divIcon({ className: "pending-pin-shell", html: '<span class="pending-pin" aria-hidden="true">?</span>', iconSize: [36, 44], iconAnchor: [18, 42] })

export default function PendingLocationReview() {
  const node = useRef(null), map = useRef(null), layer = useRef(null)
  const [items, setItems] = useState([]), [selected, setSelected] = useState(null), [status, setStatus] = useState("Loading pending locations…")
  const load = useCallback(async () => { const response = await adminFetch("/api/admin/pending-locations"); if (!response.ok) return setStatus("Pending locations could not be loaded."); const data = await response.json(); setItems(data.items || []); setSelected((data.items || [])[0] || null); setStatus(`${data.count || 0} pending locations`) }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  useEffect(() => { if (!node.current || map.current) return; map.current = L.map(node.current).setView([49.2, -122.9], 9); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>' }).addTo(map.current); layer.current = L.layerGroup().addTo(map.current); return () => { map.current?.remove(); map.current = null } }, [])
  useEffect(() => { if (!layer.current) return; layer.current.clearLayers(); for (const item of items) { const marker = L.marker([item.latitude, item.longitude], { icon: pendingIcon, keyboard: true, title: `Pending, not public: ${item.resource_name}` }).on("click", () => setSelected(item)).addTo(layer.current); marker.bindTooltip(`Pending: ${item.resource_name}`); marker.getElement()?.setAttribute("aria-label", `Pending, not public: ${item.resource_name}`) } if (items.length) map.current.fitBounds(L.latLngBounds(items.map((x) => [x.latitude, x.longitude])), { padding: [30, 30], maxZoom: 13 }) }, [items])
  useEffect(() => { if (selected) map.current?.panTo([selected.latitude, selected.longitude]) }, [selected])
  async function decide(action) { if (!selected) return; const body = { action }; if (action === "approve" && !window.confirm(`Publish this one location for ${selected.resource_name}? This does not approve any service sharing the address.`)) return; if (action === "approve") body.confirmed = true; if (action === "correct") { const latitude = window.prompt("Correct latitude", selected.latitude); const longitude = window.prompt("Correct longitude", selected.longitude); if (latitude == null || longitude == null) return; body.latitude = Number(latitude); body.longitude = Number(longitude) } setStatus(`Recording ${action}…`); const response = await adminFetch(`/api/admin/pending-locations/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) return setStatus("Decision was not saved."); await load() }
  return <section className="pending-review" aria-labelledby="pending-title"><div className="pending-review-head"><div><p className="eyebrow">Administrator only</p><h2 id="pending-title">Pending locations — not public</h2><p role="status">{status}</p></div><div className="pending-legend"><span className="pending-pin mini">?</span> Pending human review</div></div><div className="pending-review-grid"><div className="pending-map" ref={node} aria-label="Private preview of pending service locations"/><div className="pending-cards">{items.map((item) => <button key={item.id} type="button" className={selected?.id === item.id ? "pending-card selected" : "pending-card"} aria-pressed={selected?.id === item.id} onClick={() => setSelected(item)}><strong>{item.resource_name}</strong><span>{item.original_address_text}</span></button>)}</div>{selected ? <article className="pending-detail"><h3>{selected.resource_name}</h3><dl><dt>Submitted address</dt><dd>{selected.original_address_text}</dd><dt>Normalized query</dt><dd>{selected.normalized_query}</dd><dt>Returned address</dt><dd>{selected.returned_address}</dd><dt>Coordinates</dt><dd>{selected.latitude}, {selected.longitude}</dd><dt>Provider</dt><dd>{selected.geocode_source} · {selected.provider_class}/{selected.provider_type} · confidence {selected.geocode_confidence ?? "not supplied"}</dd><dt>Warnings</dt><dd>{selected.warnings?.length ? selected.warnings.join(", ") : "None recorded"}</dd></dl><div className="pending-actions"><button onClick={() => decide("approve")}>Approve this pin</button><button onClick={() => decide("correct")}>Correct</button><button onClick={() => decide("reject")}>Reject</button><button onClick={() => decide("exclude")}>Exclude</button><button onClick={() => decide("defer")}>Defer</button></div><p>No bulk approval. Each service is reviewed independently, including services sharing an address.</p></article> : null}</div></section>
}
