import { useCallback, useEffect, useState } from "react"
import { adminFetch } from "../adminApi.js"
const readable = (value) => String(value || "unknown").replaceAll("_", " ")
export default function RefreshedLocationReviews() {
  const [items, setItems] = useState([]), [counts, setCounts] = useState({ ready_to_publish: 0, one_confirmation_away: 0, blocked: 0 }), [status, setStatus] = useState("Loading refreshed location reviews…"), [saving, setSaving] = useState("")
  const load = useCallback(async () => { const response = await adminFetch("/api/admin/refreshed-location-reviews"), body = await response.json().catch(() => ({})); if (!response.ok) return setStatus(body.error || "Refreshed reviews are unavailable."); setItems(body.items || []); setCounts(body.queue_counts || {}); setStatus(`${body.queue_counts?.ready_to_publish || 0} ready to publish · ${body.queue_counts?.one_confirmation_away || 0} one confirmation away · ${body.queue_counts?.blocked || 0} blocked.`) }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  async function confirm(item) { if (saving || !window.confirm(`Confirm refreshed evidence for ${item.resource_name}? This does not create or publish a location.`)) return; setSaving(item.canonical_uuid); setStatus("Saving human QC confirmation…"); try { const response = await adminFetch(`/api/admin/refreshed-location-reviews/${item.canonical_uuid}/confirm`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expected_version: item.qc.version }) }); const body = await response.json().catch(() => ({})); setStatus(response.ok ? body.message : body.error || "Confirmation was not saved."); if (response.ok) await load() } catch { setStatus("Confirmation could not reach the server. Reload and try again.") } finally { setSaving("") } }
  async function publish(item) { if (saving || !window.confirm(`Publish this verified service location on Miller's public map?\n\n${item.resource_name}\n${item.address || "Verified address"}\n${item.community || "Community unavailable"}`)) return; setSaving(item.canonical_uuid); setStatus("Publishing…"); try { const response = await adminFetch(`/api/admin/verified-map-pins/${item.canonical_uuid}/publish`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expected_qc_version: item.qc.version, confirmed_publication: true }) }); const body = await response.json().catch(() => ({})); setStatus(response.ok ? (body.already_published ? "This verified location is already on Miller's public map." : "Published on Miller's public map.") : body.error || "Publication was not completed."); if (response.ok) await load() } catch { setStatus("Publication could not reach the server. Reload and try again.") } finally { setSaving("") } }
  const card = (item) => <article className="evidence-card" key={item.canonical_uuid}><h3>{item.resource_name}</h3><dl><dt>Public address</dt><dd>{item.address || "Missing"}</dd><dt>Community</dt><dd>{item.community || "Missing"}</dd><dt>BC geocoder</dt><dd>{item.geocoder.score ? `${item.geocoder.score} · ${item.geocoder.precision} · ${item.geocoder.descriptor}` : "Incomplete"}</dd><dt>Occupancy</dt><dd>{readable(item.occupancy)} · {item.evidence_sources} current source(s)</dd><dt>QC</dt><dd>{readable(item.qc.decision)} · version {item.qc.version}</dd><dt>Blockers</dt><dd>{item.blockers.map(readable).join(", ") || "None"}</dd></dl>{item.queue_state === "one_confirmation_away" ? <button disabled={Boolean(saving)} onClick={() => confirm(item)}>{saving === item.canonical_uuid ? "Saving…" : "Confirm location evidence"}</button> : null}{item.queue_state === "ready_to_publish" ? <button disabled={Boolean(saving)} onClick={() => publish(item)}>{saving === item.canonical_uuid ? "Publishing…" : "Publish verified map pin"}</button> : null}</article>
  return <section className="address-evidence"><header><p className="eyebrow">Administrator only · current evidence</p><h2>Location publication</h2><p role="status">{status}</p></header><h3>Ready to publish ({counts.ready_to_publish || 0})</h3>{items.filter((item) => item.queue_state === "ready_to_publish").map(card)}<h3>One confirmation away ({counts.one_confirmation_away || 0})</h3>{items.filter((item) => item.queue_state === "one_confirmation_away").map(card)}<h3>Blocked ({counts.blocked || 0})</h3>{items.filter((item) => item.queue_state === "blocked").map(card)}</section>
}
