import { createHash } from "node:crypto"

export const SENSOR_CADENCE = Object.freeze({ service_announcements: "daily", drug_safety: "daily", scientific_literature: "weekly", toxic_drug_alerts: "fast", epidemiology: "monthly", cultural: "monthly" })
export const FREE_SENSOR_ADAPTERS = Object.freeze([
  { id: "trusted_service_announcements", family: "services", cadence: SENSOR_CADENCE.service_announcements, entrypoints: ["bc-government-substance-use", "fraser-health-substance-use", "vch-substance-use"], live: "existing_fixed_trend_sensor" },
  { id: "health_canada_drug_safety", family: "pharmacology", cadence: SENSOR_CADENCE.drug_safety, host: "recalls-rappels.canada.ca", entrypoint: "https://recalls-rappels.canada.ca/en/alert-recall", live: "fixture_parser_pending_authoritative_feed_validation" },
  { id: "pubmed_addiction_literature", family: "scientific", cadence: SENSOR_CADENCE.scientific_literature, host: "eutils.ncbi.nlm.nih.gov", fixed_topics: ["opioid use disorder", "opioid agonist treatment", "buprenorphine", "methadone", "withdrawal management", "harm reduction"], live: "metadata_only_fixture_parser" },
  { id: "bc_toxic_drug", family: "toxic_drug", cadence: SENSOR_CADENCE.toxic_drug_alerts, host: "www.bccdc.ca", live: "fixture_parser_pending_stable_machine_readable_source" },
  { id: "bc_epidemiology", family: "toxic_drug", cadence: SENSOR_CADENCE.epidemiology, host: "www2.gov.bc.ca", live: "fixture_parser_pending_release_validation" },
  { id: "cultural_context", family: "cultural", cadence: SENSOR_CADENCE.cultural, live: "schema_and_fixture_only" },
])
export const ATTENTION_LIMITS = Object.freeze({ maxScore: 100, maxSignalContribution: 35, maxEventContribution: 35, maxConvergenceBonus: 24, maxQuestionsPerTopic: 2 })
const norm = (value) => String(value || "").toLowerCase().trim().replace(/[^a-z0-9:_|-]+/g, "_").replace(/^_+|_+$/g, "")
const n = (value) => Math.max(0, Math.min(1, Number(value) || 0))
const hash = (parts) => createHash("sha256").update(parts.map((item) => String(item || "").trim().toLowerCase()).join("|"), "utf8").digest("hex")
export function attentionTopicKey({ topic_type = "service_system", geographic_scope = "", service_scope = "", canonical_resource_id = "", subject = "" } = {}) { const subjectKey = canonical_resource_id ? `resource:${canonical_resource_id}` : `${norm(topic_type)}:${norm(subject || geographic_scope || service_scope)}`; return subjectKey.slice(0, 240) }
export function attentionSignalFingerprint(signal = {}) { return hash([signal.topic_key, signal.signal_type, signal.source_id, signal.underlying_event_key, signal.effective_at || signal.observed_at || ""]) }
const ageDays = (at, now) => Math.max(0, (new Date(now).getTime() - new Date(at).getTime()) / 86_400_000)
const halfLife = { fast: 7, medium: 35, slow: 180 }
export function decayFactor(signal, now = new Date().toISOString()) { return Math.pow(0.5, ageDays(signal.effective_at || signal.observed_at, now) / (halfLife[signal.decay_class] || halfLife.medium)) }
const evidenceWeight = { single_study: 0.35, observational_study: 0.35, randomized_trial: 0.55, systematic_review: 0.8, guideline: 0.9, regulator_safety_action: 1, replication: 0.7 }
export function signalContribution(signal, now) { const scientific = signal.signal_type === "scientific_evidence" ? (evidenceWeight[signal.provenance?.evidence_class] || 0.3) : 1; const raw = (Number(signal.source_authority || 0) / 100) * n(signal.magnitude) * n(signal.novelty) * n(signal.relevance) * n(signal.confidence) * 40 * scientific * decayFactor(signal, now); return Math.min(ATTENTION_LIMITS.maxSignalContribution, raw) }
export function attentionState({ score, signals = [], status = "active" }) { if (["resolved", "suppressed"].includes(status) && score < 20) return "background"; const urgent = signals.some((signal) => signal.reflex_eligible && Number(signal.source_authority) >= 85 && decayFactor(signal) > 0.65); if (urgent && score >= 20) return "urgent_review"; if (score >= 45) return "focus"; if (score >= 15) return "watch"; return "background" }
export function recalculateTopic(topic, signals = [], now = new Date().toISOString()) {
  const active = signals.filter((signal) => decayFactor(signal, now) > 0.02)
  const eventBest = new Map(); for (const signal of active) { const key = signal.underlying_event_key || signal.signal_fingerprint; const contribution = signalContribution(signal, now); if (!eventBest.has(key) || eventBest.get(key).contribution < contribution) eventBest.set(key, { signal, contribution }) }
  const unique = [...eventBest.values()], families = new Set(unique.map(({ signal }) => signal.signal_family)), base = unique.reduce((sum, item) => sum + item.contribution, 0), convergence = Math.min(ATTENTION_LIMITS.maxConvergenceBonus, Math.max(0, families.size - 1) * 8), resolvedFactor = ["resolved", "suppressed"].includes(topic.status) ? 0.25 : 1, highAuthority = unique.some(({ signal }) => Number(signal.source_authority) >= 70), rawScore = Math.min(ATTENTION_LIMITS.maxScore, Math.round((base + convergence) * resolvedFactor * 100) / 100), score = highAuthority ? rawScore : Math.min(44, rawScore), state = attentionState({ score, signals: unique.map((item) => item.signal), status: topic.status })
  return { ...topic, current_score: score, state, trend: score > Number(topic.current_score || 0) + 2 ? "rising" : score < Number(topic.current_score || 0) - 2 ? "falling" : "stable", contributing_families: [...families].sort(), reason_codes: [...new Set(unique.flatMap(({ signal }) => signal.reason_codes || []))].slice(0, 8), signal_count: active.length, unique_event_count: unique.length, last_recalculated_at: now }
}
export function signalToTopic(signal) { const topic_key = attentionTopicKey(signal); return { topic_key, topic_type: signal.topic_type || "service_system", title: String(signal.title || signal.subject || "Service-system attention").slice(0, 240), geographic_scope: signal.geographic_scope || null, service_scope: signal.service_scope || null, canonical_resource_id: signal.canonical_resource_id || null } }
export function attentionCuriosityQuestions(topics = []) { return topics.filter((topic) => ["focus", "urgent_review"].includes(topic.state) && topic.status === "active" && !topic.protected).sort((a, b) => b.current_score - a.current_score || a.topic_key.localeCompare(b.topic_key)).slice(0, ATTENTION_LIMITS.maxQuestionsPerTopic * 5).map((topic) => ({ question_id: `attention:${topic.topic_key}`, topic_key: topic.topic_key, expected_value: topic.current_score, answerability: "bounded", safety_risk: "low", requires_human_authorization: true, proposed_investigation: topic.canonical_resource_id ? "maintenance" : "growth_or_human_review", reason_codes: topic.reason_codes || [], question: topic.canonical_resource_id ? `Does this resource require a current factual review?` : `Does this attended topic justify a bounded evidence review?` })) }
export function trendObservationSignal(observation = {}) { const category = observation.trend_category || "other_relevant_change", urgent = ["service_closure", "service_relocation"].includes(category) && Boolean(observation.canonical_resource_id); const topic = signalToTopic({ topic_type: observation.canonical_resource_id ? "resource" : category === "policy_change" ? "policy" : "service_system", canonical_resource_id: observation.canonical_resource_id, subject: observation.canonical_resource_id || observation.geographic_scope || "bc_service_system", title: observation.canonical_resource_id ? "Resource change needs review" : observation.geographic_scope || "BC service system", geographic_scope: observation.geographic_scope, service_scope: category })
  return { ...topic, signal_type: category === "policy_change" ? "policy_change" : "service_change", signal_family: "services", source_id: observation.provenance?.source_id || "trusted_service_announcements", source_authority: observation.source_authority, magnitude: urgent ? 0.9 : 0.55, novelty: 0.7, relevance: 0.8, confidence: Math.min(1, Number(observation.source_authority || 0) / 100), observed_at: observation.retrieved_at || new Date().toISOString(), effective_at: observation.publication_date || null, decay_class: urgent ? "medium" : "medium", reflex_eligible: urgent, underlying_event_key: observation.observation_fingerprint || hash([observation.source_url, category, observation.publication_date]), reason_codes: [category, "trend_observation"], provenance: { trend_observation_id: observation.id || null, content_role: "untrusted_observation" } }
}
