const bounded = (value, limit = 2000) => JSON.stringify(value || []).length <= limit ? value || [] : []
export function createAutomationSchedulerStore(supabase) {
  return {
    async recent() { const result = await supabase.from("miller_automation_scheduler_runs").select("*").order("started_at", { ascending: false }).limit(2); if (result.error) throw result.error; return result.data || [] },
    async acquire({ leaseMs, startedAt }) { const expires = new Date(new Date(startedAt).getTime() + leaseMs).toISOString(), active = await supabase.from("miller_automation_scheduler_runs").select("*").eq("status", "running").gt("lease_expires_at", startedAt).limit(1).maybeSingle(); if (active.error) throw active.error; if (active.data) return { already_running: true, run: active.data }; const recovered = await supabase.from("miller_automation_scheduler_runs").update({ status: "failed", failure_code: "stale_lease_recovered", completed_at: startedAt }).eq("status", "running").lte("lease_expires_at", startedAt); if (recovered.error) throw recovered.error; const created = await supabase.from("miller_automation_scheduler_runs").insert({ status: "running", started_at: startedAt, lease_expires_at: expires }).select().single(); if (created.error) { if (created.error.code === "23505") return { already_running: true, run: null }; throw created.error } return { already_running: false, run: created.data } },
    async finish(run, values) { const result = await supabase.from("miller_automation_scheduler_runs").update({ ...values, due_capabilities: bounded(values.due_capabilities), started_capabilities: bounded(values.started_capabilities), completed_at: new Date().toISOString(), lease_expires_at: new Date().toISOString() }).eq("id", run.id).eq("status", "running").select().single(); if (result.error) throw result.error; return result.data },
    async fail(run, values) { const result = await supabase.from("miller_automation_scheduler_runs").update({ status: "failed", failure_code: values.failure_code, completed_at: new Date().toISOString(), lease_expires_at: new Date().toISOString() }).eq("id", run.id).eq("status", "running").select().single(); if (result.error) throw result.error; return result.data },
  }
}
