import { randomUUID } from "node:crypto"
import { mkdirSync } from "node:fs"
import { dirname } from "node:path"
import { DatabaseSync } from "node:sqlite"
import { confirmPublicationAction } from "./chatPublicationAction.js"

const STATES=new Set(["pending","confirmed","applied","expired","rejected"])
const clean=(v,n=160)=>typeof v==="string"?v.replace(/\s+/g," ").trim().slice(0,n):""
export function createChatPublicationConveyor({databasePath,now=()=>Date.now(),loadCurrent,publish}={}){
 if(!databasePath||typeof loadCurrent!=="function"||typeof publish!=="function")throw new Error("chat_publication_conveyor_dependencies_required")
 const open=()=>{mkdirSync(dirname(databasePath),{recursive:true,mode:0o700});const db=new DatabaseSync(databasePath);db.exec("create table if not exists chat_publication_actions(action_id text primary key,action_json text not null,status text not null,created_at text not null,expires_at text not null,confirmed_at text,applied_at text,outcome text);create table if not exists chat_publication_action_audit(id text primary key,action_id text not null,event text not null,created_at text not null)");return db}
 const audit=(db,id,event)=>db.prepare("insert into chat_publication_action_audit values(?,?,?,?)").run(`chat_publication_audit_${randomUUID()}`,id,event,new Date(now()).toISOString())
 const row=r=>r&&({...JSON.parse(r.action_json),status:r.status,created_at:r.created_at,expires_at:r.expires_at,confirmed_at:r.confirmed_at||null,applied_at:r.applied_at||null,outcome:r.outcome||null})
 const summary=a=>({prepared_action_id:a.action_id,resource_name:clean(a.resource_name,240),address:clean(a.address,300),map_state:"Not published",evidence_summary:"Exact civic evidence and current Miller QC verified.",expires_at:a.expires_at,recommended_action:"Publish verified map pin"})
 const prepare=input=>{if(input?.action!=="publish_verified_map_pin"||!clean(input.action_id)||!clean(input.resource_name)||!clean(input.address)||!clean(input.expires_at))throw new Error("chat_publication_prepare_invalid");const db=open();try{const existing=row(db.prepare("select * from chat_publication_actions where action_id=?").get(input.action_id));if(existing)return existing;const created=new Date(now()).toISOString(),record={...input,created_at:created};db.prepare("insert into chat_publication_actions values(?,?,?,?,?,?,?,?)").run(record.action_id,JSON.stringify(record),"pending",created,record.expires_at,null,null,null);audit(db,record.action_id,"prepared");return {...record,status:"pending"}}finally{db.close()}}
 const list=()=>{const db=open();try{return db.prepare("select * from chat_publication_actions where status='pending' order by created_at asc limit 20").all().map(row).map(a=>Date.parse(a.expires_at)<=now()?null:summary(a)).filter(Boolean)}finally{db.close()}}
 const confirm=async({prepared_action_id,owner_confirmed}={})=>{if(!owner_confirmed||!/^publish_[0-9a-f-]{36}$/i.test(clean(prepared_action_id)))return{outcome:"rejected",code:"chat_publication_confirmation_invalid"};const db=open();let action;try{action=row(db.prepare("select * from chat_publication_actions where action_id=?").get(prepared_action_id));if(!action)return{outcome:"rejected",code:"chat_publication_unknown_action"};if(action.status==="applied")return{outcome:"already_published",idempotent:true};if(action.status!=="pending")return{outcome:"rejected",code:"chat_publication_consumed"};if(Date.parse(action.expires_at)<=now()){db.prepare("update chat_publication_actions set status='expired',outcome='expired' where action_id=?").run(action.action_id);audit(db,action.action_id,"expired");return{outcome:"expired"}}const current=await loadCurrent(action);const checked=confirmPublicationAction({action,confirmedActionId:action.action_id,now:now(),current});if(!checked.allowed){db.prepare("update chat_publication_actions set status='rejected',outcome=? where action_id=?").run(checked.code,action.action_id);audit(db,action.action_id,"rejected");return{outcome:"rejected",code:checked.code}}db.prepare("update chat_publication_actions set status='confirmed',confirmed_at=? where action_id=?").run(new Date(now()).toISOString(),action.action_id);audit(db,action.action_id,"confirmed")}finally{db.close()}const result=await publish(action);const done=open();try{const outcome=result?.outcome==="already_published"?"already_published":"published";done.prepare("update chat_publication_actions set status='applied',applied_at=?,outcome=? where action_id=?").run(new Date(now()).toISOString(),outcome,action.action_id);audit(done,action.action_id,"applied");return{outcome,idempotent:outcome==="already_published"}}finally{done.close()}}
 return{prepare,list,confirm}
}
