const DAY = 24 * 60 * 60 * 1000
const active = (item) => !["resolved", "false_positive", "expected_behavior"].includes(item.lifecycle)
const readable = (value) => String(value || "unknown").replaceAll("_", " ")
const safe = (value, max = 220) => String(value || "").replace(/[\r\n\t]/g, " ").replace(/[^a-z0-9 .,:;()/'-]/gi, "").slice(0, max)
const priority = { critical: 1, high: 1, degraded: 2, failed: 2, attention: 3, unknown: 4, medium: 4, low: 6, informational: 7 }
const ago = (value, now) => value && now - new Date(value).getTime() <= DAY

export function buildControlRoomSummary({ securityFindings = [], pulse = null, incidents = [], deployment = null, maintenance = [], healthSignals = [], resourceReviewCount = 0, shelterReviewCount = 0, locationReviewCount = 0, attachmentBacklog = 0, siteEvents = 0, now = Date.now() } = {}) {
  const important = []
  for (const finding of securityFindings.filter(active)) if (["critical", "high"].includes(finding.severity)) important.push({ id: `security:${finding.finding_fingerprint}`, domain: "security", severity: finding.severity, title: "Security needs review", detail: safe(finding.finding_type || "A security check found something that needs review."), action: "Open Security Room", href: "#security-room-title" })
  for (const incident of incidents.filter((item) => item.state === "active" && ["critical", "high"].includes(item.severity)).slice(0, 2)) important.push({ id: `incident:${incident.correlation_key}`, domain: "security", severity: incident.severity, title: "Security signals agree on a concern", detail: `Related ${readable(incident.category)} evidence needs review. This is an observation, not a claim about cause.`, action: "Open Security Room", href: "#security-room-title", context: { type: "security" } })
  if (deployment?.alignment_state && deployment.alignment_state !== "aligned") important.push({ id: "deployment", domain: "deployment", severity: deployment.alignment_state === "migration_gap" ? "high" : "attention", title: "Deployment status is unknown", detail: deployment.alignment_state === "build_unknown" || deployment.alignment_state === "schema_unknown" ? "Miller cannot yet verify which application build and database schema are running together." : `Build and database alignment is ${readable(deployment.alignment_state)}.`, action: "Explain deployment status", href: "#security-room-title", context: { type: "deployment" } })
  if (pulse?.status === "failed") important.push({ id: "pulse-failed", domain: "security", severity: "degraded", title: "Security Pulse did not complete", detail: "The last bounded security check failed safely. No settings were changed.", action: "Open Security Room", href: "#security-room-title" })
  if (Number(attachmentBacklog) > 0) important.push({ id: "attachments", domain: "operations", severity: "attention", title: "Attachments are waiting for scan decisions", detail: `${attachmentBacklog} quarantined attachment${attachmentBacklog === 1 ? " is" : "s are"} not available to anyone.`, action: "Open details", href: "#system-health-title" })
  const needs_you = [
    resourceReviewCount ? { id: "resources", domain: "resources", count: resourceReviewCount, title: "Resource reviews", detail: `${resourceReviewCount} resource decision${resourceReviewCount === 1 ? " is" : "s are"} waiting.`, href: "#admin-review-queue" } : null,
    shelterReviewCount ? { id: "shelters", domain: "shelters", count: shelterReviewCount, title: "Shelter reviews", detail: `${shelterReviewCount} shelter decision${shelterReviewCount === 1 ? " is" : "s are"} waiting.`, href: "#shelter-throughput-title" } : null,
    locationReviewCount ? { id: "locations", domain: "locations", count: locationReviewCount, title: "Location evidence reviews", detail: `${locationReviewCount} location evidence decision${locationReviewCount === 1 ? " is" : "s are"} waiting.`, href: "#refreshed-location-reviews-title" } : null,
  ].filter(Boolean)
  const handled = [
    pulse?.status === "completed" ? { id: "pulse", domain: "security", at: pulse.completed_at, text: "Security Pulse completed. It only observed the configured checks; it did not change settings." } : null,
    maintenance.find((item) => item.status === "completed") ? { id: "maintenance", domain: "operations", at: maintenance.find((item) => item.status === "completed").completed_at || maintenance.find((item) => item.status === "completed").started_at, text: "A maintenance cycle completed with its recorded verification." } : null,
  ].filter(Boolean)
  const timeline = [
    ...handled.map((item) => ({ ...item, kind: item.domain })),
    ...healthSignals.filter((item) => ago(item.finished_at || item.started_at, now)).slice(0, 3).map((item) => ({ id: `health:${item.id || item.inspection_id}`, domain: "sensors", at: item.finished_at || item.started_at, text: item.outcome?.includes("new") ? "An official health-information source recorded a new relevant observation." : "An official health-information source was checked." })),
    ...important.slice(0, 3).map((item) => ({ id: item.id, domain: item.domain, at: deployment?.observed_at || pulse?.completed_at || null, text: item.title })),
  ].sort((a, b) => String(b.at || "").localeCompare(String(a.at || ""))).slice(0, 8)
  const changes = [
    securityFindings.filter((item) => item.lifecycle === "new").length ? { domain: "security", text: `${securityFindings.filter((item) => item.lifecycle === "new").length} new security finding${securityFindings.filter((item) => item.lifecycle === "new").length === 1 ? "" : "s"}.` } : null,
    resourceReviewCount ? { domain: "resources", text: `${resourceReviewCount} resource review${resourceReviewCount === 1 ? " is" : "s are"} waiting.` } : null,
    healthSignals.filter((item) => ago(item.finished_at || item.started_at, now)).length ? { domain: "sensors", text: `${healthSignals.filter((item) => ago(item.finished_at || item.started_at, now)).length} recent official source check${healthSignals.filter((item) => ago(item.finished_at || item.started_at, now)).length === 1 ? "" : "s"}.` } : null,
    siteEvents ? { domain: "operations", text: `${siteEvents} privacy-safe public activity event${siteEvents === 1 ? "" : "s"} recorded recently.` } : null,
  ].filter(Boolean).slice(0, 6)
  const posture = important.some((item) => priority[item.severity] <= 2) ? "degraded" : important.length || needs_you.length ? "attention" : deployment?.alignment_state && deployment.alignment_state !== "aligned" ? "unknown" : "healthy"
  const bubble = posture === "healthy" ? "Everything important looks normal. I do not see an urgent issue right now." : posture === "unknown" ? "I cannot yet verify the deployed build and database state. I am showing that uncertainty rather than guessing." : posture === "degraded" ? "Something important needs your attention. I have kept the details and next safe step close by." : `Most things are steady, but ${important.length + needs_you.length} item${important.length + needs_you.length === 1 ? " needs" : "s need"} your attention.`
  return { generated_at: new Date(now).toISOString(), posture, bubble, important: important.sort((a, b) => priority[a.severity] - priority[b.severity]).slice(0, 6), needs_you, handled, changes, timeline, subsystems: [{ id: "security", label: "Security", state: securityFindings.filter(active).length ? "attention" : "healthy", detail: `${securityFindings.filter(active).length} active finding(s)` }, { id: "deployment", label: "Deployment", state: deployment?.alignment_state || "unknown", detail: deployment?.build_identity ? "Build identity is available." : "Running build is not yet verified." }, { id: "resources", label: "Resources", state: resourceReviewCount ? "review_needed" : "quiet", detail: `${resourceReviewCount} review item(s)` }, { id: "shelters", label: "Shelters", state: shelterReviewCount ? "review_needed" : "quiet", detail: `${shelterReviewCount} review item(s)` }, { id: "locations", label: "Locations", state: locationReviewCount ? "review_needed" : "quiet", detail: `${locationReviewCount} evidence review(s)` }, { id: "sensors", label: "Information sensors", state: healthSignals.length ? "current" : "unknown", detail: healthSignals.length ? `${healthSignals.length} recent source observation(s)` : "No recent source observation." }, { id: "operations", label: "Operations", state: maintenance.some((item) => item.status === "failed") ? "attention" : "steady", detail: "Scheduling remains off unless you explicitly enable it." }] }
}

export function answerControlRoomQuestion({ question = "", summary = {}, selectedContext = null } = {}) {
  const text = String(question).toLowerCase().trim()
  if (selectedContext?.type === "deployment" && (!text || /explain|this|why|danger/.test(text))) return { text: "Miller cannot currently prove which Render build is running with which database schema. Nothing was changed automatically. Before a production update, verify the deployed build, service health, and migration compatibility.", details: { context: "deployment", posture: summary.posture } }
  if (/what.*(wrong|attention|look)|urgent/.test(text)) return { text: summary.important?.length ? summary.important.map((item) => item.detail).join(" ") : "No urgent issue is currently recorded. I will still show any decisions waiting for you.", details: summary.important || [] }
  if (/what.*(changed|new|today|recent)/.test(text)) return { text: summary.changes?.length ? summary.changes.map((item) => item.text).join(" ") : "No meaningful recent change is recorded in this bounded summary.", details: summary.changes || [] }
  if (/render|deploy|schema|build/.test(text)) return { text: summary.subsystems?.find((item) => item.id === "deployment")?.detail || "Deployment state is unknown.", details: summary.subsystems?.find((item) => item.id === "deployment") || {} }
  if (/security|pulse/.test(text)) return { text: summary.subsystems?.find((item) => item.id === "security")?.detail || "Security status is unknown.", details: summary.subsystems?.find((item) => item.id === "security") || {} }
  return { text: summary.bubble || "I do not have enough current information to summarize this safely.", details: { posture: summary.posture || "unknown" } }
}
