import { createHash } from "node:crypto"
import { HUMAN_NEEDS, humanNeedBand } from "./humanNeedsSense.js"

export const COVERAGE_HYPOTHESES = Object.freeze({ maximum_active: 15, ttl_days: 30, schema_version: "coverage-hypothesis-v1" })
const aliases = { withdrawal_management:["detox","withdrawal"], opioid_agonist_treatment:["opioid agonist","methadone","oat"], counselling:["counselling","mental health"], shelter:["shelter","housing"], housing_support:["housing"], overdose_prevention:["harm reduction","overdose"], transportation:["transport","transit"], hours_availability:["hours","evening","weekend"] }
const norm = (value) => String(value || "").toLowerCase()
export function coverageHypothesisKey(bucket) { return createHash("sha256").update([COVERAGE_HYPOTHESES.schema_version,bucket.kind,bucket.theme,bucket.geography].join("|")).digest("hex") }
export function inspectCoverage(bucket, resources = []) { const terms = aliases[bucket.theme] || [bucket.theme.replaceAll("_"," ")], relevant = resources.filter((resource) => terms.some((term) => `${norm(resource.category)} ${norm(resource.service_type)} ${norm(resource.description)} ${norm(resource.city)}`.includes(term))), geographyRelevant = bucket.geography === "province" ? relevant : relevant.filter((resource) => norm(resource.city).includes(bucket.geography.replaceAll("_"," "))); const count = geographyRelevant.length || relevant.length, uncertainty = count === 0 ? "directory_coverage_unknown" : bucket.kind === "barrier" ? "navigation_or_access_detail_unknown" : count < 3 ? "limited_directory_representation" : "coverage_present_discoverability_unknown"; return { matching_resource_count: count, uncertainty_reason: uncertainty, coverage_state: count === 0 ? "unknown" : count < 3 ? "limited" : "represented" } }
export function buildCoverageHypothesis(bucket, resources = [], now = new Date().toISOString()) { if (Number(bucket.observation_count) < HUMAN_NEEDS.threshold) return null; const coverage = inspectCoverage(bucket, resources), key = coverageHypothesisKey(bucket), expires_at = new Date(new Date(now).getTime() + COVERAGE_HYPOTHESES.ttl_days * 86_400_000).toISOString(), needsEvidence = coverage.coverage_state !== "represented", question = needsEvidence ? `Does Miller have enough current, discoverable ${bucket.theme.replaceAll("_"," ")} information for ${bucket.geography.replaceAll("_"," ")}?` : `Are ${bucket.theme.replaceAll("_"," ")} resources discoverable and represented clearly for ${bucket.geography.replaceAll("_"," ")}?`; return { hypothesis_key:key, kind:bucket.kind, theme:bucket.theme, geography:bucket.geography, strength_band:humanNeedBand(bucket.observation_count), coverage_state:coverage.coverage_state, uncertainty_reason:coverage.uncertainty_reason, matching_resource_count:coverage.matching_resource_count, status: needsEvidence ? "awaiting_evidence" : "evidence_available", research_question:question, reason_codes:["aggregate_human_need","privacy_threshold_satisfied",coverage.uncertainty_reason], expires_at, provenance:{ aggregate_only:true, raw_query_retained:false, individual_linkage:false, bucket_key:bucket.bucket_key, schema_version:COVERAGE_HYPOTHESES.schema_version } } }
export function activeCoverageWorkspace(items = [], now = new Date().toISOString()) { return items.filter((item) => item.status !== "resolved" && new Date(item.expires_at) > new Date(now)).sort((a,b) => ({recurring:2,elevated:3,emerging:1}[b.strength_band]||0)-({recurring:2,elevated:3,emerging:1}[a.strength_band]||0) || String(b.updated_at||"").localeCompare(String(a.updated_at||""))).slice(0,COVERAGE_HYPOTHESES.maximum_active) }
