import { createHash } from "node:crypto"
export const HEALTH_CANADA = Object.freeze({ id: "health_canada_drug_safety", host: "open.canada.ca", endpoint: "https://open.canada.ca/data/api/3/action/package_show?id=d38de914-c94c-429b-8ab1-8776c31643e3", maxRequests: 1, maxBytes: 512 * 1024, maxRecords: 100, timeoutMs: 7000, mode: "fixture_validated" })
const terms = { methadone: ["methadone"], buprenorphine: ["buprenorphine","suboxone"], naloxone: ["naloxone","narcan"], naltrexone: ["naltrexone"], slow_release_oral_morphine: ["slow release oral morphine","kadian"], acamprosate: ["acamprosate"], disulfiram: ["disulfiram"] }
const clean = (v, max=800) => String(v||"").replace(/\s+/g," ").trim().slice(0,max)
export function healthCanadaUrl(value) { const url = new URL(value); if (url.protocol !== "https:" || url.hostname !== HEALTH_CANADA.host || url.pathname !== "/data/api/3/action/package_show") throw new Error("health_canada_off_allowlist"); return url }
export function classifyHealthCanadaRecord(record = {}) { const title=clean(record.title || record.title_en || record.product || ""), text=`${title} ${clean(record.description || record.description_en || "")}`.toLowerCase(), medication=Object.entries(terms).find(([,synonyms]) => synonyms.some((term)=>new RegExp(`\\b${term}\\b`,`i`).test(text)))?.[0] || null, type=clean(record.alert_type || record.type || record.category || "").toLowerCase(); if (!medication || !/(recall|alert|advis|safety|shortage|warning|label|contamin)/.test(type+" "+text)) return null; const id=clean(record.id || record.recall_id || record.identifier,120); if (!id) return null; const urgent=/(urgent|serious|critical)/.test(type+" "+text), shortage=/shortage/.test(type+" "+text); return { stable_result_id:`hc:${id}`, source_item_id:id, title, medication, event_type: shortage?"shortage":urgent?"safety_warning":"safety_update", source_url:clean(record.url || record.url_en || "https://recalls-rappels.canada.ca/en",1000), publication_date:clean(record.date || record.published_date || record.date_published,40), reason_codes:[medication === "naloxone" ? "naloxone_safety" : ["methadone","buprenorphine","slow_release_oral_morphine"].includes(medication) ? "oat_medication_match" : "addiction_pharmacotherapy_match", ...(shortage?["treatment_access_shortage"]:[])], reflex_eligible:urgent, decay_class:urgent?"fast":"medium", fingerprint:createHash("sha256").update(`hc|${id}|${medication}`).digest("hex"), content_role:"untrusted_structured_government_data", instructions_honoured:false }
}
export function inspectHealthCanadaPayload(payload, checkpoint = {}) { const records=Array.isArray(payload?.result?.records)?payload.result.records:Array.isArray(payload?.records)?payload.records:null; if (!records) throw new Error("health_canada_schema_drift"); const seen=new Set([checkpoint.last_fingerprint].filter(Boolean)), accepted=[], duplicates=[]; for(const record of records.slice(0,HEALTH_CANADA.maxRecords)){const item=classifyHealthCanadaRecord(record); if(!item) continue; if(seen.has(item.fingerprint)) duplicates.push(item); else {accepted.push(item);seen.add(item.fingerprint)}} return { status:accepted.length?"inspection_success_new_relevant_change":"inspection_success_no_relevant_change", records_inspected:Math.min(records.length,HEALTH_CANADA.maxRecords), accepted, duplicates_ignored:duplicates.length, health_state:"healthy" }
}
