import { createHash } from "node:crypto"

export const HUMAN_NEEDS = Object.freeze({ source: "public_directory_search", schema_version: "human-needs-v1", retention_days: 14, threshold: 5, maximum_dimensions: 2, enabled: (env = process.env) => env.MILLER_HUMAN_NEEDS_LEARNING_ENABLED === "true" })
const NEEDS = Object.freeze({ withdrawal_management:["withdrawal","detox"], outpatient_treatment:["outpatient"], residential_treatment:["residential treatment","rehab"], opioid_agonist_treatment:["methadone","buprenorphine","suboxone","oat"], counselling:["counselling","counseling"], harm_reduction:["harm reduction"], overdose_prevention:["overdose prevention","naloxone"], youth_services:["youth","teen"], family_support:["family support"], housing_support:["housing"], shelter:["shelter"], peer_support:["peer support"], medical_support:["medical support"], crisis_support:["crisis"] })
const BARRIERS = Object.freeze({ transportation:["transport","bus","transit"], mobility_accessibility:["wheelchair","accessible","mobility"], cost:["cost","free","afford"], waitlist:["waitlist","waiting list"], eligibility:["eligible","eligibility"], age_restriction:["age"], referral_requirement:["referral"], hours_availability:["open now","hours"], language_access:["language","translation"], virtual_access:["virtual","online"], geographic_distance:["near me","nearby","distance"], immediate_access:["today","immediately","urgent"] })
const REGIONS = Object.freeze({ fraser:["surrey","langley","abbotsford","burnaby","fraser"], vancouver_coastal:["vancouver","richmond","coastal"], island:["victoria","nanaimo","island"], interior:["kelowna","kamloops","interior"], northern:["prince george","northern"] })
const normalized = (value) => String(value || "").toLowerCase().normalize("NFKC").replace(/[^a-z0-9\s-]/g, " ").replace(/\s+/g, " ").trim().slice(0, 500)
const hit = (text, values) => values.some((value) => text.includes(value))
export function containsSensitiveEntity(value) { const text = String(value || ""); return /[\w.+-]+@[\w.-]+\.[a-z]{2,}/i.test(text) || /(?:\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]\d{3}[-.\s]\d{4}/.test(text) || /\b\d{1,6}\s+[a-z][a-z .'-]{2,}\b/i.test(text) }
export function classifyHumanNeed(query, city = "") { const text = normalized(query), regionText = normalized(city); if (!text) return { observations: [], rejected: "empty" }; const needs = Object.entries(NEEDS).filter(([, terms]) => hit(text, terms)).map(([key]) => key).slice(0, 2), barriers = Object.entries(BARRIERS).filter(([, terms]) => hit(text, terms)).map(([key]) => key).slice(0, 1), geography = Object.entries(REGIONS).find(([, terms]) => hit(`${text} ${regionText}`, terms))?.[0] || "province"; const observations = [...needs.map((theme) => ({ kind: "need", theme, geography })), ...barriers.map((theme) => ({ kind: "barrier", theme, geography }))].slice(0, 3); return { observations, sensitive_entity_detected: containsSensitiveEntity(query), geography, raw_retained: false }
}
export function humanNeedBucketKey({ kind, theme, geography, observedAt = new Date().toISOString() }) { const hour = new Date(observedAt).toISOString().slice(0, 13); return createHash("sha256").update([HUMAN_NEEDS.schema_version, kind, theme, geography, hour].join("|")).digest("hex") }
export function humanNeedBand(count) { return count >= 12 ? "elevated" : count >= HUMAN_NEEDS.threshold ? "recurring" : "emerging" }
export function aggregateNeedSignal(bucket) { if (!bucket || Number(bucket.observation_count) < HUMAN_NEEDS.threshold) return null; const subject = `${bucket.kind}:${bucket.theme}:${bucket.geography}`, topic_key = `service_system:${subject}`; return { topic_key, topic_type: "service_system", title: `Aggregate ${bucket.kind} demand: ${bucket.theme}`, geographic_scope: bucket.geography, service_scope: bucket.theme, signal_type: "coverage_gap", signal_family: "growth", source_id: "aggregate_directory_demand", source_authority: 55, magnitude: humanNeedBand(bucket.observation_count) === "elevated" ? .7 : .45, novelty: .5, relevance: .75, confidence: .55, observed_at: bucket.last_observed_at, decay_class: "medium", reflex_eligible: false, underlying_event_key: `human_need:${bucket.bucket_key}`, reason_codes: ["aggregate_human_need", `${bucket.kind}_${bucket.theme}`, `support_threshold_${HUMAN_NEEDS.threshold}`, `band_${humanNeedBand(bucket.observation_count)}`], provenance: { aggregate_only: true, raw_query_retained: false, user_linkage: false, count_band: humanNeedBand(bucket.observation_count), schema_version: HUMAN_NEEDS.schema_version } } }
export function activeNeedWorkspace(buckets = [], now = new Date().toISOString(), limit = 20) { return buckets.filter((bucket) => Number(bucket.observation_count) >= HUMAN_NEEDS.threshold && new Date(bucket.expires_at) > new Date(now)).sort((a, b) => b.observation_count - a.observation_count || String(a.bucket_key).localeCompare(String(b.bucket_key))).slice(0, limit).map((bucket) => ({ kind: bucket.kind, theme: bucket.theme, geography: bucket.geography, count_band: humanNeedBand(bucket.observation_count), expires_at: bucket.expires_at })) }
