import { buildPlannerDiagnostic } from "./plannerDiagnostics.js"

const severityRank = { critical: 0, high: 1, medium: 2, low: 3, maintenance: 4, healthy: 5 }
const latestByAttachment = (decisions = []) => {
  const latest = new Map()
  for (const decision of decisions) if (!latest.has(decision.attachment_id) || String(latest.get(decision.attachment_id).created_at) < String(decision.created_at)) latest.set(decision.attachment_id, decision)
  return latest
}
const finding = (input) => Object.freeze({ read_only: true, requires_human_review: true, actionable: true, resource_id: null, object_ids: [], reason_codes: [], ...input })

export function systemSecurityAudit({ attachments = [], scanDecisions = [], trendSensorItems = [], configuration = {} } = {}) {
  const decisions = latestByAttachment(scanDecisions), findings = []
  for (const attachment of attachments) {
    const decision = decisions.get(attachment.id), ids = [attachment.id]
    if (attachment.status === "available" && (!decision || decision.decision !== "clean" || decision.actor_type !== "scanner_service")) findings.push(finding({ finding_id: `security:attachment_available_without_clean:${attachment.id}`, domain: "system", finding_type: "attachment_available_without_clean_scan", severity: "critical", object_ids: ids, reason_codes: ["quarantine_invariant_broken"], explanation: "An attachment appears available without a clean scanner-service decision.", recommendation: "Immediately verify quarantine enforcement and restrict access." }))
    else if (decision?.decision === "malicious") findings.push(finding({ finding_id: `security:attachment_malicious:${attachment.id}`, domain: "system", finding_type: "malicious_attachment_detected", severity: "critical", object_ids: ids, reason_codes: ["malware_detected", "attachment_rejected"], explanation: "A malware scanner recorded a malicious attachment decision.", recommendation: "Keep the attachment rejected and review the submission through authorized procedures." }))
    else if (attachment.status === "pending_scan" && decision?.decision === "failed") findings.push(finding({ finding_id: `security:attachment_scan_failed:${attachment.id}`, domain: "system", finding_type: "attachment_scan_failed", severity: "medium", object_ids: ids, reason_codes: ["scanner_failed", "quarantine_retained"], explanation: "A scan failed and the attachment remains quarantined.", recommendation: "Restore the scanner before an authorized retry; do not make the attachment available." }))
    else if (attachment.status === "pending_scan" && !decision) findings.push(finding({ finding_id: `security:attachment_awaiting_scan:${attachment.id}`, domain: "system", finding_type: "attachment_awaiting_scan", severity: "low", object_ids: ids, reason_codes: ["pending_scan"], explanation: "An attachment is awaiting a scan decision and remains unavailable.", recommendation: "Process it only through the constrained scanner workflow." }))
    else if (attachment.status === "rejected" && decision?.decision !== "malicious") findings.push(finding({ finding_id: `security:attachment_rejected_without_malware:${attachment.id}`, domain: "system", finding_type: "attachment_quarantine_state_inconsistent", severity: "medium", object_ids: ids, reason_codes: ["unexpected_rejected_state"], explanation: "A rejected attachment has no current malicious scan decision.", recommendation: "Review immutable scan provenance before taking any action." }))
  }
  if (configuration.admin_allowlist_configured !== true) findings.push(finding({ finding_id: "security:admin_allowlist_missing", domain: "system", finding_type: "admin_protection_configuration", severity: "high", reason_codes: ["admin_allowlist_not_configured"], explanation: "Administrator access is not configured to fail closed through an email allowlist.", recommendation: "Configure the administrator allowlist before enabling admin use." }))
  if (configuration.attachment_quarantine_enforced !== true) findings.push(finding({ finding_id: "security:attachment_quarantine_unverified", domain: "system", finding_type: "attachment_quarantine_control", severity: "high", reason_codes: ["quarantine_control_unverified"], explanation: "The attachment quarantine control could not be confirmed.", recommendation: "Treat attachments as unavailable until the control is verified." }))
  const trendFailures = new Map()
  for (const item of trendSensorItems) if (["failed", "blocked"].includes(item.outcome)) trendFailures.set(item.source_id, (trendFailures.get(item.source_id) || 0) + 1)
  for (const [sourceId, count] of trendFailures) if (count >= 2) findings.push(finding({ finding_id: `security:trend_source_degraded:${sourceId}`, domain: "system", finding_type: "trend_source_degraded", severity: "medium", reason_codes: ["authoritative_source_repeated_failure", itemSafeCode(sourceId)], explanation: "A fixed authoritative Trend Sensor source repeatedly failed or was blocked.", recommendation: "Review its allowlisted entrypoint and parser before another authorized inspection." }))
  return findings.sort((a, b) => severityRank[a.severity] - severityRank[b.severity] || a.finding_id.localeCompare(b.finding_id))
}

const itemSafeCode = (value) => String(value || "unknown").replace(/[^a-z0-9_-]/gi, "_").slice(0, 80)

export function buildImmuneSystemHealth({ plannerState = {}, attachments = [], scanDecisions = [], trendSensorItems = [], sensorCheckpoints = [], configuration = {} } = {}) {
  const planner = buildPlannerDiagnostic(plannerState), security_findings = systemSecurityAudit({ attachments, scanDecisions, trendSensorItems, configuration })
  const knowledge_findings = planner.audit_findings.map((item) => finding({ finding_id: `knowledge:${item.resource_id}:${item.issue_type}`, domain: "knowledge", finding_type: item.issue_type, severity: item.issue_type === "authoritative_address_conflict" ? "high" : item.issue_type === "stale_evidence" ? "medium" : "low", resource_id: item.resource_id, reason_codes: item.reason_codes, actionable: item.recommended_next_action !== "no_action_needed", requires_human_review: item.recommended_next_action === "investigate_entity_relationship" || item.recommended_next_action === "stop_retrying_no_new_evidence", explanation: `Knowledge audit: ${item.issue_type.replaceAll("_", " ")}.`, recommendation: item.recommended_next_action }))
  const findings = [...knowledge_findings, ...security_findings].sort((a, b) => severityRank[a.severity] - severityRank[b.severity] || a.finding_id.localeCompare(b.finding_id))
  const healthCanada = sensorCheckpoints.find((item) => item.sensor_id === "health_canada_drug_safety"), now = Date.now(), stale = healthCanada?.last_success_at && now - new Date(healthCanada.last_success_at).getTime() > 2 * 86_400_000, healthCanadaStatus = !healthCanada ? "unknown" : stale ? "stale" : healthCanada.health_state
  const humanNeedsStatus = configuration.human_needs_enabled === true ? configuration.human_needs_privacy_ready === true ? "enabled" : "degraded" : "disabled"
  if (humanNeedsStatus === "degraded") findings.push(finding({ finding_id: "privacy:human_needs_unsafe_configuration", domain: "system", finding_type: "human_needs_privacy_configuration", severity: "high", reason_codes: ["human_needs_enabled_without_privacy_gate"], explanation: "Human Needs learning is enabled without its required privacy configuration.", recommendation: "Disable it until the privacy review configuration is complete." }))
  return { summary: { knowledge_findings: knowledge_findings.filter((item) => item.actionable).length, security_findings: security_findings.length, high_severity_findings: findings.filter((item) => ["critical", "high"].includes(item.severity)).length, quarantine_backlog: attachments.filter((item) => item.status === "pending_scan").length, failed_scans: security_findings.filter((item) => item.finding_type === "attachment_scan_failed").length, malicious_detections: security_findings.filter((item) => item.finding_type === "malicious_attachment_detected").length }, planner_summary: planner.summary, findings, sensors: [{ id: "pubmed_addiction_literature", status: "fixture_validated", cadence: "weekly", detail: "Bounded metadata adapter; manual authorization required." }, { id: "health_canada_drug_safety", status: healthCanadaStatus, cadence: "daily", last_success_at: healthCanada?.last_success_at || null, detail: "Fixed Health Canada recall feed; manual inspection only." }, { id: "human_needs", status: humanNeedsStatus, cadence: "event-derived", detail: "Aggregate-only, feature-flagged demand sensing; raw search text is never retained." }, { id: "bc_toxic_drug", status: "fixture_validated_live_disabled", cadence: "fast", detail: "No stable machine-readable first-party alert feed has been approved." }, { id: "bc_epidemiology", status: "fixture_validated_live_disabled", cadence: "monthly", detail: "Release-driven dashboard/report architecture requires a dedicated adapter." }], checks: [{ id: "attachment_delivery", status: configuration.attachment_quarantine_enforced === true ? "healthy" : "unknown", detail: "Attachments remain unavailable until a clean scanner-service decision." }, { id: "admin_allowlist", status: configuration.admin_allowlist_configured === true ? "healthy" : "degraded", detail: "Admin authorization uses the configured allowlist." }] }
}
