import { buildPlannerDiagnostic } from "./plannerDiagnostics.js"

const severityRank = { critical: 0, high: 1, medium: 2, low: 3, maintenance: 4, healthy: 5 }
const latestByAttachment = (decisions = []) => {
  const latest = new Map()
  for (const decision of decisions) if (!latest.has(decision.attachment_id) || String(latest.get(decision.attachment_id).created_at) < String(decision.created_at)) latest.set(decision.attachment_id, decision)
  return latest
}
const finding = (input) => Object.freeze({ read_only: true, requires_human_review: true, actionable: true, resource_id: null, object_ids: [], reason_codes: [], ...input })

export function systemSecurityAudit({ attachments = [], scanDecisions = [], configuration = {} } = {}) {
  const decisions = latestByAttachment(scanDecisions), findings = []
  for (const attachment of attachments) {
    const decision = decisions.get(attachment.id), ids = [attachment.id]
    if (attachment.status === "available" && (!decision || decision.decision !== "clean" || decision.actor_type !== "scanner_service")) findings.push(finding({ finding_id: `security:attachment_available_without_clean:${attachment.id}`, domain: "system", finding_type: "attachment_available_without_clean_scan", severity: "critical", object_ids: ids, reason_codes: ["quarantine_invariant_broken"], explanation: "An attachment appears available without a clean scanner-service decision.", recommendation: "Immediately verify quarantine enforcement and restrict access." }))
    else if (decision?.decision === "malicious") findings.push(finding({ finding_id: `security:attachment_malicious:${attachment.id}`, domain: "system", finding_type: "malicious_attachment_detected", severity: "critical", object_ids: ids, reason_codes: ["malware_detected", "attachment_rejected"], explanation: "A malware scanner recorded a malicious attachment decision.", recommendation: "Keep the attachment rejected and review the submission through authorized procedures." }))
    else if (attachment.status === "pending_scan" && decision?.decision === "failed") findings.push(finding({ finding_id: `security:attachment_scan_failed:${attachment.id}`, domain: "system", finding_type: "attachment_scan_failed", severity: "medium", object_ids: ids, reason_codes: ["scanner_failed", "quarantine_retained"], explanation: "A scan failed and the attachment remains quarantined.", recommendation: "Restore the scanner before an authorized retry; do not make the attachment available." }))
    else if (attachment.status === "pending_scan" && !decision) findings.push(finding({ finding_id: `security:attachment_awaiting_scan:${attachment.id}`, domain: "system", finding_type: "attachment_awaiting_scan", severity: "low", object_ids: ids, reason_codes: ["pending_scan"], explanation: "An attachment is awaiting a scan decision and remains unavailable.", recommendation: "Process it only through the constrained scanner workflow." }))
    else if (attachment.status === "rejected" && decision?.decision !== "malicious") findings.push(finding({ finding_id: `security:attachment_rejected_without_malware:${attachment.id}`, domain: "system", finding_type: "attachment_quarantine_state_inconsistent", severity: "medium", object_ids: ids, reason_codes: ["unexpected_rejected_state"], explanation: "A rejected attachment has no current malicious scan decision.", recommendation: "Review immutable scan provenance before taking any action." }))
  }
  if (configuration.admin_allowlist_configured !== true) findings.push(finding({ finding_id: "security:admin_allowlist_missing", domain: "system", finding_type: "admin_protection_configuration", severity: "high", reason_codes: ["admin_allowlist_not_configured"], explanation: "Administrator access is not configured to fail closed through an email allowlist.", recommendation: "Configure the administrator allowlist before enabling admin use." }))
  if (configuration.attachment_quarantine_enforced !== true) findings.push(finding({ finding_id: "security:attachment_quarantine_unverified", domain: "system", finding_type: "attachment_quarantine_control", severity: "high", reason_codes: ["quarantine_control_unverified"], explanation: "The attachment quarantine control could not be confirmed.", recommendation: "Treat attachments as unavailable until the control is verified." }))
  return findings.sort((a, b) => severityRank[a.severity] - severityRank[b.severity] || a.finding_id.localeCompare(b.finding_id))
}

export function buildImmuneSystemHealth({ plannerState = {}, attachments = [], scanDecisions = [], configuration = {} } = {}) {
  const planner = buildPlannerDiagnostic(plannerState), security_findings = systemSecurityAudit({ attachments, scanDecisions, configuration })
  const knowledge_findings = planner.audit_findings.map((item) => finding({ finding_id: `knowledge:${item.resource_id}:${item.issue_type}`, domain: "knowledge", finding_type: item.issue_type, severity: item.issue_type === "authoritative_address_conflict" ? "high" : item.issue_type === "stale_evidence" ? "medium" : "low", resource_id: item.resource_id, reason_codes: item.reason_codes, actionable: item.recommended_next_action !== "no_action_needed", requires_human_review: item.recommended_next_action === "investigate_entity_relationship" || item.recommended_next_action === "stop_retrying_no_new_evidence", explanation: `Knowledge audit: ${item.issue_type.replaceAll("_", " ")}.`, recommendation: item.recommended_next_action }))
  const findings = [...knowledge_findings, ...security_findings].sort((a, b) => severityRank[a.severity] - severityRank[b.severity] || a.finding_id.localeCompare(b.finding_id))
  return { summary: { knowledge_findings: knowledge_findings.filter((item) => item.actionable).length, security_findings: security_findings.length, high_severity_findings: findings.filter((item) => ["critical", "high"].includes(item.severity)).length, quarantine_backlog: attachments.filter((item) => item.status === "pending_scan").length, failed_scans: security_findings.filter((item) => item.finding_type === "attachment_scan_failed").length, malicious_detections: security_findings.filter((item) => item.finding_type === "malicious_attachment_detected").length }, planner_summary: planner.summary, findings, checks: [{ id: "attachment_delivery", status: configuration.attachment_quarantine_enforced === true ? "healthy" : "unknown", detail: "Attachments remain unavailable until a clean scanner-service decision." }, { id: "admin_allowlist", status: configuration.admin_allowlist_configured === true ? "healthy" : "degraded", detail: "Admin authorization uses the configured allowlist." }] }
}
