import { lessonFromOutcome, reinforceLesson } from "./maintenanceLearning.js"

const bounded = (value, limit = 2_000) => { const safe = JSON.parse(JSON.stringify(value || {})); return JSON.stringify(safe).length <= limit ? safe : {} }
export function createMaintenancePersistence(supabase) {
  return {
    async recordOutcome(outcome) { const values = { cycle_id: outcome.cycle_id, need_key: String(outcome.need_key).slice(0,180), action_id: String(outcome.action_id).slice(0,100), action_version: "v1", domain: outcome.domain, target_type: String(outcome.target_type).slice(0,80), target_key: String(outcome.target_key).slice(0,180), before_state: bounded(outcome.before), expected_state: bounded(outcome.expected), after_state: bounded(outcome.after), verification: outcome.verified ? "passed" : outcome.classification === "inconclusive" ? "inconclusive" : "failed", classification: outcome.classification, completed_at: new Date().toISOString() }; const result = await supabase.from("miller_maintenance_outcomes").insert(values).select().single(); if(result.error) throw result.error; return result.data },
    async updateLesson(outcome) { const evidence=lessonFromOutcome(outcome); if(!evidence) return null; const current=await supabase.from("miller_learning_records").select("*").eq("lesson_fingerprint",evidence.lesson_fingerprint).maybeSingle(); if(current.error) throw current.error; const lesson=reinforceLesson(current.data,evidence), values={lesson_fingerprint:lesson.lesson_fingerprint,domain:lesson.domain,lesson_type:lesson.lesson_type,scope:lesson.scope,statement:lesson.statement,support_count:lesson.support_count,contradiction_count:lesson.contradiction_count,status:lesson.status,last_confirmed_at:new Date().toISOString()}; const saved=await supabase.from("miller_learning_records").upsert(values,{onConflict:"lesson_fingerprint"}).select().single();if(saved.error)throw saved.error;return saved.data },
    async observeGrowth(item) { const values={...item,last_observed_at:new Date().toISOString(),recurrence_count:1}; const existing=await supabase.from("miller_growth_opportunities").select("id,recurrence_count").eq("opportunity_fingerprint",item.opportunity_fingerprint).maybeSingle();if(existing.error)throw existing.error;if(existing.data){const updated=await supabase.from("miller_growth_opportunities").update({...values,recurrence_count:existing.data.recurrence_count+1}).eq("id",existing.data.id).select().single();if(updated.error)throw updated.error;return updated.data}const saved=await supabase.from("miller_growth_opportunities").insert(values).select().single();if(saved.error)throw saved.error;return saved.data }
    ,async observeCapabilityGap(item) { const existing=await supabase.from("miller_capability_gaps").select("id,observation_count").eq("gap_fingerprint",item.gap_fingerprint).maybeSingle();if(existing.error)throw existing.error;const values={...item,last_observed_at:new Date().toISOString(),observation_count:Number(existing.data?.observation_count||0)+1};const saved=existing.data?await supabase.from("miller_capability_gaps").update(values).eq("id",existing.data.id).select().single():await supabase.from("miller_capability_gaps").insert(values).select().single();if(saved.error)throw saved.error;return saved.data}
  }
}
