const plan = {
  saskatchewan: [
    ["Prince Albert Victoria Hospital Indigenous patient racism 2025", "facility_recent"],
    ["Prince Albert Victoria Hospital First Nations patient complaint 2026", "facility_recent"],
    ["Prince Albert Victoria Hospital Indigenous family complaint 2024", "facility_recent"],
    ["Royal University Hospital Saskatoon Indigenous patient discrimination 2025", "facility_recent"],
    ["Royal University Hospital Saskatoon First Nations family complaint 2026", "facility_recent"],
    ["St. Paul's Hospital Saskatoon Indigenous patient racism 2025", "facility_recent"],
    ["St. Paul's Hospital Saskatoon First Nations patient complaint 2024", "facility_recent"],
    ["Regina hospital alleged racism third-party review Indigenous patient 2023", "social_lead_verification"],
    ["Battlefords Union Hospital Indigenous patient racism 2025", "facility_recent"],
    ["Battlefords Union Hospital First Nations family complaint 2024", "facility_recent"],
    ["Lloydminster Hospital Saskatchewan Indigenous patient discrimination 2025", "facility_recent"],
    ["Saskatchewan Health Authority Indigenous patient investigation 2025", "institutional_recent"],
    ["site:fsin.com hospital Indigenous patient Saskatchewan 2025", "indigenous_organization_recent"],
    ["site:aptnnews.ca Saskatchewan hospital First Nations patient 2025", "indigenous_journalism_recent"],
    ["site:cbc.ca Saskatchewan hospital Indigenous patient racism 2026", "journalism_recent"],
    ["site:globalnews.ca Saskatchewan hospital Indigenous family complaint 2025", "journalism_recent"],
    ["Prince Albert Grand Council hospital racism 2025", "indigenous_organization_recent"],
    ["Saskatchewan First Nations Health Ombudsperson hospital incident 2026", "organization_recent"],
    ["site:reddit.com/r/saskatchewan Prince Albert hospital Indigenous patient racism 2025", "reddit_recent"],
    ["site:reddit.com/r/saskatoon hospital Indigenous patient complaint 2025", "reddit_recent"],
  ],
  alberta: [
    ["Royal Alexandra Hospital Edmonton Indigenous patient racism 2025", "facility_recent"],
    ["Royal Alexandra Hospital Edmonton First Nations family complaint 2026", "facility_recent"],
    ["Misericordia Hospital Edmonton Indigenous patient discrimination 2025", "facility_recent"],
    ["University of Alberta Hospital Indigenous patient racism 2025", "facility_recent"],
    ["University of Alberta Hospital First Nations patient complaint 2024", "facility_recent"],
    ["Grey Nuns Community Hospital Indigenous patient discrimination 2025", "facility_recent"],
    ["Stollery Children's Hospital Indigenous family complaint 2025", "facility_recent"],
    ["Fort Saskatchewan Community Hospital Indigenous patient racism 2024", "facility_recent"],
    ["Wetaskiwin Hospital Indigenous patient discrimination 2025", "facility_recent"],
    ["Maskwacis healthcare Indigenous patient hospital complaint 2025", "treaty6_facility_recent"],
    ["Red Deer Regional Hospital Indigenous patient racism 2025", "facility_recent"],
    ["Alberta Health Services Edmonton Indigenous patient investigation 2025", "institutional_recent"],
    ["site:aptnnews.ca Alberta hospital Indigenous patient 2025", "indigenous_journalism_recent"],
    ["site:cbc.ca Edmonton hospital First Nations patient complaint 2025", "journalism_recent"],
    ["site:globalnews.ca Alberta hospital Indigenous family complaint 2025", "journalism_recent"],
    ["site:albertahumanrights.ab.ca Indigenous healthcare hospital complaint Alberta", "human_rights"],
    ["Edmonton Indigenous organization hospital racism 2025", "indigenous_organization_recent"],
    ["Maskwacis First Nation hospital discrimination 2024", "treaty6_organization_recent"],
    ["site:reddit.com/r/Edmonton hospital Indigenous patient racism 2025", "reddit_recent"],
    ["site:reddit.com/r/alberta Edmonton hospital First Nations complaint 2025", "reddit_recent"],
  ],
  british_columbia: [
    ["Royal Jubilee Hospital Indigenous patient racism 2025", "facility_recent"],
    ["Cowichan District Hospital Indigenous family complaint 2025", "facility_recent"],
    ["Victoria General Hospital Indigenous patient discrimination 2026", "facility_recent"],
    ["Vancouver General Hospital Indigenous patient racism 2025", "facility_recent"],
    ["Surrey Memorial Hospital First Nations patient complaint 2025", "facility_recent"],
    ["St. Paul's Hospital Vancouver Indigenous patient discrimination 2024", "facility_recent"],
    ["Mills Memorial Hospital Terrace Indigenous patient 2025", "facility_recent"],
    ["site:aptnnews.ca B.C. hospital Indigenous patient 2025", "indigenous_journalism_recent"],
    ["site:cbc.ca British Columbia hospital Indigenous family complaint 2025", "journalism_recent"],
    ["site:reddit.com/r/britishcolumbia hospital Indigenous patient racism 2025", "reddit_recent"],
  ],
}

export function buildMillerNorthRecentDiscoveryV1() {
  const campaign_id = "miller-north-recent-facility-discovery-v1"
  const queries = Object.entries(plan).flatMap(([province, rows]) => rows.map(([query, lane]) => ({
    campaign_id,
    province,
    regional_context: province === "alberta" || province === "saskatchewan" ? "Treaty 6 research geography where facility/community geography supports it; never person identity." : "British Columbia comparison region",
    lane,
    query,
  })))
  return { campaign_id, version: "miller-north-recent-facility-checkpoint-v1", queries }
}
