import { createHash } from "node:crypto"
export const PUBMED = Object.freeze({ id: "pubmed", host: "eutils.ncbi.nlm.nih.gov", base: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils", maxRequests: 3, maxRecords: 20, maxDeepRecords: 5, timeoutMs: 7000, maxBytes: 256 * 1024, requestsPerSecond: 3 })
export const PUBMED_TOPICS = Object.freeze({ contingency_management: "contingency management stimulant use disorder", opioid_use_disorder: "opioid use disorder", opioid_agonist_treatment: "opioid agonist treatment", buprenorphine: "buprenorphine", methadone: "methadone", slow_release_oral_morphine: "slow release oral morphine", stimulant_use_disorder: "stimulant use disorder", alcohol_use_disorder: "alcohol use disorder treatment", withdrawal_management: "withdrawal management", overdose_prevention: "overdose prevention", harm_reduction: "harm reduction", youth_substance_use: "youth substance use", digital_addiction_treatment: "digital addiction treatment", emerging_addiction_pharmacotherapy: "addiction pharmacotherapy" })
const clean = (value, max = 1000) => String(value || "").replace(/\s+/g, " ").trim().slice(0, max)
export function pubmedPlan(topicKey) { const term = PUBMED_TOPICS[topicKey]; if (!term) throw new Error("unsupported_pubmed_topic"); return { investigation_type: "review_scientific_development", tool_id: PUBMED.id, topic_key: topicKey, query: `(${term}) AND ("last 365 days"[pdat])`, max_search_requests: 1, max_metadata_requests: 2, max_records_considered: 20, max_records_deeply_inspected: 5, no_publisher_fetch: true, no_canonical_mutation: true } }
export function pubmedUrl(path, parameters = {}) { const url = new URL(`${PUBMED.base}/${path}`); for (const [key,value] of Object.entries({ retmode: "json", tool: "miller_attention", ...parameters })) url.searchParams.set(key, String(value)); return url }
export function classifyStudyType(types = []) { const text = types.map((item) => clean(item).toLowerCase()).join(" | "); if (/practice guideline|guideline|consensus/.test(text)) return "guideline"; if (/meta-analysis|systematic review/.test(text)) return "systematic_review"; if (/randomized controlled trial/.test(text)) return "randomized_trial"; if (/observational/.test(text)) return "observational_study"; if (/clinical trial/.test(text)) return "clinical_trial_registration"; return "other_research" }
export function normalizePubmedSummary(record = {}, topicKey) { const pmid = clean(record.uid || record.pmid, 40); if (!/^\d+$/.test(pmid)) return null; const title = clean(record.title, 500); if (!title) return null; return { stable_result_id: `pmid:${pmid}`, pmid, title, abstract: clean(record.abstract, 4000), journal: clean(record.fulljournalname || record.source, 300), publication_date: clean(record.pubdate || record.epubdate, 40), doi: clean((record.elocationid || "").replace(/^doi:\s*/i, ""), 300), study_type: classifyStudyType(record.pubtype || record.publicationtypes || []), topic_key: topicKey, fingerprint: createHash("sha256").update(`${pmid}|${topicKey}`).digest("hex"), content_role: "untrusted_scientific_metadata", instructions_honoured: false }
}
async function boundedJson(response) { const length = Number(response.headers.get("content-length") || 0); if (!response.ok || length > PUBMED.maxBytes || !String(response.headers.get("content-type") || "").includes("json")) throw new Error("pubmed_invalid_response"); const text = await response.text(); if (Buffer.byteLength(text) > PUBMED.maxBytes) throw new Error("pubmed_response_too_large"); return { value: JSON.parse(text), bytes: Buffer.byteLength(text) } }
export async function inspectPubmed(plan, { fetchImpl = fetch } = {}) { if (plan?.tool_id !== PUBMED.id) throw new Error("invalid_pubmed_plan"); const search = await boundedJson(await fetchImpl(pubmedUrl("esearch.fcgi", { db: "pubmed", term: plan.query, retmax: plan.max_records_considered }))); const ids = (search.value.esearchresult?.idlist || []).slice(0, plan.max_records_deeply_inspected); if (!ids.length) return { requests_used: 1, bytes: search.bytes, records: [], stop_reason: "no_material_change" }; const summaries = await boundedJson(await fetchImpl(pubmedUrl("esummary.fcgi", { db: "pubmed", id: ids.join(",") }))); const records = ids.map((id) => normalizePubmedSummary(summaries.value.result?.[id], plan.topic_key)).filter(Boolean); return { requests_used: 2, bytes: search.bytes + summaries.bytes, records, stop_reason: records.length ? "bounded_metadata_complete" : "no_material_change" } }
