export const PROVIDERS = Object.freeze({ miller: { status: "available", capabilities: ["resource_search", "trusted_facts"] }, tavily: { status: "available_when_configured", capabilities: ["discovery", "change_research"] }, geocoder: { status: "available_when_configured", capabilities: ["resolve_origin", "validate_address"] }, transit: { status: "available", capabilities: ["destination_access"] }, bc211: { status: "pending_access", capabilities: [] }, pathways: { status: "pending_authorized_access", capabilities: [] } })
export function planRetrieval({ intent = {}, task = "search", selectedCandidate = null, currentVerificationRequired = false } = {}) {
  const steps = [{ provider: "miller", capability: "resource_search", required: true, reason: "trusted_local_search" }]
  if (intent.explicit?.locationText && intent.explicit.locationText !== intent.explicit.city) steps.push({ provider: "geocoder", capability: "resolve_origin", required: false, reason: "explicit_location_phrase" })
  if (selectedCandidate?.mapped && intent.explicit?.transport?.transitRelevant) steps.push({ provider: "transit", capability: "destination_access", required: false, reason: "selected_mapped_candidate_and_explicit_transit_need" })
  if (currentVerificationRequired || task === "maintenance") steps.push({ provider: "tavily", capability: "change_research", required: false, reason: "current_public_evidence_requested" })
  return { version: "miller-orchestration-v1.0.0", task, steps, omitted: Object.keys(PROVIDERS).filter((provider) => !steps.some((step) => step.provider === provider)).map((provider) => ({ provider, reason: PROVIDERS[provider].status.includes("pending") ? PROVIDERS[provider].status : "not_needed" })), failurePolicy: "continue_with_trusted_miller_data", allProviderFanout: false }
}
export function collectProviderResults(plan, results = {}) { return plan.steps.flatMap((step) => (results[step.provider] || []).map((item) => ({ ...item, provenance: { ...(item.provenance || {}), provider: step.provider, capability: step.capability } }))) }
