import { normalizeIdentityText, normalizePhone, normalizePublicUrl } from "../resourceIdentity.js"
function text(value, max = 2_000) { return String(value ?? "").replace(/\s+/g, " ").trim().slice(0, max) }
function safeHttps(value) { try { const url = new URL(value); return url.protocol === "https:" ? url.toString() : "" } catch { return "" } }
export function normalizeResourceCandidate(input = {}) {
  return { version: "miller-resource-candidate-v1.0.0", provider: text(input.provider, 80), sourceRecordId: text(input.sourceRecordId, 200), canonicalCandidateId: text(input.canonicalCandidateId, 200) || null, name: text(input.name, 300), operator: text(input.operator, 300), description: text(input.description), categories: Array.isArray(input.categories) ? input.categories.map((x) => text(x, 100)).filter(Boolean).slice(0, 20) : [], location: input.location ? { address: text(input.location.address, 500), city: text(input.location.city, 100), postalCode: text(input.location.postalCode, 20), latitude: Number.isFinite(Number(input.location.latitude)) ? Number(input.location.latitude) : null, longitude: Number.isFinite(Number(input.location.longitude)) ? Number(input.location.longitude) : null } : null, contact: { phone: text(input.contact?.phone, 80), website: safeHttps(input.contact?.website), email: text(input.contact?.email, 320) }, hours: input.hours ?? null, eligibility: input.eligibility ?? null, accessibility: input.accessibility ?? null, intake: input.intake ?? null, evidence: Array.isArray(input.evidence) ? input.evidence.slice(0, 30) : [], freshness: text(input.freshness, 40) || null, trustState: ["trusted", "reviewed", "unverified", "unknown"].includes(input.trustState) ? input.trustState : "unknown" }
}
export function resolveCandidateEntity(left, right, aliases = []) {
  if (aliases.some((item) => item.provider === right.provider && String(item.sourceRecordId) === String(right.sourceRecordId) && item.canonicalId === left.canonicalCandidateId)) return { classification: "definite_match", reasonCodes: ["confirmed_source_alias"] }
  const exactUrl = normalizePublicUrl(left.contact?.website) && normalizePublicUrl(left.contact.website) === normalizePublicUrl(right.contact?.website), exactPhone = normalizePhone(left.contact?.phone) && normalizePhone(left.contact.phone) === normalizePhone(right.contact?.phone), exactAddress = normalizeIdentityText(left.location?.address) && normalizeIdentityText(left.location.address) === normalizeIdentityText(right.location?.address), sameName = normalizeIdentityText(left.name) === normalizeIdentityText(right.name), sameOperator = normalizeIdentityText(left.operator) && normalizeIdentityText(left.operator) === normalizeIdentityText(right.operator)
  if (sameName && ((exactPhone && exactAddress) || (exactUrl && exactPhone))) return { classification: "definite_match", reasonCodes: ["program_name_and_two_identity_signals"] }
  if (sameName && [exactUrl, exactPhone, exactAddress].filter(Boolean).length >= 1) return { classification: "probable_match", reasonCodes: ["program_name_and_one_identity_signal"] }
  if ((exactUrl || sameOperator) && !sameName) return { classification: "distinct", reasonCodes: ["same_operator_or_website_different_program"] }
  if (sameName || exactPhone || exactAddress) return { classification: "uncertain", reasonCodes: ["single_identity_signal_only"] }
  return { classification: "distinct", reasonCodes: ["no_material_identity_agreement"] }
}
