export function createAutomationControls(overrides = {}) { return { shadowEnabled: true, factUpdatesEnabled: false, locationPublicationEnabled: false, resourcePublicationEnabled: false, maintenanceUpdatesEnabled: false, killSwitchActive: true, ...overrides } }
export function automationAllowed(controls, action) { if (controls.killSwitchActive) return false; const keys = { fact_update: "factUpdatesEnabled", location_publication: "locationPublicationEnabled", resource_publication: "resourcePublicationEnabled", maintenance_update: "maintenanceUpdatesEnabled" }; return Boolean(keys[action] && controls[keys[action]]) }
export function buildShadowObservation({ id, subjectId, field, currentValue = null, proposedValue, recommendation, evidence = [], reasonCodes = [], version = 0 }) { return { id, subjectId, field, currentValue, proposedValue, recommendation, evidence: evidence.slice(0, 30), reasonCodes, version, status: recommendation === "human_review" ? "needs_review" : "handled", trustedRecordChanged: false, publicationChanged: false, createdAt: new Date().toISOString() } }
export class ShadowDecisionStore {
  constructor(items = [], controls = createAutomationControls()) { this.items = new Map(items.map((item) => [item.id, structuredClone(item)])); this.audit = []; this.controls = controls }
  decide({ id, expectedVersion, decision, actorId }) { const current = this.items.get(id); if (!current) return { ok: false, code: "not_found" }; if (current.version !== expectedVersion) return { ok: false, code: "shadow_version_conflict", current: structuredClone(current) }; const previous = structuredClone(current), next = { ...current, status: decision, version: current.version + 1, decidedBy: actorId, decidedAt: new Date().toISOString() }; this.items.set(id, next); const event = { id: `event-${this.audit.length + 1}`, observationId: id, previous, next: structuredClone(next), actorId, decision, createdAt: next.decidedAt }; this.audit.push(event); return { ok: true, item: structuredClone(next), event } }
  rollback({ eventId, actorId }) { const event = this.audit.find((item) => item.id === eventId); if (!event) return { ok: false, code: "event_not_found" }; const current = this.items.get(event.observationId); if (current.version !== event.next.version) return { ok: false, code: "rollback_version_conflict" }; const restored = { ...event.previous, version: current.version + 1, rolledBackBy: actorId, rolledBackAt: new Date().toISOString() }; this.items.set(event.observationId, restored); this.audit.push({ id: `event-${this.audit.length + 1}`, observationId: event.observationId, previous: structuredClone(current), next: structuredClone(restored), actorId, decision: "rollback", createdAt: restored.rolledBackAt }); return { ok: true, item: restored } }
}
export function shadowAgreement(observation, administratorDecision) { const equivalent = { approve_suggestion: ["auto_accept", "accept_with_monitoring"], keep_existing: ["human_review"], reject: ["reject"], mark_unknown: ["unknown"] }; return { millerRecommendation: observation.recommendation, administratorDecision, agreement: (equivalent[administratorDecision] || []).includes(observation.recommendation), field: observation.field, reasonCodes: observation.reasonCodes } }
export function partitionShadowQueue(items = []) { return { needsReview: items.filter((item) => item.status === "needs_review"), handledByMiller: items.filter((item) => item.status === "handled") } }
