import { useCallback, useEffect, useMemo, useState } from "react"
import { adminFetch } from "../adminApi.js"
const readable = (value) => String(value || "unknown").replaceAll("_", " ")
export default function Attention() {
  const [report, setReport] = useState(null), [filter, setFilter] = useState("all"), [message, setMessage] = useState("")
  const load = useCallback(async () => { try { const response = await adminFetch("/api/admin/attention"), body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error); setReport(body) } catch (error) { setMessage(error.message || "Attention is unavailable.") } }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  const topics = useMemo(() => (report?.topics || []).filter((topic) => filter === "all" || topic.state === filter || topic.contributing_families?.includes(filter)), [report, filter])
  const recalculate = async () => { if (!window.confirm("Recalculate persistent attention from existing private signals? This makes no external request and cannot change resources or map pins.")) return; try { const response = await adminFetch("/api/admin/attention/recalculate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirm: true }) }), body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error); setMessage(`Recalculated ${body.recalculated_topics} topic(s).`); await load() } catch (error) { setMessage(error.message || "Attention recalculation failed.") } }
  const investigate = async (question) => { if (!window.confirm(`${question.question}\n\nTool: PubMed metadata only. Maximum: 3 requests, 20 records. Miller cannot change canonical resources, guidance, or map pins.`)) return; try { const response = await adminFetch(`/api/admin/attention/questions/${encodeURIComponent(question.question_id)}/investigate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirm: true }) }), body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error); setMessage(`Investigation stopped: ${readable(body.outcome)}. ${body.results?.length || 0} bounded finding(s).`); await load() } catch (error) { setMessage(error.message || "Investigation could not run.") } }
  return <section className="admin-review-panel attention" aria-labelledby="attention-title"><div className="results-head"><div><p className="eyebrow">Administrator only · deterministic planning</p><h2 id="attention-title">Miller’s Attention</h2></div></div><p>Attention prioritizes review; it is not truth, permission, or execution authorization.</p>{message ? <p role="status">{message}</p> : null}<div className="review-tabs" aria-label="Attention filters">{[["all","All"],["watch","Watch"],["focus","Focus"],["urgent_review","Urgent review"],["services","Services"],["scientific","Scientific"],["pharmacology","Pharmacology"],["toxic_drug","Overdose/toxic drug"],["policy","Policy"],["growth","Growth"]].map(([id,label]) => <button type="button" key={id} aria-selected={filter === id} onClick={() => setFilter(id)}>{label}</button>)}</div><div className="resource-review-actions"><button type="button" onClick={recalculate}>Recalculate attention</button></div>{!report ? <p role="status">Loading private attention state…</p> : topics.length ? <div className="evidence-cards">{topics.slice(0, 20).map((topic) => <article className="evidence-card" key={topic.id}><p><strong>{topic.title}</strong></p><p><strong>{readable(topic.state)} · score {topic.current_score} · {topic.trend}</strong></p><p>{topic.geographic_scope || "Miller-wide"}{topic.service_scope ? ` · ${readable(topic.service_scope)}` : ""}</p><p><strong>Why it matters:</strong> {topic.reason_codes?.map(readable).join(", ") || "current private signal history"}</p><p><strong>Families:</strong> {topic.contributing_families?.map(readable).join(", ") || "none"}</p><details><summary>Why is this getting attention?</summary><p>First observed: {topic.first_observed_at}; last reinforced: {topic.last_reinforced_at || "not yet reinforced"}; {topic.unique_event_count} independent event(s).</p></details></article>)}</div> : <p>No topics match this view. Signals remain private until an authorized fixed-source inspection records them.</p>}{report?.curiosity_questions?.length ? <div className="evidence-cards">{report.curiosity_questions.map((question) => <article className="evidence-card" key={question.question_id}><p><strong>{question.question}</strong></p><p>Plan: {readable(question.investigation_type)} · PubMed metadata only · max 3 requests / 20 records.</p><button type="button" onClick={() => investigate(question)} disabled={question.investigation_type !== "review_scientific_development"}>Investigate this question</button></article>)}</div> : null}</section>
}
