import { useCallback, useEffect, useState } from "react"
import { adminFetch } from "../adminApi.js"

const readable = (value) => String(value || "unknown").replaceAll("_", " ")

export default function ControlRoom() {
  const [data, setData] = useState(null), [message, setMessage] = useState(""), [question, setQuestion] = useState(""), [answer, setAnswer] = useState(""), [asking, setAsking] = useState(false), [context, setContext] = useState(null), [filter, setFilter] = useState("all")
  const load = useCallback(async () => { try { const response = await adminFetch("/api/admin/control-room-summary"), body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); setMessage("") } catch (error) { setMessage(error.message || "Control Room is unavailable.") } }, [])
  useEffect(() => { load() }, [load])
  const explain = (item) => { setContext(item.context || { type: item.domain || item.id }); setQuestion(`Explain ${item.title || item.text || "this"}`); setAnswer("") }
  const ask = async (event) => { event.preventDefault(); if (!question.trim() || asking) return; setAsking(true); setAnswer(""); try { const response = await adminFetch("/api/admin/miller-guide", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question, selected_context: context }) }), body = await response.json(); if (!response.ok) throw new Error(body.error); if (body.action_required === "run_security_pulse") { if (!window.confirm("Run Security Pulse? It checks fixed local controls and does not change settings.")) return setAnswer(body.text); const run = await adminFetch("/api/admin/security-pulse/run", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirm: true }) }), result = await run.json(); setAnswer(run.ok ? "Security Pulse completed. The summary has been refreshed." : result.error); if (run.ok) await load() } else setAnswer(body.text) } catch (error) { setAnswer(error.message || "Miller could not answer from the current protected summary.") } finally { setAsking(false) } }
  if (!data) return <section className="admin-review-panel"><h2>Miller Control Room</h2><p role="status">{message || "Loading protected system summary…"}</p></section>
  const timeline = filter === "all" ? data.timeline || [] : (data.timeline || []).filter((item) => item.domain === filter)
  return <section className="admin-review-panel control-room" aria-labelledby="control-room-title">
    <header className="results-head"><div><p className="eyebrow">Administrator only · plain-language overview</p><h2 id="control-room-title">Miller Control Room</h2><p><strong>Overall: {readable(data.posture)}</strong></p></div><button type="button" onClick={load}>Refresh summary</button></header>
    <section className="miller-guidance control-room-bubble" aria-label="Miller's current summary"><h3>Miller</h3><p>{data.bubble}</p>{context ? <p><small>Explaining: {readable(context.type)}</small></p> : null}</section>
    <section aria-labelledby="control-automation"><h3 id="control-automation">Automation / Heartbeat</h3><p><strong>{readable(data.automation?.state)}</strong> · {data.automation?.reason}</p><p>Last wake: {data.automation?.last_wake_at ? new Date(data.automation.last_wake_at).toLocaleString() : "not yet recorded"}. Next expected: {data.automation?.next_expected_at ? new Date(data.automation.next_expected_at).toLocaleString() : "not scheduled"}.</p><p>Security Pulse: <strong>{readable(data.automation?.security_pulse?.freshness)}</strong>. Automatic work is limited to local scheduled orientation and the fixed Security Pulse capability; maintenance, deployments, migrations, and configuration changes still require their existing authority.</p><button type="button" onClick={() => explain({ domain: "maintenance", title: "automation schedule" })}>Explain schedule</button></section>
    <section aria-labelledby="control-important"><h3 id="control-important">Important</h3>{data.important?.length ? <div className="evidence-cards">{data.important.map((item) => <article className="evidence-card" key={item.id}><strong>{item.title}</strong><p>{item.detail}</p><div className="pending-actions"><a href={item.href}>Open details</a><button type="button" onClick={() => explain(item)}>Explain</button></div></article>)}</div> : <p>No urgent issues are recorded.</p>}</section>
    <section aria-labelledby="control-needs-you"><h3 id="control-needs-you">Miller needs you</h3>{data.needs_you?.length ? <div className="resolution-summary">{data.needs_you.map((item) => <a key={item.id} href={item.href}><strong>{item.count}</strong><span>{item.title}</span></a>)}</div> : <p>No human decision is currently waiting in the summarized queues.</p>}</section>
    <section aria-labelledby="control-handled"><h3 id="control-handled">Miller handled this</h3>{data.handled?.length ? <ul>{data.handled.map((item) => <li key={item.id}>{item.text}</li>)}</ul> : <p>No recent completed bounded work is recorded.</p>}</section>
    <section className="miller-guidance" aria-label="Ask Miller about current operations"><h3>Ask Miller</h3><p>Ask about current status, changes, security, deployment, reviews, maintenance, or a selected item. Questions explain; buttons perform actions.</p><form className="map-chat-form" onSubmit={ask}><label htmlFor="miller-guide-question">Ask Miller about what is happening</label><textarea id="miller-guide-question" rows="2" maxLength="500" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="What should I look at first?"/><button type="submit" disabled={!question.trim() || asking}>{asking ? "Checking…" : "Ask Miller"}</button></form>{answer ? <p role="status">{answer}</p> : null}</section>
    <section aria-labelledby="control-changes"><h3 id="control-changes">What changed?</h3>{data.changes?.length ? <ul>{data.changes.map((item, index) => <li key={`${item.domain}:${index}`}>{item.text}</li>)}</ul> : <p>No meaningful recent change is recorded.</p>}</section>
    <section aria-labelledby="control-timeline"><h3 id="control-timeline">Recent activity</h3><div className="pending-actions" aria-label="Timeline filters">{["all", "security", "resources", "sensors", "operations", "deployment"].map((item) => <button type="button" key={item} aria-pressed={filter === item} onClick={() => setFilter(item)}>{readable(item)}</button>)}</div>{timeline.length ? <ol>{timeline.map((item) => <li key={item.id}><strong>{readable(item.domain)}</strong> · {item.text}</li>)}</ol> : <p>No activity matches this filter.</p>}</section>
    <details><summary>System areas</summary><div className="evidence-cards">{(data.subsystems || []).map((item) => <article className="evidence-card" key={item.id}><strong>{item.label} · {readable(item.state)}</strong><p>{item.detail}</p><button type="button" onClick={() => explain({ ...item, title: item.label })}>Explain</button></article>)}</div></details>
    {message ? <p role="status">{message}</p> : null}
  </section>
}
