import { useCallback, useEffect, useState } from "react"
import { adminFetch } from "../adminApi.js"

export default function CuratedListManager() {
  const [lists, setLists] = useState([]), [detail, setDetail] = useState(null), [status, setStatus] = useState("Loading curated lists…")
  const [title, setTitle] = useState("Low-Cost Community Counselling Options"), [slug, setSlug] = useState("low-cost-community-counselling-options")
  const load = useCallback(async () => { const response = await adminFetch("/api/admin/curated-lists"); const body = await response.json().catch(() => ({})); if (!response.ok) return setStatus(body.error || "Lists could not be loaded."); setLists(body.items || []); setStatus(`${body.items?.length || 0} curated list(s).`) }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  async function upload(event) { event.preventDefault(); const file = event.currentTarget.elements.source.files?.[0]; if (!file) return; setStatus("Uploading privately and parsing…"); const response = await adminFetch("/api/admin/list-imports", { method: "POST", headers: { "Content-Type": file.type || "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "X-File-Name": encodeURIComponent(file.name), "X-List-Title": encodeURIComponent(title), "X-List-Slug": encodeURIComponent(slug) }, body: file }); const body = await response.json().catch(() => ({})); setStatus(body.message || body.error || "No import result was returned."); if (response.ok) await load() }
  async function open(item) { setStatus("Loading draft review…"); const response = await adminFetch(`/api/admin/curated-lists/${item.id}`); const body = await response.json().catch(() => ({})); if (!response.ok) return setStatus(body.error); setDetail(body); setStatus(`${body.import_items.length} parsed entries require review.`) }
  async function decide(item, disposition) { const canonical = disposition === "canonical_resource" ? window.prompt("Canonical resource UUID") : null; if (disposition === "canonical_resource" && !canonical) return; const response = await adminFetch(`/api/admin/list-import-items/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ final_disposition: disposition, selected_canonical_resource_id: canonical, administrator_corrections: {} }) }); const body = await response.json().catch(() => ({})); setStatus(body.error || `Saved ${disposition}.`); if (response.ok) await open(detail.list) }
  async function commitDraft() { const response = await adminFetch(`/api/admin/curated-lists/${detail.list.id}/commit-import`, { method: "POST" }); const body = await response.json().catch(() => ({})); setStatus(body.error || `Structured draft committed: ${body.structured_items} items and ${body.section_placements} placements. Nothing was published.`); if (response.ok) await open(detail.list) }
  return <section className="admin-review-panel curated-list-manager"><div className="results-head"><div><p className="eyebrow">Administrator only</p><h2>Import Pre-made List</h2></div></div><p role="status">{status}</p><form className="curated-list-upload" onSubmit={upload}><label>List title<input value={title} onChange={(event) => setTitle(event.target.value)} required/></label><label>Slug<input value={slug} onChange={(event) => setSlug(event.target.value)} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"/></label><label>Private DOCX source<input name="source" type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required/></label><button type="submit">Parse into private draft</button></form><div className="premade-list-grid">{lists.map((item) => <article className="premade-list-card" key={item.id}><h3>{item.title}</h3><p>Status: {item.status}</p><button onClick={() => open(item)}>Review draft</button></article>)}</div>{detail ? <div className="curated-import-review"><div className="results-head"><h3>{detail.list.title}: parsed entries</h3><button onClick={commitDraft}>Commit reviewed entries to structured draft</button></div>{detail.import_items.map((item) => <article className="evidence-card" key={item.id}><h4>{item.parsed_name || "Needs identification"}</h4><p>{item.detected_section} · {item.match_confidence} · {item.review_status}</p><details><summary>Original document text and warnings</summary><pre>{item.raw_source_text}</pre><ul>{item.validation_warnings?.map((warning) => <li key={warning.code}>{warning.message}</li>)}</ul></details>{item.proposed_matches?.length ? <details><summary>{item.proposed_matches.length} proposed canonical match(es)</summary><ul>{item.proposed_matches.map((match) => <li key={match.canonical_resource_id}>{match.name} — {match.classification}</li>)}</ul></details> : null}<div className="pending-actions"><button onClick={() => decide(item, "list_only_entry")}>Keep as list-only</button><button onClick={() => decide(item, "canonical_resource")}>Attach canonical</button><button onClick={() => decide(item, "skip")}>Skip</button></div></article>)}</div> : null}</section>
}
