import { useCallback, useEffect, useState } from "react"
import { adminFetch } from "../adminApi.js"
const readable = (value) => String(value || "unknown").replaceAll("_", " ")
export default function GrowthTrends() {
  const [report, setReport] = useState(null), [error, setError] = useState("")
  const load = useCallback(async () => { try { const response = await adminFetch("/api/admin/growth-trends"), body = await response.json().catch(() => ({})); if (!response.ok) return setError(body.error || "Growth and trends are unavailable."); setReport(body) } catch { setError("Growth and trends are unavailable.") } }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  return <section className="admin-review-panel growth-trends" aria-labelledby="growth-trends-title"><div className="results-head"><div><p className="eyebrow">Administrator only · planning only</p><h2 id="growth-trends-title">Growth &amp; Trends</h2></div></div>{error ? <p role="alert">{error}</p> : !report ? <p role="status">Planning growth and reviewing observations…</p> : <><p>Opportunities and trends recommend human attention only. They cannot add resources, change policy, or publish map locations.</p><p><strong>Projected pace:</strong> {report.projection.investigations_per_month} investigations/month; about {report.projection.estimated_verified_additions_per_year} verified additions/year at the configured illustrative rate.</p>{report.growth_opportunities.length ? <div className="evidence-cards">{report.growth_opportunities.slice(0, 5).map((item) => <article className="evidence-card" key={item.opportunity_id}><p><strong>{item.geographic_scope || "Directory"} · value {item.value_score}</strong></p><p>{item.explanation}</p><p><strong>Blockers:</strong> {item.blockers.join(", ") || "none"}</p></article>)}</div> : <p>No bounded growth opportunity is currently identified.</p>}{report.trends.length ? <div className="evidence-cards">{report.trends.slice(0, 5).map((item) => <article className="evidence-card" key={item.id || item.observation_fingerprint}><p><strong>{readable(item.attention)} · {readable(item.trend_category)}</strong></p><p>{item.summary}</p><p><strong>Suggested response:</strong> {readable(item.recommended_response)}</p></article>)}</div> : <p>No persisted trend observations yet.</p>}</>}</section>
}
