import { useCallback, useEffect, useState } from "react"
import { adminFetch } from "../adminApi.js"
const readable = (value) => String(value || "unknown").replaceAll("_", " ")
export default function GrowthTrends() {
  const [report, setReport] = useState(null), [error, setError] = useState(""), [running, setRunning] = useState(false), [message, setMessage] = useState("")
  const load = useCallback(async () => { try { const response = await adminFetch("/api/admin/growth-trends"), body = await response.json().catch(() => ({})); if (!response.ok) return setError(body.error || "Growth and trends are unavailable."); setReport(body) } catch { setError("Growth and trends are unavailable.") } }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  const inspect = async () => {
    if (!window.confirm("Inspect the fixed trusted-source allowlist now? This records observations only; it cannot change resources, start research, or publish locations.")) return
    setRunning(true); setMessage("")
    try { const response = await adminFetch("/api/admin/growth-trends/inspect", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirm: true }) }), body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Trend inspection could not complete."); setMessage(`Inspection complete: ${body.new_observations} new observation(s), ${body.duplicates_ignored} duplicate(s) ignored.`); await load() } catch (runError) { setMessage(runError.message || "Trend inspection could not complete.") } finally { setRunning(false) }
  }
  return <section className="admin-review-panel growth-trends" aria-labelledby="growth-trends-title"><div className="results-head"><div><p className="eyebrow">Administrator only · planning only</p><h2 id="growth-trends-title">Growth &amp; Trends</h2></div></div>{error ? <p role="alert">{error}</p> : !report ? <p role="status">Planning growth and reviewing observations…</p> : <><p>Opportunities and trends recommend human attention only. They cannot add resources, change policy, or publish map locations.</p><div className="resource-review-actions"><button type="button" onClick={inspect} disabled={running}>{running ? "Inspecting…" : "Run trend inspection"}</button></div>{message ? <p role="status">{message}</p> : null}<dl className="planner-summary"><dt>Last inspection</dt><dd>{report.last_inspection?.completed_at || report.last_inspection?.started_at || "not yet run"}</dd><dt>Requests used</dt><dd>{report.last_inspection?.requests_used ?? 0}</dd><dt>New observations</dt><dd>{report.last_inspection?.new_observations ?? 0}</dd><dt>Duplicates ignored</dt><dd>{report.last_inspection?.duplicates_ignored ?? 0}</dd><dt>Stop reason</dt><dd>{readable(report.last_inspection?.stop_reason || "not yet run")}</dd></dl><p><strong>Projected pace:</strong> {report.projection.investigations_per_month} investigations/month; about {report.projection.estimated_verified_additions_per_year} verified additions/year at the configured illustrative rate.</p>{report.growth_opportunities.length ? <div className="evidence-cards">{report.growth_opportunities.slice(0, 5).map((item) => <article className="evidence-card" key={item.opportunity_id}><p><strong>{item.geographic_scope || "Directory"} · value {item.value_score}</strong></p><p>{item.explanation}</p><p><strong>Blockers:</strong> {item.blockers.join(", ") || "none"}</p></article>)}</div> : <p>No bounded growth opportunity is currently identified.</p>}{report.trends.length ? <div className="evidence-cards">{report.trends.slice(0, 5).map((item) => <article className="evidence-card" key={item.id || item.observation_fingerprint}><p><strong>{readable(item.attention)} · {readable(item.trend_category)}</strong></p><p>{item.summary}</p><p><strong>Suggested response:</strong> {readable(item.recommended_response)}</p></article>)}</div> : <p>No persisted trend observations yet.</p>}{report.curiosity_questions?.length ? <p><strong>Planning questions:</strong> {report.curiosity_questions.length} bounded, authorization-required question candidate(s).</p> : null}</>}</section>
}
