import { useCallback, useEffect, useState } from "react"
import { adminFetch } from "../adminApi.js"
const readable = (value) => String(value || "unknown").replaceAll("_", " ")
export default function Heartbeat() {
  const [report, setReport] = useState(null), [message, setMessage] = useState(""), [running, setRunning] = useState(false)
  const load = useCallback(async () => { try { const response = await adminFetch("/api/admin/heartbeat"), body = await response.json().catch(() => ({})); if (!response.ok) return setMessage(body.error || "Heartbeat is unavailable."); setReport(body) } catch { setMessage("Heartbeat is unavailable.") } }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  const run = async (mode) => { if (running || mode === "maintenance" && !window.confirm("Run one bounded maintenance cycle? It may perform limited external research for at most two existing planner tasks.")) return; setRunning(true); setMessage(""); try { const response = await adminFetch("/api/admin/heartbeat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode, confirm: mode === "maintenance" }) }), body = await response.json().catch(() => ({})); setMessage(response.ok ? `Cycle stopped: ${readable(body.stop_reason)}.` : body.error || "Heartbeat could not run."); await load() } catch { setMessage("Heartbeat could not run.") } finally { setRunning(false) } }
  return <section className="admin-review-panel heartbeat" aria-labelledby="heartbeat-title"><div className="results-head"><div><p className="eyebrow">Administrator only · bounded wake cycle</p><h2 id="heartbeat-title">Heartbeat</h2></div></div>{message ? <p role="status">{message}</p> : null}{!report ? <p role="status">Loading heartbeat status…</p> : <><p>Wake → inspect → bounded work → reassess → stop. Growth remains planning-only.</p><dl className="planner-summary"><dt>Knowledge findings</dt><dd>{report.health.summary.knowledge_findings}</dd><dt>System findings</dt><dd>{report.health.summary.security_findings}</dd><dt>Eligible maintenance tasks</dt><dd>{report.planner.tasks.filter((item) => item.actionable).length}</dd><dt>Growth opportunities</dt><dd>{report.growth_opportunities.length}</dd><dt>Last stop</dt><dd>{readable(report.last_cycle?.stop_reason || "no_cycle_yet")}</dd></dl><div className="resource-review-actions"><button type="button" onClick={() => run("inspect_only")} disabled={running}>{running ? "Running…" : "Run inspection"}</button><button type="button" onClick={() => run("maintenance")} disabled={running}>{running ? "Running…" : "Run bounded maintenance cycle"}</button></div></>}</section>
}
