import { useCallback, useEffect, useState } from "react"
import { adminFetch } from "../adminApi.js"

const readable = (value) => String(value || "unknown").replaceAll("_", " ")

export default function MaintenanceToolbox() {
  const [data, setData] = useState(null), [heartbeat, setHeartbeat] = useState(null), [error, setError] = useState(""), [running, setRunning] = useState(false), [savingSchedule, setSavingSchedule] = useState(false)
  const load = useCallback(async () => { const [toolbox, scheduler] = await Promise.all([adminFetch("/api/admin/maintenance-toolbox"), adminFetch("/api/admin/maintenance-scheduler")]); const [toolboxBody, schedulerBody] = await Promise.all([toolbox.json(), scheduler.json()]); if (!toolbox.ok) throw new Error(toolboxBody.error); if (!scheduler.ok) throw new Error(schedulerBody.error); setData(toolboxBody); setHeartbeat(schedulerBody) }, [])
  useEffect(() => { let active = true; load().catch((reason) => { if (active) setError(reason.message || "Maintenance state is unavailable.") }); return () => { active = false } }, [load])
  const runNow = async () => { if (!window.confirm("Run one bounded maintenance cycle now? It will use the current dry-run or active configuration.")) return; setRunning(true); setError(""); try { const response = await adminFetch("/api/admin/maintenance-scheduler/run", { method: "POST", body: JSON.stringify({ confirm: true }) }), body = await response.json(); if (!response.ok) throw new Error(body.error); await load() } catch (reason) { setError(reason.message || "Maintenance cycle could not start.") } finally { setRunning(false) } }
  const saveSchedule = async (event) => { event.preventDefault(); if (!heartbeat || !window.confirm("Save this scheduler configuration? Scheduling remains disabled unless selected below.")) return; const form = new FormData(event.currentTarget); setSavingSchedule(true); setError(""); try { const response = await adminFetch("/api/admin/maintenance-scheduler/config", { method: "POST", body: JSON.stringify({ enabled: form.get("enabled") === "on", execution_mode: form.get("execution_mode"), cadence_hours: Number(form.get("cadence_hours")), display_timezone: heartbeat.config.display_timezone, version: heartbeat.config.version, confirm: true }) }), body = await response.json(); if (!response.ok) throw new Error(body.error); await load() } catch (reason) { setError(reason.message || "Scheduler configuration could not be saved.") } finally { setSavingSchedule(false) } }
  return <section className="admin-review-panel" aria-labelledby="maintenance-toolbox-title">
    <p className="eyebrow">Administrator only · manual and bounded</p><h2 id="maintenance-toolbox-title">Maintenance &amp; Growth</h2>
    {error ? <p role="alert">{error}</p> : !data ? <p role="status">Loading maintenance state…</p> : <>
      <p>Safe repair uses complete trusted evidence. Missing evidence becomes a research recommendation, never a guessed change.</p>
      {heartbeat && <section aria-labelledby="maintenance-heartbeat-title"><h3 id="maintenance-heartbeat-title">Heartbeat / Recent Cycles</h3><dl className="planner-summary"><dt>Scheduler</dt><dd>{heartbeat.config.enabled ? "enabled" : "disabled"}</dd><dt>Mode</dt><dd>{readable(heartbeat.config.execution_mode)}</dd><dt>Cadence</dt><dd>Every {heartbeat.config.cadence_hours} hours</dd><dt>Next expected wake</dt><dd>{heartbeat.config.next_expected_at ? new Date(heartbeat.config.next_expected_at).toLocaleString() : "Not scheduled"}</dd><dt>Current cycle</dt><dd>{heartbeat.currently_running ? "running" : "quiet"}</dd></dl><form onSubmit={saveSchedule}><label><input name="enabled" type="checkbox" defaultChecked={heartbeat.config.enabled} /> Enable once-daily scheduling</label><label>Mode <select name="execution_mode" defaultValue={heartbeat.config.execution_mode}><option value="dry_run">Dry run / observe only</option><option value="active">Active bounded Tier-1</option></select></label><label>Cadence (hours) <input name="cadence_hours" type="number" min="24" max="168" defaultValue={heartbeat.config.cadence_hours} /></label><button type="submit" className="admin-action-button" disabled={savingSchedule}>{savingSchedule ? "Saving…" : "Save scheduler settings"}</button></form><button type="button" className="admin-action-button" onClick={runNow} disabled={running || Boolean(heartbeat.currently_running)}>{running ? "Running one cycle…" : "Run One Cycle Now"}</button><p>Uses the same server-authoritative bounded cycle as scheduled delivery. Disabled scheduling does not prevent this deliberate administrator request.</p><h4>Recent cycles</h4>{heartbeat.recent_cycles.length ? <div className="evidence-cards">{heartbeat.recent_cycles.slice(0,6).map((item) => <article className="evidence-card" key={item.id}><strong>{readable(item.status)} · {readable(item.trigger_type)}</strong><p><b>Observed:</b> {item.orientation_summary?.needs_found || 0} needs · <b>Considered:</b> {item.considered?.length || 0} actions · <b>Acted:</b> {readable(item.selected_action?.action_id || "none")} · <b>Verified:</b> {readable(item.verification?.status)}</p><p><b>Refused:</b> {item.refused?.length || 0} · {item.reflection?.status || "no reflection"}</p></article>)}</div> : <p>No cycle has been recorded yet.</p>}<h4>Previous seven days</h4><p>{heartbeat.weekly_summary.cycles_completed} completed of {heartbeat.weekly_summary.cycles_attempted} attempted; {heartbeat.weekly_summary.no_op_cycles} safe no-op cycle(s); {heartbeat.weekly_summary.tier1_actions_performed} Tier-1 action(s); {heartbeat.weekly_summary.successful_verifications} independently verified.</p></section>}
      <dl className="planner-summary"><dt>Safe repairs available</dt><dd>{data.safe_repairs_available}</dd><dt>Almost map-ready</dt><dd>{data.almost_map_ready}</dd><dt>Needs location research</dt><dd>{data.location_research}</dd><dt>Stale information</dt><dd>{data.stale_resource_information}</dd><dt>Scheduling</dt><dd>{readable(data.scheduling)}</dd></dl>
      <h3>What I repaired</h3>{data.verified_outcomes.length ? <div className="evidence-cards">{data.verified_outcomes.map((item) => <article className="evidence-card" key={item.id}><strong>{readable(item.action_id)}</strong><p>{readable(item.classification)} · independently verified</p></article>)}</div> : <p>No verified maintenance repair has been persisted yet.</p>}
      <h3>Growth opportunities</h3>{data.opportunities.length ? <div className="evidence-cards">{data.opportunities.map((item) => <article className="evidence-card" key={item.id}><strong>{readable(item.gap_type)}</strong><p>{item.reason}</p></article>)}</div> : <p>No persisted growth opportunity is currently waiting.</p>}
      <h3>Capabilities worth building</h3>{data.capability_gaps.length ? <div className="evidence-cards">{data.capability_gaps.map((item) => <article className="evidence-card" key={item.id}><strong>{readable(item.problem_class)}</strong><p>{item.suggested_direction}</p><p>Observed {item.observation_count} time(s) · {readable(item.safety_category)}</p></article>)}</div> : <p>No recurring capability gap is currently persisted.</p>}
      <h3>Security attention</h3>{data.security_attention.length ? <div className="evidence-cards">{data.security_attention.map((item) => <article className="evidence-card" key={item.id}><strong>{readable(item.finding_type)}</strong><p>{item.recommended_action}</p></article>)}</div> : <p>No active private security finding is currently waiting.</p>}
      <details><summary>Learning and ineffective work</summary><p>Learning can rank an already eligible repair, but it cannot authorize one.</p><pre>{JSON.stringify({ lessons: data.lessons, ineffective_outcomes: data.ineffective_outcomes }, null, 2)}</pre></details>
    </>}
  </section>
}
