import { useEffect, useState } from "react"
import { adminFetch } from "../adminApi.js"

const displayValue = (value, fallback) => value === null || value === undefined || value === "" ? fallback : typeof value === "string" ? value : JSON.stringify(value)

export default function MillerReviewQueue() {
  const [report, setReport] = useState(null), [error, setError] = useState(""), [status, setStatus] = useState(""), [view, setView] = useState("needs_review")
  const load = async () => {
    setError("")
    try { const response = await adminFetch("/api/admin/intelligence-shadow"), body = await response.json().catch(() => ({})); if (!response.ok) setError(body.error || "Shadow review is unavailable."); else setReport(body) }
    catch { setError("Shadow review is unavailable.") }
  }
  useEffect(() => { let active = true; adminFetch("/api/admin/intelligence-shadow").then(async (response) => { const body = await response.json().catch(() => ({})); if (!active) return; if (!response.ok) setError(body.error || "Shadow review is unavailable."); else setReport(body) }).catch(() => active && setError("Shadow review is unavailable.")); return () => { active = false } }, [])
  const decide = async (item, action) => {
    setStatus("Saving shadow decision…")
    const response = await adminFetch(`/api/admin/intelligence-shadow/${item.id}/decision`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expected_version: item.version, action }) })
    const body = await response.json().catch(() => ({}))
    setStatus(response.ok ? "Decision recorded in shadow audit history. Nothing was published." : body.error || "Decision could not be saved.")
    if (response.ok) await load()
  }
  const items = view === "needs_review" ? report?.needsReview || [] : report?.handledByMiller || []
  return <section className="admin-review-panel miller-review-queue" aria-labelledby="miller-review-title"><div className="results-head"><div><p className="eyebrow">Protected · durable shadow mode</p><h2 id="miller-review-title">Miller needs your review</h2></div></div>{error ? <p role="alert">{error}</p> : !report ? <p role="status">Loading shadow recommendations…</p> : <><p>{report.summary}</p><p className="shadow-metrics">Handled before review: {report.metrics.handled_by_miller} · Human judgment: {report.metrics.human_judgment_required} · External research still needed: {report.metrics.administrator_external_research_required}</p><div className="review-tabs" role="tablist"><button type="button" aria-selected={view === "needs_review"} onClick={() => setView("needs_review")}>Needs review ({report.needsReview.length})</button><button type="button" aria-selected={view === "handled"} onClick={() => setView("handled")}>Handled by Miller ({report.handledByMiller.length})</button></div>{items.length ? <div className="evidence-cards">{items.map((item) => <article className="evidence-card" key={item.id}><div><h3>{item.question}</h3><p><strong>What Miller found:</strong> {item.finding}</p><p><strong>{view === "needs_review" ? "Why Miller needs you:" : "Why this was routine:"}</strong> {(item.reasonCodes.length ? item.reasonCodes : ["bounded evidence recorded"]).join(", ").replaceAll("_", " ")}</p><p><strong>Current:</strong> {displayValue(item.currentValue, "Unknown / unmapped")}<br/><strong>Proposed:</strong> {displayValue(item.proposedValue, "Keep unknown / unmapped")}</p>{item.evidence.length ? <details><summary>Evidence ({item.evidence.length})</summary><ul>{item.evidence.map((evidence, index) => <li key={`${evidence.sourceUrl}-${index}`}><strong>{evidence.sourceType.replaceAll("_", " ")}</strong>{evidence.sourceUrl ? <> · <a href={evidence.sourceUrl} target="_blank" rel="noreferrer">Open source</a></> : null}<br/><small>Retrieved {evidence.retrievedAt ? new Date(evidence.retrievedAt).toLocaleString() : "unknown"} · authority {evidence.authority}</small></li>)}</ul></details> : <p>No usable source was found; external research is still required.</p>}{view === "needs_review" ? <div className="pending-actions" aria-label="Shadow decision actions"><button type="button" onClick={() => decide(item, "accept")}>Approve suggestion</button><button type="button" onClick={() => decide(item, "keep_existing")}>Keep existing / unmapped</button><button type="button" onClick={() => decide(item, "reject")}>Reject</button><button type="button" onClick={() => decide(item, "mark_unknown")}>Mark unknown</button></div> : null}</div></article>)}</div> : <p>No items in this view.</p>}<p role="status">{status}</p><small>{report.persistenceNote}</small></>}</section>
}
