import { useCallback, useEffect, useState } from "react"
import { adminFetch } from "../adminApi.js"
const readable = (value) => String(value || "unknown").replaceAll("_", " ")
const display = (value, fallback) => value === null || value === undefined || value === "" ? fallback : typeof value === "string" ? value : JSON.stringify(value)
export default function MillerReviewQueue() {
  const [report, setReport] = useState(null), [error, setError] = useState(""), [status, setStatus] = useState(""), [view, setView] = useState("needs_review"), [saving, setSaving] = useState("")
  const load = useCallback(async () => { setError(""); try { const response = await adminFetch("/api/admin/intelligence-shadow"), body = await response.json().catch(() => ({})); if (!response.ok) setError(body.error || "Review recommendations are unavailable."); else setReport(body) } catch { setError("Review recommendations are unavailable.") } }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  async function decide(item, action) { if (saving) return; setSaving(item.id); setStatus("Saving evidence decision…"); const response = await adminFetch(`/api/admin/intelligence-shadow/${item.id}/decision`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expected_version: item.version, action }) }); const body = await response.json().catch(() => ({})); setSaving(""); if (!response.ok) return setStatus(body.error || "Evidence decision was not saved. Reload and try again."); setStatus("Evidence decision saved to the private audit. No directory resource, location, or map pin changed."); await load() }
  const items = view === "needs_review" ? report?.needsReview || [] : report?.handledByMiller || []
  return <section className="admin-review-panel miller-review-queue" aria-labelledby="miller-review-title"><div className="results-head"><div><p className="eyebrow">Administrator only · evidence review</p><h2 id="miller-review-title">Miller needs your review</h2></div></div>{error ? <p role="alert">{error}</p> : !report ? <p role="status">Loading evidence recommendations…</p> : <><p>{report.needsReview.length} evidence decisions are ready. They are not directory or map approvals.</p><div className="review-tabs" role="tablist"><button aria-selected={view === "needs_review"} onClick={() => setView("needs_review")}>Ready for evidence decision ({report.needsReview.length})</button><button aria-selected={view === "handled"} onClick={() => setView("handled")}>Handled by Miller · evidence history ({report.handledByMiller.length})</button></div>{items.length ? <div className="evidence-cards">{items.map((item) => <article className="evidence-card" key={item.id}><div><h3>{item.question}</h3><p><strong>Miller recommendation:</strong> {readable(item.recommendation)}</p><p><strong>Why:</strong> {item.finding}</p><p><strong>Current:</strong> {display(item.currentValue, "Unknown")}<br/><strong>Proposed:</strong> {display(item.proposedValue, "No replacement proposed")}</p><p><strong>This action will:</strong> record an evidence judgment in a private, append-only audit.<br/><strong>This action will not:</strong> approve a directory resource, create a location, or publish a map pin.</p><details><summary>Evidence and technical details ({item.evidence.length})</summary><p>Reasons: {item.reasonCodes.map(readable).join(", ") || "bounded evidence recorded"}</p>{item.evidence.map((evidence, index) => <p key={`${evidence.sourceUrl}-${index}`}><strong>{readable(evidence.sourceType)}</strong>{evidence.sourceUrl ? <> · <a href={evidence.sourceUrl} target="_blank" rel="noreferrer">Open source</a></> : null}</p>)}</details>{view === "needs_review" ? <div className="pending-actions"><button disabled={Boolean(saving)} onClick={() => decide(item, "accept")}>{saving === item.id ? "Saving…" : "Approve suggestion — accept evidence"}</button><button disabled={Boolean(saving)} onClick={() => decide(item, "keep_existing")}>Keep current value</button><button disabled={Boolean(saving)} onClick={() => decide(item, "reject")}>Reject recommendation</button><button disabled={Boolean(saving)} onClick={() => decide(item, "mark_unknown")}>Mark unknown</button></div> : null}</div></article>)}</div> : <p>No items in this view.</p>}<p role="status">{status}</p><small>{report.persistenceNote}</small></>}</section>
}
