import { useCallback, useEffect, useState } from "react"
import { adminFetch } from "../adminApi.js"
const labels = { tier_a_bulk_confirmable: "Bulk-confirmable preview", tier_b_one_click_review: "One-click review", tier_c_reconciliation: "Reconciliation required", tier_d_research: "Research required", tier_e_safety_sensitive: "Safety-sensitive directory review" }
const action = { tier_a_bulk_confirmable: "Inspect for administrator bulk confirmation", tier_b_one_click_review: "Approve directory resource", tier_c_reconciliation: "Resolve identity relationship", tier_d_research: "Research before deciding", tier_e_safety_sensitive: "Approve directory separately from address handling" }
export default function ShelterThroughputQueue() {
  const [report, setReport] = useState(null), [status, setStatus] = useState("Loading shelter action queue…")
  const load = useCallback(async () => { const response = await adminFetch("/api/admin/shelter-throughput"), body = await response.json().catch(() => ({})); if (!response.ok) return setStatus(body.error || "Shelter action queue is unavailable."); setReport(body); setStatus(`${Object.values(body.counts).reduce((sum, value) => sum + value, 0)} pending candidates classified. No automatic approval or map publication is enabled.`) }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  const priority = ["tier_a_bulk_confirmable", "tier_b_one_click_review", "tier_c_reconciliation", "tier_e_safety_sensitive"]
  return <section className="address-evidence" aria-labelledby="shelter-throughput-title"><header><p className="eyebrow">Administrator only · action queue</p><h2 id="shelter-throughput-title">Ready for your decision</h2><p role="status">{status}</p></header>{report ? <><div className="resolution-summary">{Object.entries(report.counts).map(([key, count]) => <div key={key}><strong>{count}</strong><span>{labels[key]}</span></div>)}</div>{priority.flatMap((tier) => report[tier].slice(0, 12).map((item) => <article className="evidence-card" key={`${tier}:${item.id}`}><h3>{item.name}</h3><p>{[item.operator, item.shelter_type, item.community].filter(Boolean).join(" · ")}</p><p><strong>Miller recommendation:</strong> {labels[tier]}</p><p><strong>Why:</strong> {item.reason_codes.join(", ").replaceAll("_", " ")}</p><p><strong>Available next action:</strong> {action[tier]}<br/><strong>It will not:</strong> create a location or publish a map pin.</p>{item.source_url ? <a href={item.source_url} target="_blank" rel="noreferrer">Open strongest evidence</a> : null}</article>))}</> : null}</section>
}
