import { useCallback, useEffect, useState } from "react"
import { adminFetch } from "../adminApi.js"
export default function ShelterReconciliationReview() {
  const [queue, setQueue] = useState({ pairs: [], clusters: [] }), [status, setStatus] = useState("Loading possible duplicate shelters…"), [busy, setBusy] = useState("")
  const load = useCallback(async () => { const response = await adminFetch("/api/admin/shelter-reconciliations"); const body = await response.json().catch(() => ({})); if (!response.ok) return setStatus(body.error || "The reconciliation queue is unavailable."); setQueue(body); setStatus(`${body.pairs.length} related pairs in ${body.clusters.length} cluster(s). Decisions never approve, close, merge, publish, or map a shelter.`) }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  async function decide(pair, decision) { const key = `${pair.left.id}:${pair.right.id}`; if (busy || !window.confirm(`Record “${decision.replaceAll("_", " ")}"? This only writes the reconciliation ledger.`)) return; setBusy(key); const response = await adminFetch(`/api/admin/shelter-reconciliations/${pair.left.id}/${pair.right.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision, expected_version: pair.ledger?.version || 0 }) }); const body = await response.json().catch(() => ({})); setBusy(""); setStatus(response.ok ? "Reconciliation saved. No candidate, resource, location, or map state changed." : body.error || "Decision was not saved."); if (response.ok) load() }
  const detail = (item) => <><strong>{item.name}</strong><br/>{[item.operator, item.shelter_type, item.population_served, item.community, item.region].filter(Boolean).join(" · ")}<br/>{item.phone || "No phone"}{item.public_address ? ` · ${item.public_address}` : ""}<br/><a href={item.source_url || item.website} target="_blank" rel="noreferrer">Source evidence</a></>
  return <section className="address-evidence" aria-labelledby="shelter-reconciliation-title"><header><p className="eyebrow">Administrator only · identity review</p><h2 id="shelter-reconciliation-title">Possible duplicate shelters</h2><p role="status">{status}</p></header>{queue.pairs.map((pair) => <article className="evidence-card" key={`${pair.left.id}:${pair.right.id}`}><div><h3>{pair.comparison.classification.replaceAll("_", " ")}</h3><p><strong>Why related:</strong> {pair.comparison.reasons.join(", ") || "source match"}</p><p>{detail(pair.left)}</p><p>{detail(pair.right)}</p><div className="pending-actions"><button disabled={Boolean(busy)} onClick={() => decide(pair, "same_program_duplicate")}>Same program / duplicate</button><button disabled={Boolean(busy)} onClick={() => decide(pair, "different_program")}>Different programs</button><button disabled={Boolean(busy)} onClick={() => decide(pair, "needs_more_research")}>Needs more research</button></div>{pair.ledger ? <p>Ledger: {pair.ledger.decision.replaceAll("_", " ")} (revision {pair.ledger.version})</p> : null}</div></article>)}</section>
}
