import { useCallback, useEffect, useState } from "react"
import { adminFetch } from "../adminApi.js"

const readable = (value) => String(value || "unknown").replaceAll("_", " ")
export default function SystemHealth() {
  const [report, setReport] = useState(null), [error, setError] = useState("")
  const load = useCallback(async () => { try { const response = await adminFetch("/api/admin/system-health"), body = await response.json().catch(() => ({})); if (!response.ok) return setError(body.error || "System health is unavailable."); setReport(body); setError("") } catch { setError("System health is unavailable.") } }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  return <section className="admin-review-panel system-health" aria-labelledby="system-health-title"><div className="results-head"><div><p className="eyebrow">Administrator only · read-only</p><h2 id="system-health-title">System Health</h2></div></div>{error ? <p role="alert">{error}</p> : !report ? <p role="status">Checking knowledge and protective controls…</p> : <><p>Knowledge and system findings are deterministic diagnostics. No attachment contents, credentials, or secret configuration values are shown.</p><dl className="planner-summary"><dt>Knowledge findings</dt><dd>{report.summary.knowledge_findings}</dd><dt>System findings</dt><dd>{report.summary.security_findings}</dd><dt>High severity</dt><dd>{report.summary.high_severity_findings}</dd><dt>Quarantine backlog</dt><dd>{report.summary.quarantine_backlog}</dd><dt>Failed scans</dt><dd>{report.summary.failed_scans}</dd><dt>Malicious detections</dt><dd>{report.summary.malicious_detections}</dd></dl>{report.findings.length ? <div className="evidence-cards">{report.findings.slice(0, 20).map((item) => <article className="evidence-card" key={item.finding_id}><p><strong>{readable(item.domain)} · {readable(item.severity)}</strong></p><p>{item.explanation}</p><p><strong>Recommendation:</strong> {readable(item.recommendation)}</p></article>)}</div> : <p>No knowledge or system exceptions were identified in this bounded diagnostic sample.</p>}</>}</section>
}
