begin;

create table if not exists public.ai_resource_reviews (
  id bigint generated by default as identity primary key,
  resource_id bigint not null references public.tavily_resources(id) on delete cascade,
  status text not null check (status in ('queued', 'running', 'completed', 'failed')),
  review_recommendation text check (review_recommendation in ('approve', 'reject', 'manual_review')),
  review_confidence double precision check (review_confidence between 0 and 1),
  review_reason text,
  review_results jsonb,
  suggested_tags jsonb,
  duplicate_candidates jsonb,
  quality_results jsonb,
  agent_errors jsonb not null default '{}'::jsonb,
  model_identifier text,
  schema_version text not null,
  error_message text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  reviewed_by_human_at timestamptz,
  human_decision text check (human_decision in ('approved', 'hidden', 'left_pending'))
);

create index if not exists ai_resource_reviews_resource_created_idx
  on public.ai_resource_reviews (resource_id, created_at desc);

create unique index if not exists ai_resource_reviews_one_running_idx
  on public.ai_resource_reviews (resource_id)
  where status in ('queued', 'running');

alter table public.ai_resource_reviews enable row level security;

-- Intentionally no anon/authenticated policies. The Express backend uses service_role.
revoke all on table public.ai_resource_reviews from anon, authenticated;

commit;
