begin;
create table public.map_auto_publication_runs (
 id uuid primary key, operation text not null check(operation='map_auto_publish_v1_execution'), project_ref text not null check(project_ref='wccagykzugrahwugefqt'), policy_version text not null check(policy_version='map_auto_publish_v1'), authorized_max_successes integer not null check(authorized_max_successes between 1 and 23), attempted_count integer not null default 0 check(attempted_count>=0), successful_count integer not null default 0 check(successful_count>=0 and successful_count<=authorized_max_successes), failed_count integer not null default 0 check(failed_count>=0), status text not null default 'running' check(status in ('running','completed','stopped')), machine_actor text not null default 'miller_map_automation', actor_id uuid references auth.users(id), created_at timestamptz not null default now(), resumed_at timestamptz, completed_at timestamptz
);
create table public.map_auto_publication_execution_provenance (
 id uuid primary key default gen_random_uuid(), run_id uuid not null references public.map_auto_publication_runs(id) on delete restrict, resource_id uuid not null references public.resource_registry(id), location_id uuid references public.resource_locations(id), qc_version integer not null, occupancy_claim_id uuid not null references public.resource_fact_claims(id), geocoder_evidence_id uuid not null references public.resource_fact_evidence(id), policy_version text not null check(policy_version='map_auto_publish_v1'), outcome text not null check(outcome in ('published','idempotent','refused','failed')), reason_code text not null, machine_actor text not null default 'miller_map_automation', created_at timestamptz not null default now(), unique(run_id,resource_id)
);
alter table public.map_auto_publication_runs enable row level security; alter table public.map_auto_publication_execution_provenance enable row level security;
revoke all on public.map_auto_publication_runs,public.map_auto_publication_execution_provenance from public,anon,authenticated;
grant select,insert,update on public.map_auto_publication_runs,public.map_auto_publication_execution_provenance to service_role;

create or replace function public.begin_map_auto_publication_run(p_run_id uuid,p_authorized_max_successes integer,p_actor_id uuid) returns public.map_auto_publication_runs language plpgsql security definer set search_path=public as $$ declare v public.map_auto_publication_runs; begin
 if p_authorized_max_successes not between 1 and 23 then raise exception 'automatic publication cap must be between 1 and 23'; end if;
 select * into v from public.map_auto_publication_runs where id=p_run_id for update;
 if found then if v.project_ref<>'wccagykzugrahwugefqt' or v.policy_version<>'map_auto_publish_v1' or v.authorized_max_successes<>p_authorized_max_successes then raise exception 'publication run binding mismatch'; end if; if v.status<>'running' then raise exception 'publication run is not resumable'; end if; update public.map_auto_publication_runs set resumed_at=now() where id=p_run_id returning * into v; return v; end if;
 insert into public.map_auto_publication_runs(id,operation,project_ref,policy_version,authorized_max_successes,actor_id) values(p_run_id,'map_auto_publish_v1_execution','wccagykzugrahwugefqt','map_auto_publish_v1',p_authorized_max_successes,p_actor_id) returning * into v; return v; end $$;

create or replace function public.publish_map_location_v1(p_resource_id uuid,p_expected_qc_version integer,p_occupancy_claim_id uuid,p_geocoder_evidence_id uuid,p_run_id uuid,p_actor_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_run public.map_auto_publication_runs; v_existing public.map_auto_publication_execution_provenance; v_geo public.resource_fact_evidence; v_result jsonb; v_snapshot jsonb; v_location public.resource_locations; v_new public.resource_locations;
begin
 perform pg_advisory_xact_lock(hashtextextended(p_resource_id::text,4)); select * into v_run from public.map_auto_publication_runs where id=p_run_id for update;
 if not found or v_run.status<>'running' then raise exception 'publication run is not resumable'; end if;
 select * into v_existing from public.map_auto_publication_execution_provenance where run_id=p_run_id and resource_id=p_resource_id for update;
 if found and v_existing.outcome in ('published','idempotent') then return jsonb_build_object('outcome','idempotent','reason_code',v_existing.reason_code,'location_id',v_existing.location_id); end if;
 if v_run.successful_count>=v_run.authorized_max_successes then return jsonb_build_object('outcome','refused','reason_code','authorized_success_cap_reached'); end if;
 select * into v_geo from public.resource_fact_evidence e join public.resource_fact_claims c on c.id=e.claim_id where e.id=p_geocoder_evidence_id and c.id=p_occupancy_claim_id and c.resource_id=p_resource_id and e.source_type='bc_geocoder' and e.stale is not true;
 if not found then return jsonb_build_object('outcome','refused','reason_code','geocoder_evidence_not_bound'); end if;
 if coalesce((v_geo.extracted_value->>'score')::numeric,0)<>100 or lower(coalesce(v_geo.extracted_value->>'location_descriptor',''))<>'parcelpoint' or coalesce((v_geo.extracted_value->>'municipality_match')::boolean,false) is not true or upper(coalesce(v_geo.extracted_value->>'province',''))<>'BC' then return jsonb_build_object('outcome','refused','reason_code','weak_or_invalid_geocode'); end if;
 v_result:=public.classify_map_auto_publish_v1(p_resource_id,p_expected_qc_version,p_occupancy_claim_id);
 if v_result->>'decision'<>'auto_publish_eligible' then insert into public.map_auto_publication_execution_provenance(run_id,resource_id,qc_version,occupancy_claim_id,geocoder_evidence_id,policy_version,outcome,reason_code) values(p_run_id,p_resource_id,p_expected_qc_version,p_occupancy_claim_id,p_geocoder_evidence_id,'map_auto_publish_v1','refused',v_result->>'reason_code') on conflict(run_id,resource_id) do update set outcome='refused',reason_code=excluded.reason_code; return jsonb_build_object('outcome','refused','reason_code',v_result->>'reason_code'); end if;
 v_snapshot:=v_result->'review_snapshot'; if exists(select 1 from public.resource_locations where resource_id=p_resource_id and public_map and review_status='approved') then return jsonb_build_object('outcome','refused','reason_code','existing_human_location'); end if;
 select * into v_location from public.resource_locations where resource_id=p_resource_id and location_type='fixed' and street_address=v_snapshot->>'submitted_address' for update;
 if found then update public.resource_locations set latitude=(v_snapshot->'coordinates'->>'latitude')::double precision,longitude=(v_snapshot->'coordinates'->>'longitude')::double precision,geocode_source='bc_address_geocoder',geocode_status='verified',review_status='approved',public_map=true,reviewed_by=p_actor_id,reviewed_at=now(),location_last_verified=now(),updated_at=now() where id=v_location.id returning * into v_new;
 else insert into public.resource_locations(resource_id,location_label,location_type,original_address_text,street_address,city,province,country,latitude,longitude,geocode_source,geocode_confidence,geocode_status,review_status,public_map,reviewed_by,reviewed_at,location_last_verified) values(p_resource_id,'Automatically published verified location','fixed',v_snapshot->>'submitted_address',v_snapshot->>'submitted_address',v_snapshot->>'locality','BC','Canada',(v_snapshot->'coordinates'->>'latitude')::double precision,(v_snapshot->'coordinates'->>'longitude')::double precision,'bc_address_geocoder',1,'verified','approved',true,p_actor_id,now(),now()) returning * into v_new; end if;
 insert into public.resource_location_audit(location_id,action,previous_values,new_values,actor_id,reason) values(v_new.id,'publication_changed',to_jsonb(v_location),to_jsonb(v_new),p_actor_id,'Automatic map_auto_publish_v1 publication.');
 insert into public.map_auto_publication_execution_provenance(run_id,resource_id,location_id,qc_version,occupancy_claim_id,geocoder_evidence_id,policy_version,outcome,reason_code) values(p_run_id,p_resource_id,v_new.id,p_expected_qc_version,p_occupancy_claim_id,p_geocoder_evidence_id,'map_auto_publish_v1','published','auto_publish_exact_trusted_address') on conflict(run_id,resource_id) do nothing;
 update public.map_auto_publication_runs set attempted_count=attempted_count+1,successful_count=successful_count+1 where id=p_run_id; return jsonb_build_object('outcome','published','reason_code','auto_publish_exact_trusted_address','location_id',v_new.id);
end $$;
revoke all on function public.begin_map_auto_publication_run(uuid,integer,uuid),public.publish_map_location_v1(uuid,integer,uuid,uuid,uuid,uuid) from public,anon,authenticated;
grant execute on function public.begin_map_auto_publication_run(uuid,integer,uuid),public.publish_map_location_v1(uuid,integer,uuid,uuid,uuid,uuid) to service_role;
commit;
