begin;

create table if not exists public.resource_discovery_candidates (
  id bigint generated by default as identity primary key,
  source_fingerprint text not null unique,
  candidate_type text not null default 'shelter',
  name text not null,
  operator text,
  shelter_type text,
  population_served text,
  gender_eligibility text,
  age_eligibility text,
  community text,
  region text,
  health_authority text,
  public_address text,
  location_disclosure_status text not null check (location_disclosure_status in ('public','confidential','undisclosed')),
  phone text, crisis_line text, email text, website text,
  intake_process text, hours_or_dates text, accessibility text,
  pets_policy text, couples_policy text, substance_use_rules text,
  managed_alcohol_program text not null default 'unknown' check (managed_alcohol_program in ('yes','no','unknown','not_stated')),
  indigenous_specific text not null default 'unknown' check (indigenous_specific in ('yes','no','unknown')),
  capacity text,
  source_url text not null, source_name text, retrieved_title text, source_excerpt text,
  additional_sources jsonb not null default '[]'::jsonb,
  checked_at timestamptz not null,
  evidence_notes text,
  confidence text not null check (confidence in ('high','medium','low')),
  review_status text not null default 'pending' check (review_status in ('pending','approved','rejected','excluded','deferred','merged','import_failed')),
  geocoding_status text not null check (geocoding_status in ('not_requested','awaiting_authorized_geocoder')),
  possible_matches jsonb not null default '[]'::jsonb,
  matched_resource_id uuid references public.resource_registry(id),
  imported_tavily_resource_id bigint references public.tavily_resources(id),
  reviewed_by uuid references auth.users(id), reviewed_at timestamptz,
  last_error text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check (location_disclosure_status = 'public' or coalesce(public_address, '') = '')
);
create index if not exists resource_discovery_review_idx on public.resource_discovery_candidates(review_status, created_at desc);
create index if not exists resource_discovery_filters_idx on public.resource_discovery_candidates(region, community, shelter_type, confidence);
alter table public.resource_discovery_candidates enable row level security;
revoke all on table public.resource_discovery_candidates from anon, authenticated;

commit;
