begin;

create table if not exists public.resource_geography (
  id bigint generated by default as identity primary key,
  resource_id bigint not null references public.tavily_resources(id) on delete cascade,
  original_address_text text,
  street_address text,
  city text,
  province text not null default 'BC',
  postal_code text,
  latitude double precision check (latitude between -90 and 90),
  longitude double precision check (longitude between -180 and 180),
  geocode_source text,
  geocode_confidence double precision check (geocode_confidence between 0 and 1),
  geographic_region text,
  service_area text,
  virtual_service boolean not null default false,
  mobile_service boolean not null default false,
  public_map boolean not null default true,
  geocode_status text not null default 'needs_review' check (geocode_status in ('geocoded','verified','approximate','failed','needs_review')),
  location_last_verified timestamptz,
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(resource_id)
);

create table if not exists public.geocode_runs (
  id bigint generated by default as identity primary key,
  provider text not null,
  cache_key text not null,
  status text not null check (status in ('success','failed','skipped')),
  response_summary jsonb,
  error_summary text,
  created_at timestamptz not null default now()
);

create index if not exists resource_geography_public_coordinates_idx on public.resource_geography (public_map, latitude, longitude) where latitude is not null and longitude is not null;
create index if not exists resource_geography_city_idx on public.resource_geography (lower(city));
create unique index if not exists geocode_runs_success_cache_idx on public.geocode_runs (cache_key) where status = 'success';

alter table public.resource_geography enable row level security;
alter table public.geocode_runs enable row level security;
revoke all on table public.resource_geography, public.geocode_runs from anon, authenticated;

-- Public map reads go through the approved-only Express endpoint. Admin writes use
-- the service role after a verified Supabase admin session.
commit;
