begin;

create extension if not exists pgcrypto;

create table if not exists public.resource_registry (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  lifecycle_state text not null default 'active' check (lifecycle_state in ('active','merged','retired')),
  editorial_status text not null default 'pending' check (editorial_status in ('pending','approved','hidden')),
  merged_into_id uuid references public.resource_registry(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((lifecycle_state = 'merged') = (merged_into_id is not null)),
  check (merged_into_id is null or merged_into_id <> id)
);

create table if not exists public.resource_source_aliases (
  id bigint generated by default as identity primary key,
  resource_id uuid not null references public.resource_registry(id) on delete cascade,
  source_type text not null check (source_type in ('curated_bundle','tavily_resource','manual','import')),
  source_native_id text not null,
  source_url text,
  source_fingerprint text,
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_type, source_native_id)
);

create unique index if not exists resource_source_alias_fingerprint_idx
  on public.resource_source_aliases (source_type, source_fingerprint)
  where source_fingerprint is not null;
create index if not exists resource_source_alias_resource_idx on public.resource_source_aliases (resource_id);

create table if not exists public.resource_match_candidates (
  id bigint generated by default as identity primary key,
  left_source_type text not null,
  left_source_native_id text not null,
  right_source_type text not null,
  right_source_native_id text not null,
  classification text not null check (classification in ('high_confidence','possible','likely_distinct','insufficient')),
  evidence jsonb not null default '{}'::jsonb,
  decision text not null default 'pending' check (decision in ('pending','same_resource','keep_separate','defer')),
  decided_by uuid references auth.users(id),
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (left_source_type, left_source_native_id, right_source_type, right_source_native_id),
  check ((decision = 'pending') = (decided_at is null))
);

create table if not exists public.resource_locations (
  id uuid primary key default gen_random_uuid(),
  resource_id uuid not null references public.resource_registry(id) on delete cascade,
  source_alias_id bigint references public.resource_source_aliases(id) on delete set null,
  location_label text,
  location_type text not null check (location_type in ('fixed','service_area','virtual','mobile','confidential','undisclosed','unmapped')),
  original_address_text text,
  street_address text,
  city text,
  province text,
  postal_code text,
  country text not null default 'Canada',
  service_area text,
  latitude double precision check (latitude between -90 and 90),
  longitude double precision check (longitude between -180 and 180),
  geocode_source text,
  geocode_confidence double precision check (geocode_confidence between 0 and 1),
  geocode_status text not null default 'pending' check (geocode_status in ('pending','matched','verified','rejected','failed','not_required')),
  review_status text not null default 'pending' check (review_status in ('pending','approved','rejected','excluded','confidential')),
  public_map boolean not null default false,
  location_last_verified timestamptz,
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((latitude is null) = (longitude is null)),
  check (location_type = 'fixed' or latitude is null),
  check (not public_map or (location_type = 'fixed' and geocode_status = 'verified' and review_status = 'approved' and latitude is not null and longitude is not null))
);

create index if not exists resource_locations_resource_idx on public.resource_locations (resource_id);
create index if not exists resource_locations_public_coordinates_idx
  on public.resource_locations (latitude, longitude)
  where public_map and location_type = 'fixed' and geocode_status = 'verified' and review_status = 'approved';
create index if not exists resource_locations_city_idx on public.resource_locations (lower(city));

create table if not exists public.geocode_cache (
  id bigint generated by default as identity primary key,
  provider text not null,
  normalized_query text not null,
  query_hash text not null,
  response_summary jsonb,
  validation_status text not null check (validation_status in ('accepted','ambiguous','mismatch','no_result','failed')),
  error_summary text,
  created_at timestamptz not null default now(),
  unique (provider, query_hash)
);

create table if not exists public.resource_location_audit (
  id bigint generated by default as identity primary key,
  location_id uuid not null references public.resource_locations(id) on delete cascade,
  action text not null check (action in ('created','geocoded','corrected','approved','rejected','excluded','marked_confidential','publication_changed')),
  previous_values jsonb,
  new_values jsonb,
  actor_id uuid references auth.users(id),
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists resource_location_audit_location_idx on public.resource_location_audit (location_id, created_at desc);

alter table public.resource_registry enable row level security;
alter table public.resource_source_aliases enable row level security;
alter table public.resource_match_candidates enable row level security;
alter table public.resource_locations enable row level security;
alter table public.geocode_cache enable row level security;
alter table public.resource_location_audit enable row level security;

revoke all on table public.resource_registry, public.resource_source_aliases,
  public.resource_match_candidates, public.resource_locations, public.geocode_cache,
  public.resource_location_audit from anon, authenticated;

-- No client policies are intentionally created. The service-role backend performs
-- authorization and public responses include only approved registry resources with
-- explicitly verified, approved, fixed, public-map locations.

commit;
