import { useEffect, useState } from "react"
import { safeEmailAddress, safeHttpUrl } from "../safeLinks.js"

function formatDate(value) { if (!value) return "Not yet recorded"; return new Intl.DateTimeFormat("en-CA", { dateStyle: "medium" }).format(new Date(value)) }

function ListEntry({ item, crisis }) {
  const website = safeHttpUrl(item.website), email = safeEmailAddress(item.email)
  return <article className={`premade-entry ${crisis ? "is-crisis" : ""}`}><div><h3>{item.resource_name}</h3>{item.description ? <p>{item.description}</p> : null}</div><dl>{item.cost_information ? <><dt>Cost</dt><dd>{item.cost_information}</dd></> : null}{item.eligibility ? <><dt>Eligibility</dt><dd>{item.eligibility}</dd></> : null}{item.geographic_restriction ? <><dt>Area</dt><dd>{item.geographic_restriction}</dd></> : null}{item.contact_notes ? <><dt>Contact notes</dt><dd>{item.contact_notes}</dd></> : null}</dl><div className="resource-links">{item.phone ? <a className="resource-link-button" href={`tel:${item.phone.replace(/[^+\d]/g, "")}`}>Call {item.phone}</a> : null}{email ? <a className="resource-link-button" href={`mailto:${email}`}>Email</a> : null}{website ? <a className="resource-link-button" href={website} target="_blank" rel="noreferrer">Website</a> : null}</div></article>
}

export default function PreMadeLists({ onBack }) {
  const [lists, setLists] = useState([]), [selected, setSelected] = useState(null), [status, setStatus] = useState("Loading published lists…")
  useEffect(() => { fetch("/api/lists").then(async (response) => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error); setLists(body.items || []); setStatus(body.items?.length ? "" : "No pre-made lists have been published yet.") }).catch((error) => setStatus(error.message || "Lists are unavailable.")) }, [])
  async function openList(slug) { setStatus("Opening list…"); const response = await fetch(`/api/lists/${encodeURIComponent(slug)}`); const body = await response.json().catch(() => ({})); if (!response.ok) return setStatus(body.error || "The list could not be opened."); setSelected(body); setStatus(""); window.scrollTo({ top: 0, behavior: "smooth" }) }
  if (selected) return <main className="premade-lists-page"><div className="premade-toolbar"><button onClick={() => setSelected(null)}>← All pre-made lists</button><button onClick={() => window.print()}>Print / Save PDF</button></div><header><p className="eyebrow">Miller pre-made list</p><h1>{selected.list.title}</h1>{selected.list.introduction ? <p>{selected.list.introduction}</p> : null}<aside className="premade-disclaimer"><strong>Please verify before relying on this list.</strong> {selected.list.disclaimer}</aside><p>Last reviewed: {formatDate(selected.list.last_reviewed_at)}</p></header><nav className="premade-toc" aria-label="List sections"><h2>Sections</h2><ol>{selected.sections.map((section) => <li key={section.id}><a href={`#section-${section.id}`}>{section.title}</a></li>)}</ol></nav>{selected.sections.map((section) => { const crisis = /crisis/i.test(section.title); return <section className={crisis ? "premade-crisis-section" : "premade-section"} id={`section-${section.id}`} key={section.id}><h2>{section.title}</h2>{section.description ? <p>{section.description}</p> : null}<div className="premade-entry-grid">{section.items.map((item) => <ListEntry item={item} crisis={crisis} key={item.id}/>)}</div></section>})}</main>
  return <main className="premade-lists-page"><div className="premade-toolbar"><button onClick={onBack}>← Back to resources</button></div><header><p className="eyebrow">Curated and reviewed</p><h1>Pre-made Lists</h1><p>Browse topic-focused resource collections published by Miller administrators.</p></header><p role="status">{status}</p><div className="premade-list-grid">{lists.map((list) => <article className="premade-list-card" key={list.id}><p className="eyebrow">{list.category || "Community resources"}</p><h2>{list.title}</h2><p>{list.short_description}</p><p>{list.visible_entry_count} entries · reviewed {formatDate(list.last_reviewed_at)}</p><button onClick={() => openList(list.slug)}>Open list</button></article>)}</div></main>
}
