import MillerNorthPublicNav from "./MillerNorthPublicNav.jsx"
import "./MillerNorthMethodology.css"

export default function MillerNorthMethodology() {
  return <main className="mn-public-page mn-method-page">
    <header className="mn-public-header"><a href="/">← Miller resource finder</a><MillerNorthPublicNav current="methodology" /></header>
    <section className="mn-public-hero"><p className="mn-public-eyebrow">Miller North · Method</p><h1>How Miller North handles evidence</h1><p>Miller North organizes publicly available information about Indigenous healthcare experiences and what institutions did afterward. It keeps reports, formal findings, recommendations and implementation evidence distinct.</p></section>
    <ol className="mn-layer-flow"><li><strong><a href="/indigenous-healthcare-evidence/live-listening">Live Listening</a></strong><span>Recent public-source reports under review.</span></li><li><strong><a href="/indigenous-healthcare-evidence">Evidence Library</a></strong><span>More developed, reconciled incident and systemic evidence.</span></li><li><strong><a href="/indigenous-healthcare-evidence/research-policy">Research &amp; Policy</a></strong><span>Investigations, recommendations, government response and implementation.</span></li><li><strong><a href="/indigenous-healthcare-evidence/first-nations-supports">First Nations Supports</a></strong><span>Current public service information checked against operator or authoritative sources.</span></li></ol>
    <section className="mn-method-grid" aria-label="Evidence interpretation principles"><article><h2>Public sources</h2><p>Every displayed record follows a public source. Source links remain available so readers can inspect the underlying material.</p></article><article><h2>Reports are not findings</h2><p>A publicly reported experience or allegation is labelled as such. It is not presented as a formal finding unless an appropriate body made one.</p></article><article><h2>One event, several sources</h2><p>Multiple source records may describe one incident. Miller North can present them together without deleting the underlying evidence or counting each article as a separate incident.</p></article><article><h2>Evidence labels</h2><p>Labels describe what the available source supports. They are not moral judgments, legal conclusions or ratings of an organization.</p></article><article><h2>Missing evidence</h2><p>Not locating public evidence does not prove that an event or action did not occur. It means the current public record does not answer the question clearly.</p></article><article><h2>Implementation labels</h2><p>Recommendation statuses describe available public evidence. A policy, office or training program does not by itself prove effectiveness, compliance or improved outcomes.</p></article><article><h2>Governance and funding</h2><p>Who governs a service, who funds it and who delivers it are recorded separately. Public funding does not by itself establish operational control.</p></article><article><h2>Legal context</h2><p>Legal and human-rights material is included to explain the public record. Miller North does not provide legal advice.</p></article><article><h2>Privacy and anonymity</h2><p>Miller North does not try to identify anonymized patients. It uses the least personal detail needed to understand a public report.</p></article><article><h2>Dates and places</h2><p>Event dates and source-publication dates are kept separate. When an exact event date or facility is uncertain, the page uses a broader year or location.</p></article></section>
    <section className="mn-public-section mn-correction-path" id="corrections"><p className="mn-public-eyebrow">Corrections and source updates</p><h2>Help improve the public record</h2><p>A dedicated correction channel still needs privacy and handling review before launch. The planned pathway will accept a public source URL, page title, a concise explanation of the possible error or update, and the requested correction or removal review.</p><ul><li>Report a factual or source-link error.</li><li>Suggest a relevant public source.</li><li>Provide updated public implementation evidence.</li><li>Request correction or removal review.</li></ul><strong>Please do not submit confidential medical records or private personal information.</strong><p>Until the reviewed channel is available, no browser form on Miller North collects this information.</p></section>
    <footer className="mn-public-footer">Miller North is a living public-source research project. Publication and private research review remain separate.</footer>
  </main>
}
